using System.Collections.Generic;

namespace CompendioCalc.Services
{
    public partial class FormulaService
    {
        private void AdicionarFormulasVol12_Literal_Parte3()
        {
            AdicionarPacoteVol12Detalhado(
                "MECÂNICA QUÂNTICA RELATIVÍSTICA E QED",
                "QED e Mecânica Quântica Relativística",
                181,
                new List<Vol12FormulaSpec>
                {
                    new("Equação de Dirac", "(iγ^μ∂_μ − mc/ℏ)ψ = 0", "γ^μ=matrizes de Dirac 4×4. Inclui spin automaticamente. Prediz antipártículas.", "Dirac", "1928", "Elétron: m=0,511 MeV/c². Soluções: e⁻ (E>0) e pósitron (E<0, mar de Dirac). Anderson: pósitron em 1932"),
                    new("Constante de Estrutura Fina", "α = e²/(4πε₀ℏc) ≈ 1/137,036", "Governa a força de interação eletromagnética. Dimensionless. Mais precisa da física: 1/137,03599920...", "Sommerfeld", "1916", "α=7,297×10⁻³. Acoplamento e⁻-fóton: vértice=e=√(4πα). α varia com energia: α(MZ)=1/128. Running coupling"),
                    new("Fator g de Elétron — Anomalia Magnética", "g = 2(1 + α/2π + ...) = 2,00231930436256", "Desvio de g=2 predito pela equação de Dirac pura. QED em 5ª ordem. Verificação mais precisa.", "Schwinger; Aoyama et al.", "1948-2012", "g_exp=2,00231930436146(56). Concordância teoria-experimento: 10⁻¹². Nova física: g_muon discrepância 4,2σ"),
                    new("Espalhamento Compton Relativístico", "Δλ = λ_C(1−cosθ);  λ_C = h/(m_ec) = 2,426 pm", "Compton shift: fóton perde energia. λ_C=comprimento de Compton do elétron.", "Compton", "1923", "θ=90°: Δλ=2,426 pm. Fóton de 511 keV: E'=341 keV. Diagnóstico: efeito Compton dominante a 0,1–10 MeV"),
                    new("Seção de Choque Klein-Nishina", "dσ/dΩ = (r₀²/2)(E'/E)²(E'/E + E/E' − sin²θ)", "r₀=raio clássico do elétron. Reduz para Thomson a baixas energias. Anisotropia angular.", "Klein e Nishina", "1929", "Thomson: σ=8πr₀²/3=0,665 b. E=511 keV: σ_KN≈0,2 b. E=10 MeV: σ_KN≈0,03 b. Detectores de γ"),
                    new("Equação de Klein-Gordon", "(∂^μ∂_μ + (mc/ℏ)²)φ = 0", "Campo escalar relativístico. Partícula de spin 0 (pions, bóson de Higgs H). Não positivo definido.", "Klein; Gordon", "1926", "Pion π: m=140 MeV/c². Higgs H: m=125 GeV/c². KG=raiz do operador relativístico de energia"),
                    new("Lagrangeano de QED", "L_QED = ψ̄(iγ^μD_μ − m)ψ − (1/4)F^{μν}F_{μν}", "D_μ=∂_μ+ieA_μ: derivada covariante. F^{μν}=tensor de campo EM. Invariante de gauge U(1).", "Dirac; Tomonaga, Schwinger, Feynman", "1927-1965", "Simetria local U(1) gera eletromagnetismo. QED: teoria mais precisa da física. Lamb shift: 1058 MHz"),
                    new("Deslocamento de Lamb", "ΔE_Lamb = (8α⁵m_ec²)/(3π·n³)·f(Zα)", "Correção de QED a 1 loop (auto-energia do elétron + polarização do vácuo). Separa 2S₁/₂ e 2P₁/₂.", "Lamb e Retherford", "1947", "H 2S₁/₂−2P₁/₂: ΔE=1057,845 MHz (teórico). Experimento: 1058 MHz. Prova definitiva de QED"),
                    new("Efeito Casimir", "F_Casimir/A = −π²ℏc/(240d⁴)", "Força atrativa de vácuo quântico entre placas paralelas. Escala com d⁻⁴.", "Casimir", "1948", "d=100 nm: F/A=1,3×10⁻³ Pa. d=10 nm: 130 Pa. MEMS: força de Casimir relevante em gaps nanométricos"),
                    new("Produção de Par — Limiar", "E_γ ≥ 2m_ec² = 1,022 MeV  (campo nuclear)", "Criação de par e⁻+e⁺ perto de núcleo. Abaixo: efeito fotoelétrico ou Compton dominam.", "Anderson; Dirac", "1928-1932", "Fóton de 2 MeV: 80% de probabilidade de criação de par. Cascata EM: alternância Compton e par"),
                    new("Perda de Energia Bethe-Bloch", "−dE/dx = (4πNAz²e⁴ρZ)/(Amev²)·ln(2mev²/I)", "I=potencial de excitação médio. Pico de Bragg: máximo antes de parar. Base de radioterapia com íons.", "Bethe; Bloch", "1930-1933", "Próton de 100 MeV em água: dE/dx=7 MeV/cm. Pico de Bragg em 7,7 cm. Terapia com prótons: precisão milimétrica"),
                    new("Comprimento de Radiação", "X₀ ≈ 716·A/(Z²·ρ·ln(287/√Z))  [g/cm²]", "X₀: distância para perda de 1/e de energia por radiação (bremsstrahlung). Base de detectores.", "Particle Data Group", "Contemporâneo", "Pb: X₀=6,37 g/cm²=0,56 cm. Fe: X₀=13,84 g/cm²=1,76 cm. Calorímetro: 25X₀ para conter chuveiro EM"),
                    new("Radiação de Cherenkov", "cos θ_c = c/(nv) = 1/(nβ)", "θ_c=ângulo de emissão. v>c/n: emissão coerente de luz. Detector Cherenkov: identificação de partícula.", "Cherenkov; Frank e Tamm", "1934-1937", "Água: n=1,33. β=0,9: cosθ=0,83 → θ=34°. IceCube: Cherenkov de neutrinos. Kamiokande: oscilação ν"),
                    new("Modelo Padrão — Simetria de Gauge", "SU(3)_C × SU(2)_L × U(1)_Y", "SU(3): QCD (força forte). SU(2)×U(1): eletrofraca. 12 férmions + 4 bósons de gauge + Higgs.", "Glashow; Salam; Weinberg", "1961-1968", "Bóson de Higgs: m=125,1 GeV. Massas via mecanismo de Higgs. LHC: descoberta de H em 2012 (ATLAS/CMS)"),
                    new("Equação de Bethe para Núcleos", "ΔEpotencial = A(a_vol − a_sf·A^{-1/3} − a_coul·Z²/A^{1/3} − a_par·δ/√A)", "Fórmula da gota líquida. a_vol, a_sf, a_coul, a_par=parâmetros. Prediz massa nuclear.", "Bethe e Weizsäcker", "1935-1936", "Fe-56: a_vol=15,56, a_sf=17,23, a_coul=0,697 MeV. B/A pico em A=56: elemento mais estável. Fissão/fusão"),
                    new("Regra de Ouro de Fermi — Taxa de Decaimento", "Γ = 2π/ℏ |⟨f|H'|i⟩|² ρ(Ef)", "ρ(Ef)=densidade de estados finais. Aplicável a decaimento β, α, γ.", "Fermi; Dirac", "1927-1934", "Decaimento β: Γ∝G_F². Vida média do nêutron=879,6 s. Decaimento γ: regras de seleção de momento angular"),
                    new("Espectro Quark — Confinamento de QCD", "V(r) = −4αs/3r + k·r", "αs=constante de acoplamento forte, k=tensão de corda (~1 GeV/fm). Potencial Cornell.", "Eichten et al.", "1978", "Charmonium (cc̄): ψ/J=3097 MeV. Tensão k=0,18 GeV²=0,9 GeV/fm. Confinamento: V→∞ para r→∞"),
                    new("Oscilação de Neutrinos", "P(να→νβ) = sin²(2θ)·sin²(1,27·Δm²·L/E)", "θ=ângulo de mistura, Δm²=diferença de massas², L=distância, E=energia. Prova que neutrinos têm massa.", "Pontecorvo; Maki, Nakagawa, Sakata", "1957-1962", "Super-K: Δm²=2,5×10⁻³ eV², sin²(2θ)=1. Prêmio Nobel 2015 (Kajita e McDonald). MSW: efeito da matéria"),
                    new("Bremsstrahlung — Emissão de Fótons", "dN/dE_γ ∝ Z²·n·α·r₀²/E_γ", "Espectro contínuo. Elétron perde energia na aceleração por campo nuclear. Base de tubo de raios X.", "Bethe e Heitler", "1934", "Tubo de raios X 100 kVp: espectro de 0 a 100 keV. E_max=eV_tube. Filtração: remove energias baixas (menos penetrantes)")
                });

            AdicionarPacoteVol12Detalhado(
                "ECONOMETRIA E ANÁLISE DE SÉRIES TEMPORAIS",
                "Econometria e Séries Temporais",
                200,
                new List<Vol12FormulaSpec>
                {
                    new("Mínimos Quadrados Ordinários — Gauss-Markov", "β̂_OLS = (X'X)⁻¹X'y", "BLUE: Melhor Estimador Linear Não-Viesado. Condições: exogeneidade, homocedasticidade, sem autocorrelação.", "Gauss; Markov; Aitken", "1801-1934", "Regressão de salário: Y=β₀+β₁Educação+ε. β̂₁=0,08→8% de retorno por ano de educação. Heterocedasticidade: erro"),
                    new("Modelo ARIMA (p,d,q)", "(1−B)^d·Φ(B)·Xt = Θ(B)·εt", "d=diferenciação, Φ(B)=polinômio AR, Θ(B)=polinômio MA. B=operador de retardo. Box-Jenkins.", "Box e Jenkins", "1970", "PIB: ARIMA(1,1,1). AIC/BIC: seleção de ordens. ACF e PACF: diagnóstico. SARIMA: componente sazonal"),
                    new("Modelo GARCH(p,q) — Volatilidade Condicional", "σ²t = ω + Σαi·ε²t-i + Σβj·σ²t-j", "σ²t=variância condicional. GARCH(1,1): α+β<1 para estacionaridade. Captura clustering de volatilidade.", "Engle; Bollerslev", "1982-1986", "S&P500: α=0,10, β=0,85, ω=10⁻⁶. Persistência=0,95. Choque de mercado: σ eleva e decai lentamente. VaR"),
                    new("Cointegração e Correção de Erro (ECM)", "ΔYt = α(Yt-1−βXt-1) + γΔXt + εt", "α=velocidade de ajuste (α<0 para ECM estável). β=relação de longo prazo.", "Engle e Granger", "1987", "PIB e consumo: cointegrados se β=1. α=−0,3: 30% do desequilíbrio corrigido a cada período. VECM"),
                    new("Teste de Raiz Unitária — ADF", "τ = (ρ̂−1)/SE(ρ̂)  em ΔYt=ρYt-1+controls+εt", "H₀: raiz unitária (ρ=1). τ<τ_crítico: estacionária. Valores críticos de MacKinnon.", "Dickey e Fuller", "1979", "PIB nominal: ADF τ=−1,5 > −3,5 (5%): raiz unitária. Primeira diferença: τ=−8,2 → estacionária. KPSS"),
                    new("Variáveis Instrumentais — TSLS", "β̂_IV = (Z'X)⁻¹Z'y", "Z=instrumento: correlacionado com X, não com ε. Consistente se endogeneidade presente. Teste de Hausman.", "Wright; Theil; Sargan", "1928-1958", "Educação: instrumento=propximidade de universidade. Primeiro estágio: F>10. Sobreidentificação: teste J"),
                    new("Modelo de Painel — Efeitos Fixos", "Yit = αi + β'Xit + εit", "αi=efeito fixo individual. Elimina viés de variável omitida constante no tempo. Estimador within.", "Mundlak; Hausman", "1978", "Salários de trabalhadores: FE controla heterogeneidade invariante no tempo. Hausman: FE vs RE. FE robusto"),
                    new("Causalidade de Granger", "X causa-Granger Y se: MSE(Ŷ|Y_lag,X_lag) < MSE(Ŷ|Y_lag)", "Teste F na inclusão de lags de X. Não é causalidade causal: previsibilidade.", "Granger", "1969", "Taxa de juros → inflação? Teste GC com 4 lags. Espúria se não-estacionária. VAR: Granger multivariado"),
                    new("Regressão Quantílica", "min Σρτ(yi−xi'β);  ρτ(u)=u(τ−I(u<0))", "Estima efeito na mediana ou qualquer quantil. Robusto a outliers. Distribuição condicional.", "Koenker e Bassett", "1978", "Retorno de educação: efeito maior no quantil 90 de salário. OLS: médio. QR: heterogeneidade de efeitos"),
                    new("Processo de Wiener — Random Walk Contínuo", "dWt = ε√dt;  E[dW]=0, Var[dW]=dt", "Incrementos independentes, normal. Base de finanças quantitativas. BM com drift: dX=μdt+σdW.", "Bachelier; Einstein", "1900-1905", "Modelo de preços: S(t)=S₀exp((μ−σ²/2)t+σW). Opção Black-Scholes. Monte Carlo: N=10⁶ trajetórias"),
                    new("Modelo VAR(p) — Vetorial Autoregressivo", "Yt = A₁Yt-1 + A₂Yt-2 + ... + ApYt-p + εt", "Yₜ vetor k×1. Aᵢ matrizes k×k. IRF (impulse-response function): choque de 1 em εᵢ.", "Sims", "1980", "VAR com PIB, inflação, juros: IRF da taxa de juros → PIB. Cholesky: ordem importa. Forecast error variance decomp"),
                    new("Modelo de Regressão Descontínua — RDD", "τ_RDD = lim_{x→c⁺} E[Y|X=x] − lim_{x→c⁻} E[Y|X=x]", "Efeito causal no limiar c do running variable X. Sharp RDD: atribuição determinística.", "Thistlethwaite e Campbell; Hahn, Todd, Van der Klaauw", "1960-2001", "Nota de corte (50%) em programa social: RDD mede impacto causal. McCrary test: manipulação do running var"),
                    new("Estimador de Diferenças em Diferenças", "τ_DiD = (Ȳ¹post−Ȳ¹pre) − (Ȳ⁰post−Ȳ⁰pre)", "Tendência paralela: grupos tratado e controle teriam evoluído igualmente sem intervenção.", "Card e Krueger", "1994", "Salário mínimo em NJ vs PA: DiD → impacto no emprego. Sintético: augmented synth. Staggered DiD"),
                    new("Modelo de Escolha Discreta — Logit", "P(Y=1|X) = e^{Xβ}/(1+e^{Xβ})", "Efeito marginal: ∂P/∂X = β·P(1−P). MLE. Probit: CDF normal.", "McFadden", "1974", "Probabilidade de default: X=(LTV, DTI, FICO). Pseudo-R²=McFadden R²=1−LL_full/LL_null"),
                    new("VaR — Value at Risk", "VaR_α = −inf{l: P(perda>l)≤1−α}", "VaR(99%): perda máxima com 99% de confiança. Backtesting: 1% dos dias deve exceder VaR.", "J.P. Morgan RiskMetrics", "1994", "Carteira $1M, σ=1,5%/dia: VaR(99%)=1M×2,33×0,015=$35k. CVaR (Expected Shortfall): mais conservador"),
                    new("Decomposição de Beveridge-Nelson", "Yt = Trend_t + Cycle_t", "Tendência=random walk (permanente). Ciclo=estacionário. Base de teoria dos ciclos econômicos.", "Beveridge e Nelson", "1981", "PIB: tendência de longo prazo (crescimento potencial) + ciclo de negócios. HP filter: alternativo (Hodrick-Prescott)"),
                    new("Teste ARCH de Engle", "LM = n·R² ~ χ²(q)", "R²=de regressão dos resíduos quadrados em lags. LM>χ²_crit: efeitos ARCH presentes.", "Engle", "1982", "Retornos de ações: LM-stat=45>9,49 (5 lags, 5%): ARCH(5) presente. Usar GARCH para modelar volatilidade"),
                    new("Modelo de Difusão de Inovações — Bass", "dN/dt = (p+qN/M)(M−N)", "p=inovadores, q=imitadores, M=mercado potencial, N=adotantes acumulados.", "Bass", "1969", "Smartphones: p=0,003, q=0,38. Pico de adoção: t*=ln(q/p)/(p+q). Previsão de penetração de tecnologia"),
                    new("Índice de Complexidade Econômica", "ECI = u₁  (1ª autovetor normalizado de M̃)", "M̃=matriz de diversificação corrigida por ubiquidade. ECI alto: economia diversificada e sofisticada.", "Hidalgo e Hausmann", "2009", "Japão: ECI=2,5. Brasil: ECI=0,3. China: ECI aumentou 1 ponto em 20 anos. Prediz crescimento futuro")
                });

            AdicionarPacoteVol12Detalhado(
                "HIDROLOGIA E GESTÃO DE RECURSOS HÍDRICOS",
                "Hidrologia e Recursos Hídricos",
                219,
                new List<Vol12FormulaSpec>
                {
                    new("Método CN — SCS Chuva-Vazão", "Q = (P−Ia)²/(P−Ia+S); S=25400/CN−254", "CN=Curve Number. Ia=0,2S (abstração inicial). Q=escoamento superficial (mm).", "USDA-SCS", "1956", "Pastagem degradada: CN=78, P=100 mm: S=71,6, Ia=14,3, Q=47,9 mm. Urbanização: CN=85 → Q=60 mm"),
                    new("Manning — Escoamento em Canais Abertos", "Q = (1/n)·A·R^{2/3}·S^{1/2}", "n=coeficiente de rugosidade, A=área molhada, R=raio hidráulico=A/P_m, S=declividade.", "Manning", "1891", "Canal trapezoidal em concreto: n=0,013, R=1 m, S=0,001: V=1/0,013×1×0,032=2,4 m/s. Projeto de calha"),
                    new("Equação de Darcy-Weisbach", "hf = f·(L/D)·(V²/2g)", "f=fator de Darcy, L=comprimento, D=diâmetro, V=velocidade. Colebrook-White: f implícito.", "Darcy; Weisbach", "1845-1857", "D=300 mm, V=2 m/s, L=1000 m, f=0,02: hf=0,02×3333×0,2=13,3 m. EPANET: redes de distribuição de água"),
                    new("Equação de Hazen-Williams", "V = 0,8492·C·R^{0,63}·S^{0,54}", "C=coef. H-W (PVC novo=150, ferro envelhecido=100). Aplica-se para água a 16°C.", "Williams e Hazen", "1905", "D=200 mm (R=0,05 m), C=130, S=0,003: V=0,8492×130×0,05^{0,63}×0,003^{0,54}=0,83 m/s"),
                    new("Período de Retorno e Risco Hidrológico", "Risco = 1−(1−1/TR)^n", "TR=período de retorno, n=vida útil. Risco: excedência em n anos pelo menos uma vez.", "Chow, Maidment e Mays", "1988", "TR=100a, n=50a: R=1−0,99⁵⁰=39,5%. Projeto de obras: TR depende da criticidade da estrutura"),
                    new("Evapotranspiração de Referência — Penman-Monteith FAO", "ET₀ = [0,408Δ(Rn−G)+γ(900/(T+273))U₂(es−ea)] / [Δ+γ(1+0,34U₂)]", "Δ=declive da curva de pressão de vapor, γ=constante psicrométrica, U₂=vento a 2 m.", "Allen et al.", "1998", "T=25°C, Rn=15 MJ/m²/dia, U₂=2 m/s, es−ea=1,5 kPa: ET₀=5,5 mm/dia. Irrigação: IR=KcET₀−Pefetiva"),
                    new("Tempo de Concentração — Kirpich", "tc = 0,0195·(L/√S)^{0,77}  [min]", "L=comprimento do talvegue em m, S=declividade média (m/m). Bacia pequena e declivosa.", "Kirpich", "1940", "L=500 m, S=0,02: tc=0,0195×(500/0,141)^{0,77}=10,8 min. tc: base para escolha de t de projeto do hietograma"),
                    new("Distribuição de Gumbel para Cheias", "F(x) = exp(−exp(−(x−μ)/β))", "μ=moda, β=dispersão. Parâmetros: método dos momentos ou L-moments. Papel probabilístico.", "Gumbel", "1941", "Série de Q_max anuais: Ȳ=500 m³/s, s=100 m³/s. Q_100anos≈Ȳ+4,6s/1,28=Ȳ+360=860 m³/s. Ponte crítica"),
                    new("Muskingum — Propagação de Cheia em Rio", "O₂ = C₀I₂ + C₁I₁ + C₂O₁", "C₀+C₁+C₂=1. Parâmetros K (translação) e x (peso). Calibra com hidrogramas observados.", "McCarthy", "1938", "K=12 h, x=0,2: C₀=0,048, C₁=0,429, C₂=0,524. HEC-HMS: propagação em sistema de rios. TOPMODEL"),
                    new("OD em Rio — Equação de Streeter-Phelps", "D(t) = (kd·L₀)/(kr−kd)·(e^{−kd·t}−e^{−kr·t}) + D₀·e^{−kr·t}", "D=déficit de OD, kd=desoxigenação, kr=reaeração, L₀=DBO inicial. Base de autoepuração.", "Streeter e Phelps", "1925", "kd=0,1/d, kr=0,2/d, L₀=200 mg/L, D₀=0: Dc=kd·L₀/kr=100 mg/L a tc=5 dias. OD crítico→peixes morrem"),
                    new("Balanço Hídrico de Bacia", "ΔS = P − ET − Q − Percolação", "ΔS anual≈0 em regime. Bacia gauged: Q medido. ET estimado por Penman-Monteith.", "Thornthwaite e Mather", "1957", "São Francisco: P=900 mm, ET=700 mm, Q=190 mm, Percolação=10 mm. Defluência: regulação por reservatórios"),
                    new("Sedimentação em Reservatório — Trap Efficiency", "TE = 1 − 1/(1 + 0,1/C·V/Q_r)", "C=coef. de Brune, V=volume, Q_r=afluência. TE: fração de sedimento retida.", "Brune", "1953", "Reservatório V=10⁶ m³, Q_r=5 m³/s: C·V/Q_r=0,063. TE≈55%. Assoreamento: vida útil reduzida. Gestão"),
                    new("Escoamento Subterrâneo — Equação de Theis", "s(r,t) = (Q/4πT)·W(u);  u=r²S/(4Tt)", "s=rebaixamento, Q=vazão, T=transmissividade, S=coef. armazenamento, W(u)=integral de Theis.", "Theis", "1935", "T=100 m²/dia, S=0,001, Q=50 m³/h, r=50 m: u=0,15, W=1,5, s=0,15 m. Aquífero confinado. AquiferTest"),
                    new("Velocidade de Queda de Sedimento — Stokes", "ws = g·d²·(ρs−ρ)/(18μ)", "Válida para d<0,1 mm (Re_p<1). d>0,1 mm: Rubey ou van Rijn. Fonte de argila: ws=0,001 m/s.", "Stokes", "1851", "Areia fina d=0,1 mm: ws=1 mm/s. Argila d=2 μm: ws=4×10⁻⁶ m/s. Coagulação: ws aumenta. ETAs"),
                    new("Hidrograma Unitário — Nash-IUH", "u(t) = (t^{n-1}/K^n(n-1)!)·e^{-t/K}", "n=número de reservatórios lineares, K=constante de tempo. Parâmetros por regressão de pares P-Q.", "Nash", "1957", "Bacia 100 km²: n=3, K=2 h: pico a t=4 h, Q_pico=0,3/h. Convolução com hietograma: Q(t) total"),
                    new("Chuva de Projeto — Equação IDF", "i = a·TR^b/(t+c)^d  [mm/h]", "i=intensidade, TR=período de retorno, t=duração (min). Parâmetros a, b, c, d regionais.", "Bell; DAEE", "1969", "TR=25a, t=30 min, SP: i=1340×0,185×25^{0,182}/(30+10)^{0,886}=80 mm/h. Projeto de galerias de drenagem"),
                    new("Necessidade Hídrica de Culturas — FAO", "D_irrig = ET_c − P_ef", "P_ef=precipitação efetiva. ET_c=Kc×ET₀. Irrigação supre o déficit hídrico.", "Allen et al.", "1998", "Soja florescimento: Kc=1,15, ET₀=6 mm/d, P=2 mm/d: D=1,15×6−2=4,9 mm/d. Pivô central: lâmina bruta"),
                    new("Recarga de Aquífero — Método WTF", "R = Sy × ΔH/Δt", "Sy=porosidade específica, ΔH=elevação do nível d'água, Δt=intervalo de tempo. Recarga sazonal.", "Healy e Cook", "2002", "Sy=0,15 para areia. ΔH=0,5 m em 10 dias: R=0,15×0,5/10=7,5 mm/dia=75 mm em 10 dias. Recarga media anual"),
                    new("Qualidade de Água — Índice IQA", "IQA = Π(qi^wi);  Σwi=1", "qi=qualidade de cada parâmetro (0–100), wi=peso relativo. IQA>70: boa. <36: ruim.", "CETESB; NSF", "1970-1975", "pH=7(q=93,w=0,12), OD=8mg/L(q=84,w=0,17), turbidez=5NTU(q=90,w=0,10): contribuição parcial. IQA=76 (boa)"),
                    new("Balanço de Nutrientes em Rio — Fósforo", "dP/dt = carga − (sedimentação + assimilação)", "Eutrofização: P limita produção primária em rios e lagos. Modelo de Vollenweider para lagos.", "Vollenweider", "1968", "Lago raso: [P]=0,05 mg/L → eutrófico (>0,035). Carga crítica: Q_in×P_in/V_lago×qs. Modelo CE-QUAL-W2")
                });

            AdicionarPacoteVol12Detalhado(
                "PSICOLOGIA QUANTITATIVA E NEUROCIÊNCIA COGNITIVA",
                "Modelagem Cognitiva e Neurociência",
                239,
                new List<Vol12FormulaSpec>
                {
                    new("Modelo de Rescorla-Wagner — Aprendizagem Associativa", "ΔVi = αi·βi·(λ−ΣV)", "ΔV=mudança na força associativa, α=saliência do CS, β=taxa de aprendizagem, λ=valor máximo, ΣV=soma das associações.", "Rescorla e Wagner", "1972", "Condicionamento clássico: λ=1 (alimento), V inicial=0, α=β=0,5: ΔV=0,25 no 1º ensaio. Bloqueio de Kamin"),
                    new("Taxa de Desconto Hiperbólico", "V(D) = V₀/(1+k·D)", "D=atraso, k=taxa de desconto. Inconsistência temporal: k hiperbólico>desconto exponencial a curto prazo.", "Ainslie; Laibson", "1975-1997", "Impulsividade: k grande. Adicção: k↑↑. Intervenção: salience e comprometimento. Behavioural economics"),
                    new("Sinal BOLD de fMRI", "BOLD(t) = ∫s(τ)·h(t−τ)dτ", "h(t)=HRF (hemodynamic response function). s(τ)=atividade neural. Deconvolução: recupera s(τ).", "Ogawa et al.", "1990", "Duração de HRF: ~30 s. Peak a ~5 s. fMRI temporal: TR=2 s. GLM em SPM12: β=ativação de região"),
                    new("Modelo Drift-Diffusion — Tempo de Reação", "dX = v·dt + σ·dW (drift-diffusion)", "X=evidência acumulada, v=drift rate, σ=ruído, ±a=limiares. Velha vs acurácia.", "Ratcliff", "1978", "v alto: decisão rápida e correta. σ alto: errático. Esquizofrenia: v↓, σ↑. RT e % corretos: dados conjuntos"),
                    new("Memória — Curva de Esquecimento de Ebbinghaus", "R(t) = e^{−t/S}  (retenção)", "S=estabilidade da memória. Espaçamento (spaced repetition): aumenta S após cada retrieval.", "Ebbinghaus", "1885", "R(1 dia)=0,40 sem revisão. S=1. Anki: algoritmo SM-2 estima S por intervalo ótimo. Memória de longo prazo"),
                    new("Modelo de Dois Processos — Memória", "Probabilidade_reconhecimento = F + (1−F)·R", "F=familiaridade (rápida, automática), R=recoleção (lenta, episódica). Modelo de Yonelinas.", "Yonelinas; Mandler", "1980-1994", "Amnésia hipocampal: R↓↓, F preservada. ROC de memória: curva de assimetria revela proporção F vs R"),
                    new("IQ e Distribuição Normal", "IQ = 100 + 15·Z", "Z=(pontuação−média)/DP. MENSA: IQ>130 (top 2%). Fator g de Spearman: variância comum.", "Binet e Simon; Wechsler", "1905-1955", "IQ=130: Z=2,0 → top 2,3%. IQ=70: deficiência intelectual (Z=−2). Flynn effect: IQ↑3 pts/decade"),
                    new("Teoria da Detecção de Sinal — d'", "d' = z(H) − z(FA)", "H=taxa de acertos (hits), FA=falsos alarmes. d'>0: discriminação. C=critério de resposta.", "Green e Swets", "1966", "Radiologista: d'=2,5 (boa discriminação). Beta=e^{d'C}: conservador ou liberal. Aplicado a memória, percepção"),
                    new("Regressão Linear — Coef. de Correlação de Pearson", "r = Σ(xi−x̄)(yi−ȳ)/√[Σ(xi−x̄)²·Σ(yi−ȳ)²]", "r=−1 a 1. r²=variância explicada. Assumme linearidade e normalidade. Spearman: não-paramétrico.", "Pearson", "1895", "QI e notas: r=0,50 → r²=25% de variância. CI 95%: Fisher z-transform. n=30: z=arctanh(r)±1,96/√27"),
                    new("Modelo de Acumulador de Corrida — Horse Race", "P(resposta i) = P(accum_i atinge limiar primeiro)", "Múltiplos acumuladores independentes. Ganhe a corrida: resposta mais rápida. EX-Wald distributions.", "Logan; Vickers", "1970-1988", "Tarefa de escolha: 2 acumuladores Wald. Sinal e desvio: velocidade vs acurácia. Stop-signal: race model"),
                    new("Neurociência Computacional — Modelo de Hodgkin-Huxley", "Cm·dV/dt = −(INa+IK+IL) + Iext", "INa=gNa·m³h(V−ENa), IK=gK·n⁴(V−EK). m,h,n: portões de ativação/inativação.", "Hodgkin e Huxley", "1952", "gNa_max=120 mS/cm², gK_max=36 mS/cm². Potencial de ação: 1 ms. Velocidade de condução: 120 m/s em axônio mielinizado"),
                    new("Modelo de Neurônio Integra-e-Dispara", "τm·dV/dt = −(V−Vrest) + Rm·I(t)", "τm=constante de tempo da membrana. Disparo quando V=Vth. Reset para Vrest.", "Lapicque", "1907", "τm=20 ms, Vth=−55 mV, Vrest=−70 mV. Frequência: f=1/τm·ln((Rm·I−Vrest)/(Rm·I−Vth)). Redes neurais"),
                    new("Análise de Componentes Principais — PCA", "X_reduced = X·W;  W=top k eigenvectors de C=X'X/(n−1)", "Reduz dimensionalidade preservando variância. Eigenvalues: variância explicada.", "Pearson; Hotelling", "1901-1933", "fMRI: 300k voxels → 20 PCs. 80% da variância nos 5 primeiros PCs. Neuroimagem: denoising e compressão"),
                    new("Aprendizado por Reforço — Bellman", "V(s) = max_a[R(s,a) + γ·Σ P(s'|s,a)·V(s')]", "V=valor do estado, R=recompensa, γ=fator de desconto, P=probabilidade de transição.", "Bellman; Sutton e Barto", "1957-1998", "Q-learning: Q(s,a) converge para Q* com α<1 e exploração suficiente. DQN (DeepMind): Atari em 2013"),
                    new("Modelo Bayesiano de Percepção", "P(s|x) ∝ P(x|s)·P(s)", "s=estado do mundo, x=observação sensorial. Percepção=inferência bayesiana ótima.", "Helmholtz; Weiss et al.", "1867-2002", "Ilusão da tamanho-velocidade: prior de movimento lento → objeto maior interpretado como mais perto"),
                    new("Análise de Conjuntos de Populações Neurais — Decodificação", "s_estimado = Σ fi·ri / Σ ri  (centro de massa)", "fi=vetor de preferência do neurônio i, ri=taxa de disparo. Leitura de populações neurais.", "Georgopoulos et al.", "1986", "Neurônios do córtex motor: direção de movimento decodificada por vetor população. BCI: decodificação em tempo real"),
                    new("Modelos de Memória Operacional — Limite de Miller", "7 ± 2 chunks", "Capacidade da memória de trabalho: ~7 itens independentes. Chunking aumenta capacidade informacional.", "Miller", "1956", "Telefone: 7 dígitos = limite. Chunking: 'IBM-CIA' = 2 chunks. WM capacity prediz inteligência (g). Cowan: 4±1"),
                    new("Plasticidade Sináptica — Regra de Hebb", "ΔwAB = η·xA·xB", "w=peso sináptico, η=taxa de aprendizagem, x=atividade pré/pós. 'Neurônios que disparam juntos, conectam-se.'", "Hebb", "1949", "LTP: w↑ quando pré e pós ativados conjuntamente. LTD: atividade assíncrona. Spike-timing-dependent plasticity"),
                    new("Perceptron — Teorema de Convergência", "Número de atualizações ≤ (R/γ)²", "R=norma máxima das entradas, γ=margem de separação. Converge se dados são linearmente separáveis.", "Rosenblatt", "1958", "Perceptron de camada única: OR, AND. XOR: inseparável linearmente → multicamada (backprop). Deep learning")
                });
        }
    }
}