using System.Collections.Generic;

namespace CompendioCalc.Services
{
    public partial class FormulaService
    {
        private void AdicionarFormulasVol12_Literal_Parte2()
        {
            AdicionarPacoteVol12Detalhado(
                "Físico-Química e Cinética Química",
                "Cinética Química",
                101,
                new List<Vol12FormulaSpec>
                {
                    new("Equação de Arrhenius", "k = A·exp(−Ea/RT)", "Constante de velocidade k em função da energia de ativação Ea, temperatura T e fator pré-exponencial A.", "S. Arrhenius", "1889", "Ea=50 kJ/mol; aumento de 10°C ≈dobra velocidade de reação"),
                    new("Lei de Velocidade de Ordem n", "−d[A]/dt = k[A]ⁿ", "Taxa de desaparecimento de A; n=ordem; ordem 1: [A]=[A]₀e^(−kt); meia-vida=ln2/k.", "Van't Hoff", "1884", "Decomposição radioativa: n=1; hidrólise em excesso de água: n=0"),
                    new("Equação de van't Hoff", "d(ln K)/dT = ΔH°/(RT²)", "Variação da constante de equilíbrio K com temperatura; reação exotérmica: K↓ com T↑.", "J.H. van't Hoff", "1884", "Síntese de amônia (Haber-Bosch): ΔH°<0 → K↓ com temperatura"),
                    new("Energia de Gibbs", "ΔG = ΔH − TΔS;  ΔG = −RT ln K", "ΔG<0 reação espontânea; ΔG=0 equilíbrio; relaciona termodinâmica e cinética.", "J.W. Gibbs", "1876", "ΔH=−50 kJ/mol, ΔS=−100 J/(mol·K), T=300 K: ΔG=−20 kJ/mol"),
                    new("Equação de Nernst (Eletroquímica)", "E = E° − (RT/nF)·ln Q", "Potencial de célula em condições não-padrão; Q=quociente de reação, n=elétrons, F=Faraday.", "W. Nernst", "1897", "Célula Daniel com concentrações variadas; base do pH-metro"),
                    new("Equação de Butler-Volmer", "j = j₀[exp(αnFη/RT) − exp(−(1−α)nFη/RT)]", "Densidade de corrente de eletrodo; j₀=corrente de troca, η=sobretensão, α=coeficiente de transferência.", "J.A.V. Butler; M. Volmer", "1924-1930", "η pequena: linear; η grande: Tafel (exponencial)"),
                    new("Equação de Tafel", "η = a + b·log|j|;  b = RT·ln(10)/(αnF)", "Relação sobretensão–corrente em regime ativo; b=inclinação de Tafel; a=−b·log j₀.", "J. Tafel", "1905", "H₂ em Pt: b≈30 mV/década; em Fe: b≈120 mV/década"),
                    new("Lei de Raoult (Solução Ideal)", "pᵢ = xᵢ·p*ᵢ", "Pressão de vapor parcial em solução ideal; xᵢ=fração molar, p*ᵢ=pressão de vapor do puro.", "F.M. Raoult", "1882", "Mistura benzeno-tolueno é quase ideal; permite destilação fracionada"),
                    new("Isoterma de Langmuir", "θ = bP / (1 + bP)", "Fração de cobertura superficial θ; b=constante de equilíbrio, P=pressão; saturação quando P→∞.", "I. Langmuir", "1916", "Catálise heterogênea, adsorção de gases; base do modelo de Michaelis-Menten"),
                    new("Teoria do Estado de Transição (Eyring)", "k = (kBT/h)·exp(−ΔG‡/RT)", "Constante de velocidade via estado de transição; ΔG‡=energia de Gibbs de ativação.", "H. Eyring", "1935", "ΔG‡=60 kJ/mol, T=300 K: k≈70 s⁻¹"),
                    new("Equação de Debye-Hückel", "log γ± = −A|z₊z₋|·sqrt(I)", "Coeficiente de atividade γ± em solução eletrolítica diluída; I=força iônica, A=0,509 em água a 25°C.", "P. Debye, E. Hückel", "1923", "NaCl 0,01 mol/L: I=0,01, γ±≈0,89"),
                    new("Equação de Clausius-Clapeyron", "d(ln p*)/dT = ΔHvap/(RT²)", "Variação da pressão de vapor com temperatura; base de destilação e meteorologia.", "B.P.E. Clapeyron; R. Clausius", "1834-1850", "Água: ΔHvap=40,7 kJ/mol; T↑10°C dobra p* aproximadamente"),
                    new("Coeficiente de Difusão de Einstein-Stokes", "D = kBT / (6πηr)", "Coeficiente de difusão de partícula esférica de raio r em fluido de viscosidade η.", "A. Einstein; G.G. Stokes", "1905", "Proteína 5 nm em água a 25°C: D≈8,7×10⁻¹¹ m²/s"),
                    new("Henderson-Hasselbalch", "pH = pKa + log([A⁻]/[HA])", "pH de solução tampão em função da razão base/ácido conjugados.", "L.J. Henderson; K.A. Hasselbalch", "1908-1917", "Tampão acetato pH 5,0: pKa=4,76, [A⁻]/[HA]=1,75"),
                    new("Lei de Diluição de Ostwald", "Ka = Cα² / (1−α) ≈ Cα²  (α<<1)", "Grau de dissociação α de ácido fraco; Ka=constante de acidez, C=concentração total.", "W. Ostwald", "1888", "Ácido acético 0,1 M (Ka=1,8×10⁻⁵): α≈1,34%"),
                    new("Potencial Químico em Solução Ideal", "μᵢ = μ°ᵢ + RT·ln xᵢ", "Potencial químico do componente i em solução ideal; desvio requer coeficiente de atividade.", "J.W. Gibbs", "1876", "Base de diagramas de fase, ebuloscopia e crioscopia"),
                    new("Lei de Hess", "ΔH_rxn = Σ ΔHf(produtos) − Σ ΔHf(reagentes)", "Entalpia de reação é independente do caminho; soma de entalpias de formação padrão.", "G.H. Hess", "1840", "Combustão de CH₄: ΔH°=−802,3 kJ/mol calculado por Hess"),
                    new("Equação de Gibbs para Tensão Superficial", "dγ = −Σ Γᵢ dμᵢ", "Equação de adsorção de Gibbs; Γᵢ=excesso superficial, μᵢ=potencial químico.", "J.W. Gibbs", "1876", "Surfactante reduz γ da água de 72 para ~30 mN/m"),
                    new("Ciclo de Born-Haber", "ΔH_rede = ΔHf − ΣΔH_etapas", "Energia reticular de sólido iônico via ciclo termoquímico; combina ionização, afinidade eletrônica e sublimação.", "M. Born, F. Haber", "1919", "NaCl: ΔH_rede≈−787 kJ/mol calculada indiretamente"),
                    new("Temperatura de Ignição Espontânea (Frank-Kamenetskii)", "δ = (Ea·Q·A·ρ²·R²)/(λ·R_g·T²)·exp(−Ea/RT) = δcrit", "Parâmetro de Frank-Kamenetskii para ignição espontânea; δ>δcrit→explosão; δcrit≈0,88 para esfera.", "D.A. Frank-Kamenetskii", "1939", "Base de normas de segurança para armazenamento de materiais oxidantes")
                });

            AdicionarPacoteVol12Detalhado(
                "Geodésia e Cartografia",
                "Geometria Geodésica",
                121,
                new List<Vol12FormulaSpec>
                {
                    new("Fórmula de Haversine", "a = sin²(Δφ/2) + cosφ₁·cosφ₂·sin²(Δλ/2);  d = 2R·arcsin(sqrt(a))", "Distância de grande círculo entre dois pontos (φ,λ) na Terra esférica de raio R=6371 km.", "J. Inman", "1835", "São Paulo → Rio de Janeiro: d≈358 km"),
                    new("Projeção de Mercator", "x = R(λ−λ₀);  y = R·ln[tan(π/4+φ/2)]", "Projeção cilíndrica conforme; preserva ângulos mas distorce áreas; base de cartas náuticas.", "G. Mercator", "1569", "Groenlândia parece maior que EUA na projeção, mas área real é menor"),
                    new("Raio de Curvatura do Elipsoide", "N(φ) = a/sqrt(1−e²sin²φ);  M(φ) = a(1−e²)/(1−e²sin²φ)^(3/2)", "Raios de curvatura N (leste-oeste) e M (norte-sul) no elipsoide WGS84: a=6378137 m.", "Geodésia elipsoidal; WGS84", "1984", "No equador: N=M=a; nos polos: N=b²/a"),
                    new("Transformação de Helmert (7 parâmetros)", "[X Y Z]dest = [ΔX ΔY ΔZ] + (1+s)·R(ωx,ωy,ωz)·[X Y Z]orig", "Transformação entre datums via translação, rotação e escala.", "H. Helmert", "1880", "SAD69→WGS84 no Brasil: ΔX≈−67,35 m, ΔY=3,88 m, ΔZ≈−38,22 m"),
                    new("Projeção UTM (Gauss-Krüger)", "E = E₀ + k₀N[A + (1−T+C)A³/6 + …]", "Projeção conforme transversa de Mercator; k₀=0,9996; fuso de 6°; base do IBGE.", "C.F. Gauss; L. Krüger", "1822-1912", "Brasil zona UTM 22S (SIRGAS2000): uso em topografia e geoprocessamento"),
                    new("Altitude Ortométrica e Geóide", "H = h − N_geoidal", "Altitude ortométrica H = altitude elipsoidal h − ondulação geoidal N do MAPGEO.", "Geodésia física; MAPGEO (IBGE)", "Séc. XX", "Em SP: N≈−8 m; h_GPS≈742 m → H≈750 m"),
                    new("Equação de Bruns", "T = γ·N_geoidal;  ΔgFAC = −0,3086·h [mGal/m]", "Relação entre potencial perturbador T, gravidade normal γ e ondulação N; correção de ar-livre.", "E.H. Bruns", "1878", "Correção ar-livre: −3,086 mGal por 10 m de altitude"),
                    new("Acurácia GPS (CEP)", "CEP ≈ 0,59·sqrt(σ_N² + σ_E²)", "Erro circular provável; σ_N, σ_E=desvios norte/leste; 50% das posições caem dentro do CEP.", "Teoria de erros geodésicos", "Séc. XX", "GPS civil: CEP≈5–10 m; GPS+SBAS: CEP≈1–3 m"),
                    new("Integral de Stokes (Ondulação Geoidal)", "N = (R/4πγ) ∬ Δg·S(ψ) dσ", "Ondulação geoidal a partir de anomalias de gravidade Δg; base de EGM2008 e MAPGEO2015.", "G.G. Stokes", "1849", "Erro de omissão do EGM2008 ≈ 5–10 cm globalmente"),
                    new("Ângulo Azimutal Geodésico", "Az = arctan[sinΔλ·cosφ₂ / (cosφ₁·sinφ₂ − sinφ₁·cosφ₂·cosΔλ)]", "Azimute inicial de A→B na superfície esférica; medido do norte no sentido horário.", "Navegação esférica", "Séc. XIX", "São Paulo → Buenos Aires: Az≈206° (sul-sudoeste)"),
                    new("Escala Nominal de Mapa", "EN = 1:N;  d_mapa = d_real/N", "Relação entre distância no mapa e no terreno; 1:50000 → 1 cm = 500 m.", "Cartografia clássica", "Séc. XIX", "Carta IBGE 1:25000: precisão posicional ≈12,5 m"),
                    new("Erro de Fechamento Angular (Poligonal)", "E_angular = Σθ_obs − (n−2)·180°", "Erro de fechamento de poligonal de n lados; distribuído igualmente entre os ângulos.", "Topografia e levantamento de campo", "Séc. XX", "Poligonal 5 lados: soma esperada=540°; se obs=540°12'→E=+12'"),
                    new("Fechamento Linear de Poligonal", "Erro = sqrt[(ΣΔX)²+(ΣΔY)²];  precisão = erro/Σd", "Erro linear em poligonal fechada; distribuído proporcionalmente ao comprimento dos lados.", "Topografia e Levantamento", "Séc. XX", "Poligonal 2 km, erro=0,15 m: precisão 1:13000"),
                    new("Conversão ECEF para Geodésico (Bowring)", "φ = arctan[(Z+e'²b·sin³β)/(p−e²a·cos³β)];  β=arctan(aZ/bp)", "Conversão iterativa de coordenadas cartesianas ECEF (X,Y,Z) para geodésicas (φ,λ,h).", "B.R. Bowring", "1976", "Converge em 2–3 iterações com erro <0,1 mm"),
                    new("Mínimos Quadrados Geodésicos (Gauss-Markov)", "x̂ = (AᵀPA)⁻¹AᵀPl;  Σx = (AᵀPA)⁻¹", "Estimador ponderado; A=matriz de design, P=pesos, l=observações; base de todo ajustamento geodésico.", "C.F. Gauss; A.A. Markov", "1809-1900", "Usado em redes GPS, nivelamento e triangulação"),
                    new("Fator de Escala UTM", "k = k₀·[1 + (1/(2N²))·(λ−λ₀)²·cos²φ + …]", "Distorção linear na projeção UTM; k₀=0,9996 no meridiano central, máx≈1,0003 nos limites do fuso.", "Teoria de projeções conformes", "Séc. XX", "Distorção linear UTM <40 cm/km em fuso de 6°"),
                    new("Maré Terrestre Gravimétrica", "Δg_maré = −Σ (∂²V_mareal/∂r²) avaliado na superfície", "Variação de gravidade pela maré lunar/solar; amplitude até ±300 nGal; afeta gravimetria de precisão.", "Geodésia dinâmica", "Séc. XX", "Deve ser corrigida em levantamentos gravimétricos absolutos"),
                    new("Curvatura Gaussiana do Elipsoide", "K = 1/(R_M·R_N)", "Curvatura gaussiana; R_M, R_N=raios de curvatura principais norte-sul e leste-oeste.", "C.F. Gauss", "1827", "No equador: K≈(1/a)²; nos polos: K≈a/b²"),
                    new("Atraso Troposférico GNSS (Saastamoinen)", "Δρ_trop = 0,002277·sec(z)·[P + (1255/T+0,05)e − 1,16 tan²z]", "Atraso troposférico do sinal GNSS; P=pressão, T=temperatura, e=pressão de vapor; z=ângulo zenital.", "J. Saastamoinen", "1972", "Atraso zenital seco≈2,3 m; úmido≈0,1–0,4 m; requer correção em PPP"),
                    new("Correção de Bouguer (Gravimetria)", "ΔgB = ΔgFAC − 0,0419ρh  [mGal]", "Anomalia de Bouguer remove efeito da topografia; ρ=densidade da crosta, h=altitude.", "P. Bouguer", "1749", "Anomalia Bouguer negativa sobre montanhas indica raiz crustal")
                });

            AdicionarPacoteVol12Detalhado(
                "FOTOQUÍMICA E QUÍMICA DE RADICAIS",
                "Fotoquímica e Cinética de Radicais",
                141,
                new List<Vol12FormulaSpec>
                {
                    new("Lei de Beer-Lambert", "A = ε·c·l", "A=absorbância, ε=absortividade molar [L/mol/cm], c=concentração, l=caminho óptico. Base de espectroscopia.", "Beer; Lambert; Bouguer", "1729-1852", "β-caroteno: ε=134000 L/mol/cm a 450 nm. c=10⁻⁵ M, l=1 cm: A=1,34. Linearidade: A<2. UV-Vis, HPLC"),
                    new("Rendimento Quântico de Fotorreação", "Φ = moles reagidos / einstein absorvido", "Φ≤1 por Stark-Einstein (exceto reações em cadeia). Φ=0: fotofísico, não fotoquímico.", "Stark; Einstein", "1908-1912", "Clorofila: Φ_fl=0,02. H₂O₂ fotólise a 254 nm: Φ=0,5. TiO₂: Φ_degradação≈0,1. Medição por actinometria"),
                    new("Cinética de Radical em Estado Estacionário", "[R]ss = √(Ri/kt)", "Ri=taxa de iniciação, kt=constante de terminação. [R]ss~10⁻⁸ M. Válido quando d[R]/dt≈0.", "Bodenstein", "1913", "Autooxidação de lipídeos: [ROO]ss=10⁻⁸ M. Inibidor (α-tocoferol): reduz Ri → vida de prateleira×10"),
                    new("Fotocatálise TiO₂ — Geração de Radicais", "TiO₂ + hν(λ<390nm) → e⁻CB + h⁺VB → ·OH", "h⁺VB + H₂O → ·OH + H⁺. e⁻CB + O₂ → O₂·⁻. Oxidação de poluentes orgânicos.", "Fujishima e Honda", "1972", "TiO₂ anatase: Eg=3,2 eV. ·OH degradação de atrazina: k=3×10⁹ M⁻¹s⁻¹. TiO₂ dopado N: ativo em visível"),
                    new("Reação de Fenton", "Fe²⁺ + H₂O₂ → Fe³⁺ + ·OH + OH⁻  k=76 M⁻¹s⁻¹", "·OH: E°=2,8 V vs NHE. Photo-Fenton: UV recicla Fe³⁺→Fe²⁺. Tratamento de efluentes industriais.", "Fenton", "1894", "pH=3 ótimo, [Fe²⁺]=5 mg/L, [H₂O₂]=50 mg/L: degradação 90% de fenol em 30 min. AOP avançado"),
                    new("Fotólise de Ozônio Estratosférico", "O₃ + hν(λ<320 nm) → O(¹D) + O₂; O(¹D)+H₂O→2·OH", "·OH: principal oxidante troposférico. Ciclo de Chapman: produção e destruição de O₃.", "Chapman; Dobson; Crutzen", "1930-1995", "[·OH]troposférico=10⁶ moléculas/cm³. CH₄: t½≈9 anos por ·OH. CFC: catalisa destruição de O₃ estratosférico"),
                    new("Tempo de Vida de Fluorescência", "I(t) = I₀·e^{−t/τ}", "τ=1/(kr+knr). kr=taxa radiativa, knr=não-radiativa. FLIM=fluorescence lifetime imaging.", "Base de espectroscopia de fluorescência", "Séc. XX", "Rodamina 6G: τ=4 ns. GFP: τ=2,4 ns. FLIM-FRET: mede distâncias de 2–10 nm in vivo. TCSPC: resolução ps"),
                    new("Equação de Marcus — Transferência Eletrônica", "kET = (4π²/h)·|HDA|²·(FC)", "HDA=acoplamento eletrônico, FC=fator Franck-Condon. kET máximo quando ΔG°=−λ (zona normal).", "Marcus", "1956", "Célula solar orgânica: dissociação de éxciton via Marcus. λ=reorganização interna+solvente. Parábolas"),
                    new("Transferência de Energia de Förster — FRET", "E = 1/(1+(r/R₀)⁶)", "R₀=raio de Förster (~5–8 nm). E=50% a r=R₀. Espectro de doador e aceitante deve se sobrepor.", "Förster", "1948", "Cy3/Cy5: R₀=6 nm. E=0,9: r=3,8 nm. smFRET: dinâmica de dobramento de proteínas em molécula única"),
                    new("Foto-Oxidação de Poluentes — Ozônio", "d[C]/dt = −kO₃[O₃][C] − k·OH[·OH][C]", "kO₃, k·OH=constantes de segunda ordem. Ozônio direto + indireto via ·OH.", "Hoigné e Bader", "1983", "Diclofenaco: kO₃=10⁶ M⁻¹s⁻¹, k·OH=7×10⁹ M⁻¹s⁻¹. [O₃]=2 mg/L: t½=10 s. ETA avançada: PPCPs"),
                    new("Quimiluminescência — Luminol", "Φ_CL = η_excit × Φ_fl × Φ_reação", "η_excit=fração em estado excitado, Φ_fl=rendimento de fluorescência, Φ_reação=rendimento de reação.", "White e Roswell", "1970", "Luminol + H₂O₂ + Fe: Φ_CL=0,01. Forense: traços de sangue (hemoglobina catalisa). ELISA quimioluminescente"),
                    new("Constante de Velocidade de Reação de ·OH com VOC", "k·OH ≈ 10⁸ a 10¹⁰ M⁻¹s⁻¹", "Limitada por difusão para alcenos e aromáticos. Base de modelagem de qualidade de ar.", "Atkinson et al.", "2006", "Tolueno: k·OH=5,6×10⁹ M⁻¹s⁻¹. [·OH]=10⁶ molec/cm³=10⁻¹² M: t½=9h. São Paulo: aerossol secundário"),
                    new("Fotossíntese — Eficiência Quântica de PSII", "ΦPSII = (Fm'−Fs)/Fm'", "Fm'=fl máxima em luz (saturação), Fs=fl em estado estacionário. Medido por PAM fluorometer.", "Genty, Briantais e Baker", "1989", "Planta saudável: ΦPSII=0,6–0,8. Estresse hídrico: ΦPSII<0,4. ETR=ΦPSII×PAR×0,5×0,84. Fotoinibição"),
                    new("Oxidação de Lipídios — Número de Peróxido", "IP(t) = IP₀·e^{k_ox·t}", "IP=índice de peróxido. k_ox=constante de oxidação. ASLT=acclerated shelf-life test.", "Labuza", "1971", "Azeite a 60°C: k_ox=0,03 d⁻¹. IP=20 meq/kg: rançoso. Tocoferol reduz k_ox 10×. Embalagem N₂: k↓3×"),
                    new("Ozonólise de Alcenos", "CnH₂n + O₃ → produtos carbonílicos + H₂O₂", "Clivagem da dupla C=C. Intermediário molozônio → zwitterion Criegee. Base de síntese orgânica e atmosfera.", "Criegee", "1975", "Oleato (ácido oléico): ozonólise → nonanal + ácido azelaico. Atmosfera: SOA por ozonólise de terpenos"),
                    new("Espectroscopia Raman — Deslocamento", "Δν̃ = ν̃laser − ν̃espalhado [cm⁻¹]", "Stokes: luz perde energia. Anti-Stokes: ganha. Bandas: modos vibracionais moleculares.", "Raman", "1928", "Grafeno: G=1582 cm⁻¹, 2D=2700 cm⁻¹. Diamante: 1332 cm⁻¹. SERS: amplificação 10⁸× por nanopartícula Au"),
                    new("Decaimento de Fosforescência", "I_p(t) = I₀·e^{−t/τT}  (T₁→S₀)", "τT=tempo de vida de tripleto. ISC (intersystem crossing): S₁→T₁. τT=μs a s.", "Jablonski", "1935", "Eosina Y: τT=0,5 ms. PDT: fotossensibilizador de longa τT gera ¹O₂. OLEDs fosforescentes: η_IQE=100%"),
                    new("Geração de Singlete de Oxigênio", "¹O₂ gerado por sens*+³O₂ → ¹O₂  (tipo II)", "¹O₂: 22 kcal/mol acima de ³O₂. τ=4 μs em água. Oxidação de biomoléculas.", "Foote e Wexler", "1964", "Rosa bengal: Φ_Δ=0,76. Porfirinas: Φ_Δ=0,5–0,9. PDT de câncer: ¹O₂ mata células tumorais"),
                    new("Fotodegradação Direta de Micropoluente", "−d[C]/dt = Φ_λ·ε_λ·[C]·E₀_λ×2,303", "E₀=irradiância fotônica, Φ_λ=rendimento quântico, ε_λ=absortividade molar.", "Leifer", "1988", "Diclofenaco: Φ=0,003, ε=3500 L/mol/cm. t½ em rio=1,5 dias. Atenolol: Φ≈0 (não fotodegrada diretamente)"),
                    new("Efeito Fotovoltaico — Corrente de Curto-Circuito", "JSC = q·∫EQE(λ)·Φ_ph(λ)dλ", "EQE=eficiência quântica externa, Φ_ph=fluxo de fótons. AM1.5G: irradiância=1000 W/m².", "Base de dispositivos fotovoltaicos", "Séc. XX", "Si c-Si: JSC=40 mA/cm². GaAs: JSC=28 mA/cm². Perovskita: JSC=25 mA/cm². JSC×VOC×FF=PCE×Pin")
                });

            AdicionarPacoteVol12Detalhado(
                "BIOLOGIA EVOLUTIVA E GENÉTICA DE POPULAÇÕES",
                "Evolução e Genética de Populações",
                161,
                new List<Vol12FormulaSpec>
                {
                    new("Equilíbrio de Hardy-Weinberg", "p² + 2pq + q² = 1  (p+q=1)", "p=freq alelo A, q=freq alelo a. Equilíbrio sem evolução: ausência de seleção, mutação, deriva, migração.", "Hardy; Weinberg", "1908", "Fenilcetonúria: q²=1/10000 → q=0,01. Heterozigotos: 2pq=2% da população. Triagem neonatal"),
                    new("Equação de Breeder's — Resposta à Seleção", "R = h²·S", "R=mudança fenotípica por geração, h²=herdabilidade, S=diferencial de seleção.", "Fisher; Falconer", "1918-1960", "Altura humana: h²=0,8, S=5 cm: R=4 cm/geração. Leite em bovinos: h²=0,25. Seleção genomica"),
                    new("Deriva Genética — Variância de Frequência", "Var(Δp) = p(1−p)/(2Ne)", "Ne=tamanho efetivo populacional. Deriva dominante quando Ne pequeno. σ=√Var.", "Wright", "1931", "Ne=100: σ=0,035/geração. Ne=10000: σ=0,0035. Gargalo: Ne temporariamente pequeno → perda de variação"),
                    new("Equação de Price — Mudança Evolutiva", "ΔZ̄ = Cov(w,z)/w̄ + E[w·Δz]/w̄", "Decompõe mudança em seleção (covariância) + transmissão. Generaliza todos os modelos evolutivos.", "Price", "1970-1972", "Altruísmo: Cov(w,z)=seleção individual (negativo). E[wΔz]=transmissão. Seleção multinível explícita"),
                    new("Regra de Hamilton — Altruísmo", "rB > C", "r=coef. de parentesco, B=benefício ao receptor, C=custo ao ator. Seleção de parentesco (kin selection).", "Hamilton", "1964", "Operária de abelha: r=0,75 (haplodiplóide). B=reprodução da rainha, C=trabalho: 0,75B>C → altruísmo evolui"),
                    new("Teoria Neutra — Taxa de Substituição Molecular", "k = μ  (taxa de substituição = taxa de mutação)", "Substituições neutras fixam pela taxa de mutação, independente de Ne. k>μ: seleção positiva.", "Kimura", "1968", "Citocromo c: k=3×10⁻⁹/sítio/ano. Histona H4: k=0,01×10⁻⁹ (fortemente conservada). Fibrinopeptídeo: k alto"),
                    new("Distância Genética — Jukes-Cantor", "d = −3/4·ln(1 − 4/3·p)", "p=fração de sítios com diferença nucleotídica. Corrige para substituições múltiplas no mesmo sítio.", "Jukes e Cantor", "1969", "p=0,05: d_JC=0,053. p=0,20: d_JC=0,24 (vs p=0,20). Kimura 2P: mais realista para transições/transversões"),
                    new("Máxima Verossimilhança Filogenética", "L(T,θ|D) = P(D|T,θ) = Π sites P(coluna|T,θ)", "T=topologia de árvore, θ=parâmetros do modelo evolutivo. Otimiza topologia e parâmetros.", "Felsenstein", "1981", "IQ-TREE: ML com GTR+Γ+I. Bootstrap 1000 réplicas. BEAST: inferência Bayesiana + relógio molecular"),
                    new("Coevolução — Dinâmica de Rainha Vermelha", "dp_host/dt = β(p_parasita − p_host)", "Oscilações na frequência de alelos de resistência vs virulência. Frequência-dependência negativa.", "Van Valen; Hamilton", "1973", "MHC em vertebrados: maior variabilidade no genoma → vantagem do alelo raro. Ciclos de predador-presa"),
                    new("Tempo de Fixação de Alelo Neutro", "t̄fix = −4Ne[p·lnp + (1−p)·ln(1−p)]", "p=frequência inicial do alelo. t̄fix máxima para p=0,5. Em gerações.", "Kimura e Ohta", "1969", "p=0,5, Ne=100: t̄fix=277 gerações. Ne=10000: t̄fix=27700 gerações. Gargalo: fixação acelerada"),
                    new("Seleção Purificadora — Equilíbrio Mutação-Seleção", "q̂ = √(μ/s)  (recessivo deletério)", "q̂=frequência de equilíbrio do alelo deletério. μ=taxa de mutação, s=coef. de seleção.", "Fisher; Wright", "1930-1937", "PKU: s=0,9, μ=10⁻⁵: q̂=√(10⁻⁵/0,9)=0,0033. Observado ~0,01. Heterozigoto advantagem possível"),
                    new("Relógio Molecular — Calibração", "t = d/(2k)", "t=tempo de divergência, d=distância genética corrigida, k=taxa de substituição. Fóssil calibra k.", "Zuckerkandl e Pauling", "1965", "Humano-chimpanzé: d=0,013, k=1,3×10⁻²/Myr: t=0,013/(2×0,013)=0,5×10=5 Myr. Consistente com fósseis"),
                    new("GWAS — Correção de Bonferroni", "p_limiar = 0,05/M = 5×10⁻⁸  (M=10⁶ SNPs)", "Correção para testes múltiplos. p<5×10⁻⁸: associação genômica robusta.", "Risch e Merikangas; WTCCC", "1996-2007", "GWAS de altura: 3000+ loci com p<5×10⁻⁸. Cada loci: efeito<1 mm. PRS (polygenic risk score): soma de efeitos"),
                    new("Seleção Sexual — Princípio de Zahavi", "H = r·B − C > 0  (handicap principle)", "Sinal custoso e honesto: só indivíduos com alta qualidade genética podem custear o ornamento.", "Zahavi; Hamilton e Zuk", "1975-1982", "Cauda do pavão: custo de predação, mas sinaliza sanidade parasitária. Preferência feminina por ornamento"),
                    new("Pressão de Seleção em Evolução Experimental", "Δf = s·f(1−f)/w̄", "f=frequência do genótipo favorável. w̄=aptidão média. Evolução em tempo real observável.", "Base de evolução experimental (Lenski, E. coli LTEE)", "Séc. XX", "E. coli LTEE: linhagens divergem em 50.000 gerações. Aquisição de catabolismo de citrato: inovação evolutiva"),
                    new("Especiação Alopátrica — Modelo de Allopatric", "Fluxo gênico: m<s/(1+s)  para diferenciação", "m=taxa de migração, s=coef. de seleção. Isolamento suficiente para divergência.", "Mayr", "1942", "Tentilhões de Darwin: isolamento por barreira geográfica + seleção de nicho de bico. Galapagos=laboratório"),
                    new("Distribuição de Efeitos de Mutações", "DFE: a maioria deletéria, poucas neutras, raras benéficas", "P(s>0) muito pequena. s de benéficas exponencialmente distribuído. Purificação remove deletérias.", "Eyre-Walker e Keightley", "2007", "Levedura: DFE bimodal. Humano: ~50% de novas mutações levemente deletérias. Taxa de mutação: 1-2 por genoma/geração"),
                    new("Fórmula de Haldane — Metapopulação", "p_ext = (1 − λ)^N", "p_ext=probabilidade de extinção de metapopulação de N populações locais. λ=taxa de colonização.", "Levins; Hanski", "1969-1998", "N=10 fragmentos, λ=0,3: p_ext=(0,7)¹⁰=0,028. Fragmentação de hábitat: metapopulação em risco. RPPN"),
                    new("Valor de Acasalamento Genômico (GEBV)", "GEBV = Σ aᵢ·SNPᵢ", "aᵢ=efeito de cada SNP estimado por BLUP genômico. Base de melhoramento animal de precisão.", "Meuwissen, Hayes e Goddard", "2001", "Gado Nelore: GEBV para ganho de peso com 50k SNPs. Acurácia=0,70. Reduz intervalo geracional. Seleção genomica"),
                    new("Modelos Lineares Mistos — BLUP", "ŷ = Xβ + Zu;  û = GZ'V⁻¹(y−Xβ)", "G=matriz de relações genéticas, V=var-cov fenotípica. BLUP=Best Linear Unbiased Prediction.", "Henderson", "1950", "Galinhas: produção de ovos BLUP com 100k registros de parentesco. REML estima variâncias. ASReml, DMU")
                });
        }
    }
}