using System.Collections.Generic;

namespace CompendioCalc.Services
{
    public partial class FormulaService
    {
        private void AdicionarFormulasVol12_Literal_Parte4()
        {
            AdicionarPacoteVol12Detalhado(
                "QUÍMICA VERDE E SUSTENTABILIDADE QUÍMICA",
                "Química Verde e Sustentabilidade",
                258,
                new List<Vol12FormulaSpec>
                {
                    new("Fator E — Eficiência Ambiental", "E-factor = kg_resíduos/kg_produto", "E-factor ideal: 0 (zero resíduo). Indústria farmacêutica: E=25–100. Química fina: E=5–50.", "Sheldon", "1992", "Ibuprofeno clássico: E=26 (6 etapas). BHC process: E=1 (1 etapa, catálise). Prêmio Presidential Green Chem"),
                    new("Atom Economy — Eficiência de Átomo", "AE = PM_produto_desejado/(Σ PM_reagentes) × 100%", "100%: todos os átomos entram no produto. Base de síntese convergente e catálise.", "Trost", "1991", "Adição simples: AE=100%. Substituição: AE<100% (subproduto). Reação de Diels-Alder: AE=100% (ideal)"),
                    new("Rendimento de Reação em Verde", "RME = Y × AE × CE × SF", "RME=green metric combinado. Y=rendimento, AE=atom economy, CE=eficiência de solvente, SF=segurança.", "Curzons et al.", "2001", "Síntese de aspirina: Y=0,85, AE=0,76, CE=0,70, SF=0,9: RME=0,40=40%. Processos: meta RME>0,5"),
                    new("Catálise — Número de Rotação (TON)", "TON = moles_produto/moles_catalisador", "TON alto: catalisador eficiente. TOF=TON/tempo=rotações por hora. Catálise industrial: TON>10⁶.", "Base de catálise homogênea e heterogênea", "Séc. XX", "Haber-Bosch (Fe): TOF=0,01 s⁻¹ a 400°C. Metátese de olefina (Grubbs): TON=10⁶. Catálise enzimática: TOF=10⁴/s"),
                    new("Intensidade de Carbono — Ciclo de Vida", "CI = kg_CO₂eq / unidade de produto", "LCA completo: extração + fabricação + uso + fim de vida. Fronteiras importantes.", "ISO 14040/14044", "Contemporâneo", "Cimento: CI=0,9 kg CO₂eq/kg. Açúcar de cana: CI=0,2 (etanol: crédito). EV vs ICE: LCA de 150k km"),
                    new("Índice de Segurança de Processo — EI", "EI = ΣEᵢ·wᵢ  (índice de Dow)", "EI de Dow F&EI: fogo+explosão. Índice de IA Dow: saúde. Base de HAZOP e PHA.", "Dow Chemical", "1994", "Destilação de hidrocarbonetos: F&EI=150 (risco alto). Catalisador sólido substitui ácido líquido: EI↓30%"),
                    new("Pressão de Vapor — Antoine (base de solvente verde)", "log P = A − B/(C+T)", "P=pressão de vapor, T=temperatura. Solvente verde: baixa pressão de vapor (menor VOC).", "Antoine", "1888", "Água a 25°C: P=3,2 kPa. Acetona: P=25 kPa. 2-MeTHF: P=8,4 kPa (menos volátil que THF). Solvente verde"),
                    new("Eficiência de Carbono", "CE_carbono = C_no_produto/(C_nos_reagentes) × 100%", "Conta apenas carbonos incorporados. Complementa AE para reações com carbono.", "Base de química verde (Constable et al.)", "2002", "Síntese de ácido adípico: CE=67%. Rota bio: ciclohexano→adipato por P. putida. CE=100%. Biocatálise"),
                    new("Índice de Solvente Verde — GSK", "Score_solvente = f(saúde, segurança, ambiente)", "Escala de 1–10. Água e etanol: score alto. Cloreto de metileno: score baixo.", "Jiménez-González et al.", "2011", "Clorofórmio: score=2 (ruim). EtOH: score=7. 2-MeTHF: score=6. ACS Pharmaceutical Roundtable guide"),
                    new("Reação de Metatese de Olefina — Grubbs", "k_cat = TOF × [catalisador]  [mol/L/s]", "Metatese: quebra e formação de C=C. Catalisador de Ru. Síntese de produtos naturais e polímeros.", "Chauvin, Schrock, Grubbs", "2005", "Grubbs 2ª geração: TON=10⁶, TOF=1000/h. Síntese de Romidepsina: metatese de fecho de anel. Pharma"),
                    new("Fotocatálise Solar — Eficiência STH", "STH = ΔG_H₂/(P_solar × A)", "STH=solar-to-hydrogen efficiency. ΔG_H₂=237 kJ/mol. P_solar=100 mW/cm² (AM1.5G).", "Base de produção solar de H₂", "Séc. XXI", "GaN:ZnO: STH=0,1%. BiVO₄: STH=1,7%. Tândem: STH=30% (teórico). Objetivo DOE: STH>20% por $2/kg H₂"),
                    new("Dissolução de CO₂ — Química do Carbono Dissolvido", "CO₂(aq) + H₂O ⇌ H₂CO₃ ⇌ HCO₃⁻ + H⁺  K₁=4,3×10⁻⁷", "pH do oceano: depende de pCO₂ atmosférico. Acidificação oceânica: pH caiu 0,1 desde industrialização.", "Base de química do carbono inorgânico dissolvido", "Séc. XX", "pCO₂=420 ppm: [H₂CO₃*]=13 μM. pH=8,1. 2100: pH=7,7 (RCP8.5). Corais: CaCO₃ dissolve a Ωar<1"),
                    new("Eletrossíntese — Eficiência Faradaica", "FE = n·F·moles_produto/(carga_total)", "n=elétrons por mol de produto, F=constante de Faraday=96485 C/mol. FE=1: seletividade perfeita.", "Base de eletroquímica sintética", "Séc. XX", "CO₂ → CO: FE=95% em Au. CO₂ → CH₄: FE=60% em Cu. N₂ → NH₃: FE<1% (desafio). Eletrorredutor de CO₂"),
                    new("Intensidade de Água — WI em Química", "WI = L_água/kg_produto", "WI ideal: mínimo. Indústria farmacêutica: WI=1000–10000 L/kg. Química verde: solventes recicláveis.", "Jiménez-González et al.", "2000", "Ibuprofeno clássico: WI=10000 L/kg. Rota verde (catálise): WI=1000 L/kg. Farmácia: maior consumidor de água"),
                    new("Pirólise de Biomassa — Rendimento em Bio-óleo", "Y_bio-óleo = f(T, τ, tipo de biomassa)", "Flash pyrolysis: T=500°C, τ<2s. Y=60–75% de bio-óleo. Bio-carvão: T alto, tempo longo.", "Bridgwater", "2012", "Madeira de eucalipto: Y_bio-óleo=70%, Y_biochar=15%, Y_gás=15%. Upgrading: HDO→combustível de aviação"),
                    new("Reação de Fischer-Tropsch — Distribuição ASF", "W_n = (1−α)²·n·α^{n-1}", "α=probabilidade de crescimento de cadeia, n=número de carbonos. α alto: ceras. α=0,75: diesel.", "Fischer e Tropsch; Anderson-Schulz-Flory", "1926", "Fe ou Co catalisador. Alimentado por syngas (CO+H₂). GTL: Gas-to-Liquids (Qatar). α=0,75: diesel ótimo"),
                    new("Índice de Dispersão de Polímero — PDI", "PDI = Mw/Mn ≥ 1", "Mn=média numérica, Mw=média ponderal. PDI=1: monodisperso. RAFT/ATRP: PDI<1,1 (controlado).", "Flory", "1936", "PS por radicais livres: PDI=2. RAFT: PDI=1,05. Poli(ε-caprolactona) por ROP: PDI=1,1. GPC/SEC mede"),
                    new("Carbono Ativo — Isoterma de Langmuir", "q = qmax·KL·C/(1+KL·C)", "qmax=capacidade máxima, KL=constante de adsorção, C=concentração em equilíbrio. BET: superfície.", "Langmuir", "1918", "Carvão ativado: qmax=200 mg/g para fenol. KL=0,05 L/mg. BET: 1000 m²/g. ZIF-8 MOF: 1800 m²/g"),
                    new("Síntese Verde — Princípio 1 (Prevenção)", "Custo_resíduo > Custo_prevenção → prevenir é preferível", "12 Princípios da Química Verde. Prevenção > tratamento de resíduos.", "Anastas e Warner", "1998", "Princípios 1–12: prevenção, atom economy, química menos perigosa, produtos mais seguros, solventes/auxiliares mais seguros, eficiência energética, matérias-primas renováveis, derivatização reduzida, catálise, biodegradabilidade, análise em tempo real, química mais segura para prevenção de acidentes"),
                    new("Entalpia de Combustão — Poder Calorífico", "HHV ≈ 33,8×C + 144,4×H + 9,4×S [MJ/kg]", "C, H, S em fração mássica. HHV: todo H₂O condensado. LHV: H₂O como vapor. Base de biocombustíveis.", "Dulong", "1837", "Celulose (C=44%, H=6%): HHV=33,8×0,44+144,4×0,06=14,8+8,7=23,5 MJ/kg. Carvão vegetal: 30 MJ/kg")
                });

            AdicionarPacoteVol12Detalhado(
                "CIÊNCIAS DO SOLO E AGROFÍSICA",
                "Física do Solo e Agrofísica",
                278,
                new List<Vol12FormulaSpec>
                {
                    new("Equação de Richards — Fluxo em Solo Não-Saturado", "∂θ/∂t = ∇[K(h)∇(h+z)]", "θ=teor de umidade, h=potencial matricial, K(h)=condutividade hidráulica não-saturada, z=altitude.", "Richards", "1931", "Solo argiloso: K varia 10⁶× entre saturado e seco. Simulação: HYDRUS-1D. Irrigação sub-superficial: K crítico"),
                    new("Curva de Retenção de Água — van Genuchten", "θ(h) = θr + (θs−θr)/[1+(α|h|)^n]^{1−1/n}", "θr=umidade residual, θs=saturação, α,n=parâmetros de forma. Ajuste a dados pF.", "van Genuchten", "1980", "Areia: θr=0,04, θs=0,43, α=0,15 cm⁻¹, n=2,7. Argila: α=0,005, n=1,3. ROSETTA: estima por granulometria"),
                    new("Condutividade Hidráulica Saturada — Kozeny-Carman", "Ksat = (ρg/μ)·(φ³/(180(1−φ)²))·d²", "φ=porosidade, d=diâmetro equivalente de partícula. Ksat varia 10⁹× entre areia e argila.", "Kozeny; Carman", "1927-1937", "Areia d=0,1 mm, φ=0,45: Ksat=10⁻⁴ m/s. Argila d=2 μm, φ=0,5: Ksat=10⁻⁸ m/s. Permeâmetro de carga constante"),
                    new("Equação Universal de Perda de Solo — RUSLE", "A = R·K·L·S·C·P  [ton/ha/ano]", "R=erosividade chuva, K=erodibilidade solo, LS=topografia, C=cobertura, P=práticas conservacionistas.", "Wischmeier e Smith", "1978", "R=700 MJ·mm/ha/h/ano (SE Brasil). K=0,04. LS=5. C=0,5 (pastagem degradada). P=1: A=70 ton/ha/ano. Grave"),
                    new("Capacidade de Troca Catiônica", "CTC = Σ(Ca²⁺+Mg²⁺+K⁺+Na⁺+H⁺+Al³⁺) [cmolc/dm³]", "CTC mede capacidade de reter cátions nutrientes. Alta CTC=15: solo fértil (ex: Latossolo Vermelho).", "Base de fertilidade do solo (Embrapa)", "1997", "Latossolo vermelho: CTC=12 cmolc/dm³. Areia quartzosa: CTC=3. Calcário: Al³⁺→0, Ca²⁺+Mg²⁺↑. V%=saturação de bases"),
                    new("Necessidade de Calcário — EMBRAPA", "NC = (V₂−V₁)·CTC/(100×PRNT)  [ton/ha]", "V₁=saturação de bases atual, V₂=desejada (70%), PRNT=poder rel. de neutralização total.", "Embrapa/IAC", "1985-1997", "CTC=10, V₁=25%, V₂=70%: NC=45×10/(100×90%)=5,0 ton/ha de calcário PRNT=90%. Plintossolo: V₂=50%"),
                    new("Lei de Liebig — Fator Limitante", "Crescimento limitado pelo nutriente em menor proporção relativa à necessidade", "Produto depende do fator mais escasso. Base de adubação e diagnose foliar.", "Liebig", "1840", "Solo com B deficiente: adicionar NPK não aumenta produção. Diagnose: análise foliar identifica fator limitante"),
                    new("Potencial de Água em Planta", "ψ_total = ψ_osmótico + ψ_matricial + ψ_pressão + ψ_gravitacional", "Água flui de alto para baixo ψ. Ponto de murcha permanente: ψ=−1,5 MPa.", "Slatyer e Taylor", "1960", "Raiz: ψ=−0,5 MPa. Solo seco: ψ=−1,8 MPa→fluxo de planta para solo. Folha ao meio-dia: ψ=−2 MPa (turgor perdido)"),
                    new("Evapotranspiração da Cultura — FAO", "ETc = Kc × ET₀", "Kc=coeficiente de cultura (inicial/médio/final). ET₀ de Penman-Monteith.", "Allen et al.", "1998", "Milho floração: Kc=1,2, ET₀=6 mm/dia: ETc=7,2 mm/dia. Período de projeto: ΣETc=600 mm. Irrigação: necessidade"),
                    new("Teor de Umidade — Método Gravimétrico", "θg = (Mumida−Mseca)/Mseca × 100%", "θg=umidade em base seca. θv=θg·ρs/ρw=umidade volumétrica. TDR mede θv diretamente.", "Base de física do solo", "Séc. XX", "θg=0,15 (15%): solo médio. ρs=1,3 g/cm³: θv=19,5%. Capacidade de campo: θg=25–35% (argila). FCC"),
                    new("Nitrogênio no Solo — Equação de Mineralização", "N_mineral = k·N_orgânico·T^{0,5}", "k=constante de mineralização, T=temperatura normalizada. Incubação: mede N disponível.", "Stanford e Smith", "1972", "k=0,05/semana a 35°C. Solo com N_orgânico=0,1%: 50 kg N/ha/ano mineralizado. Adubação nitrogenada: desconto"),
                    new("Adsorção de Fósforo — Equação de Langmuir", "x/m = KL·Cmax·C/(1+KL·C)", "x/m=P adsorvido [mg/g], Cmax=capacidade máxima, C=P em solução. P: imobilizado em Oxisols.", "Base de química do fósforo em solos tropicais", "Séc. XX", "Latossolo vermelho: Cmax=800 mg/kg, KL=1,5 L/mg. C=0,5 mg/L: x/m=375 mg/kg. Fixação de P: desafio no Cerrado"),
                    new("Matéria Orgânica — Estoques de Carbono", "C_estoque = [MOS%] × ρs × h × 10⁴ [kg/ha]", "MOS%=teor de matéria orgânica, ρs=densidade do solo, h=profundidade (m).", "Base de carbono do solo e mudanças climáticas", "Séc. XXI", "MOS=2%, ρs=1,3 g/cm³, h=0,2 m: C=0,02×1300×0,2×10⁴=52.000 kg/ha=52 ton/ha. Sequestro: +0,4% ao ano"),
                    new("Salinidade — Condutividade Elétrica Limiar", "ECe_limiar: milho=1,7 dS/m, tomate=2,5 dS/m", "Rendimento cai 10% por unidade de ECe acima do limiar. Tolerância: cultura-específica.", "Maas e Hoffman", "1977", "ECe=4 dS/m em milho: rendimento=1,7+(1,7−4)×12%=72%. Fertirrigação: EC_água máx=0,7 dS/m. Lixiviação"),
                    new("Granulometria — Pipette Method", "% argila = (massa_pipetada/massa_total) × (V_total/V_pipeta) × 100", "Stokes: argila<2μm cai 10 cm em t_pipetagem. Frações: argila, silte, areia.", "Day", "1965", "Latossolo: 60% argila, 20% silte, 20% areia. Textura argilosa → maior CTC, menor Ksat. Textura para USDA"),
                    new("Fixação Biológica de N₂ — FBN", "N_fixado = δ¹⁵N_solo − δ¹⁵N_planta × B", "B=fração derivada da fixação, δ¹⁵N mede discriminação isotópica. Leguminosas: até 300 kg N/ha/ano.", "Boddey et al.", "1990", "Soja inoculada com Bradyrhizobium: FBN=200–300 kg N/ha. δ¹⁵N método: distingue N do ar vs solo. PGPR"),
                    new("Temperatura do Solo — Lei de Fourier", "q = −λ × dT/dz", "q=fluxo de calor, λ=condutividade térmica, dT/dz=gradiente de temperatura. Amortecimento com profundidade.", "Fourier", "1822", "Solo seco: λ=0,3 W/m/K. Solo úmido: λ=1,5 W/m/K. Amplitude de T: reduz 1/e a 0,1 m. Geotermômetro"),
                    new("Retenção de Herbicida no Solo", "Kd = Cs/Cw = Koc × foc", "Kd=coef. de distribuição, Koc=coef. normalizado para C orgânico, foc=fração de C orgânico.", "Karickhoff", "1981", "Atrazina: Koc=100 mL/g. Solo foc=0,01: Kd=1 mL/g. R_retardação=1+ρb×Kd/θ=1+1,3/0,3=5,3. Lixiviação risco"),
                    new("Resistência Mecânica do Solo — Penetrômetro", "RP = F/(π×r²)  [MPa]", "RP=resistência à penetração. RP>2 MPa: limita crescimento radicular. Depende de θ e ρs.", "ASAE", "1999", "RP=3 MPa em Latossolo compactado seco. Irrigação pré-plantio: θ↑→RP↓→semeadura. Subsolagem: RP<1,5 MPa"),
                    new("Balanço de Nitrogênio em Bacia", "BN = Entradas − Saídas = (Fertilizante+FBN+deposição) − (colheita+lixiviação+desnitrificação+volatilização)", "BN positivo: acúmulo. Negativo: degradação de solo. Meta: BN~0 para sustentabilidade.", "FAO", "2003", "Agricultura familiar tropical: BN=−30 kg N/ha/ano (exporta mais do que repõe). Exaustão do solo a longo prazo")
                });

            AdicionarPacoteVol12Detalhado(
                "ENGENHARIA NUCLEAR CLÁSSICA E PROTEÇÃO RADIOLÓGICA",
                "Reatores e Proteção Radiológica",
                298,
                new List<Vol12FormulaSpec>
                {
                    new("Equação de Difusão Neutrónica", "D∇²φ − Σa·φ + S = 0", "D=coef. de difusão, φ=fluxo neutrónico, Σa=seção de choque de absorção, S=fonte. Regime estacionário.", "Fermi; Placzek", "1942-1946", "Reator PWR: φ=3×10¹³ n/cm²/s. Σa_U235=0,68 cm⁻¹. D~1 cm. Criticidade: k_eff=1. MCNP, OpenMC"),
                    new("Fator de Multiplicação — k_eff", "k_eff = k_inf × P_NL = η·f·p·ε × P_NL", "η=nêutrons por fissão, f=fator de uso térmico, p=fator de ressonância, ε=fator de fissão rápida, P_NL=fuga.", "Fermi e Szilard; Glasstone e Sesonske", "1940", "k_eff=1: crítico. k_eff>1: supercrítico. η(U235)=2,06. f=0,9, p=0,8, ε=1,05: k_inf=1,55. P_NL=0,65: k_eff=1,01"),
                    new("Tempo de Dobramento do Reator", "DT = 0,693/((k_eff−1)/ℓ*)", "ℓ*=tempo de vida do nêutron geração (~10⁻⁴ s em PWR). Controle: barras de controle mantêm k_eff=1.", "Lamarsh", "1966", "k_eff=1,001: DT=0,693/(0,001/10⁻⁴)=69 s. k_eff=1,01: DT=7 s. Controle por nêutrons retardados (β=0,0065)"),
                    new("Calor de Decaimento após Desligamento", "P(t) = P₀ × 0,066 × t^{-0,2}  [t em s]", "Calor residual de produtos de fissão. Não para imediatamente! Cooling essencial pós-SCRAM.", "Way e Wigner", "1948", "t=100 s: P=0,066P₀×100^{-0,2}=0,042P₀=4,2%. Fukushima: tsunami → falha no cooling → fusão do núcleo"),
                    new("Seção de Choque de Absorção — Lei 1/v", "σa(E) = σ₀(E₀/E)^{1/2} = σ₀·v₀/v", "Nêutrons térmicos: σ inversamente proporcional à velocidade. Referência: v₀=2200 m/s (25,3 meV).", "Base de física de reatores nucleares", "Séc. XX", "Cd: σa(25 meV)=2500 b (barns). B-10: 3840 b. Xe-135: 2,6×10⁶ b → envenenamento de reator!"),
                    new("Equação de Bateman — Cadeia de Decaimento", "dN₂/dt = λ₁N₁ − λ₂N₂", "N₂=filha, N₁=mãe, λ=constante de decaimento=0,693/t½. Solução: N₂=N₁₀λ₁(e^{-λ₁t}−e^{-λ₂t})/(λ₂−λ₁).", "Bateman", "1910", "U238→Th234→Pa234→U234→...→Pb206. Equilíbrio secular: A₁=A₂. Ra em minas de urânio"),
                    new("Blindagem — Atenuação de Gamma", "I = I₀·e^{−μ·x}", "μ=coef. de atenuação linear, x=espessura. μ=μ/ρ×ρ. Build-up factor B para feixes múltiplos.", "Base de proteção radiológica", "Séc. XX", "Co-60 (1,25 MeV): μ/ρ(Pb)=0,068 cm²/g. HVL=ln2/μ. 10 HVL=fator 1024 de atenuação. Blindagem de bunker"),
                    new("Dose Absorvida e Dose Equivalente", "H = D × WR  [Sv]", "D=dose absorvida [Gy=J/kg], WR=fator de ponderação da radiação (γ,β=1; α=20; nêutrons=2–20).", "ICRP Publication 60; ICRP 103", "1990-2007", "Limite para trabalhador: H=20 mSv/ano. Público: 1 mSv/ano. Raio-X dentário: 0,005 mSv. LNT model"),
                    new("Taxa de Dose — Lei do Inverso do Quadrado", "D(r) = D(r₀)·(r₀/r)²", "Para fontes pontuais. Combinada com atenuação para fontes extensas ou em blindagem.", "Base de proteção radiológica operacional", "Séc. XX", "Fonte de Co-60 de 1 TBq: D(1m)=120 mSv/h. D(10m)=1,2 mSv/h. Distância: regra mais eficaz de proteção"),
                    new("Atividade Específica", "A = λ·N = 0,693·NA·m/(t½·M)", "A=atividade [Bq], NA=avogadro, m=massa em gramas, M=massa atômica.", "Base de radiofísica e medicina nuclear", "Séc. XX", "Ra-226 (t½=1600a): A_sp=3,7×10¹⁰ Bq/g=1 Ci/g. Definição histórica do Curie. Tc-99m: A_sp altíssima"),
                    new("Criticalidade — Massa Crítica Esfera Nua", "r_crit = π/√(Σa/D−νΣf/D)", "r_crit: raio de esfera fissível para k_eff=1. M_crit=4/3πr³ρ.", "Base de segurança nuclear e não-proliferação", "Séc. XX", "U-235 90% enriquecido: M_crit≈52 kg. Pu-239: M_crit≈10 kg. Refletor de Be: M_crit/4. Criticidade acidental"),
                    new("Moderação — Comprimento de Difusão", "L² = D/Σa;  τ = Ea/(ξ·Σs)", "L=comprimento de difusão térmico, τ=comprimento de moderação de Fermi (relentização). Atingir térmica.", "Fermi", "1942", "H₂O: L=2,73 cm, τ=27 cm². D₂O: L=100 cm, τ=131 cm². Grafite: L=54 cm. Moderador influencia k_inf"),
                    new("Envenenamento por Xe-135", "dXe/dt = γXe·Σf·φ + λI·I − λXe·Xe − σXe·φ·Xe", "Xe-135: maior absorvedor de nêutrons. Fonte: decaimento de I-135. Peak após SCRAM: 'xenon pit'.", "Base de dinâmica de reatores nucleares", "Séc. XX", "PWR: Xe equilibrium [Xe]=2×10¹⁵ at/cm³. Shutdown: Xe↑ 6h→reactivity −6000 pcm. Restart window limitada"),
                    new("Dose Efetiva — Órgãos", "E = ΣWT×HT", "WT=fator de peso de órgão (gônadas=0,20, medula=0,12...). HT=dose equivalente em órgão T.", "ICRP Publication 60", "1990", "Irradiação corporal total (radiografia tórax): E=0,02 mSv. TC de abdômen: E=10 mSv. Limite anual: 1 mSv (público)"),
                    new("Reação de Fusão Nuclear D-T", "D + T → He-4 (3,5 MeV) + n (14,1 MeV)", "ΔE=17,6 MeV por reação. Critério de Lawson: n·τ_E>2×10²⁰ m⁻³·s para ignição.", "Lawson", "1957", "ITER: n=10²⁰ m⁻³, τ_E=3 s: n·τ=3×10²⁰. Q=10 (10× mais energia do que entra). Tokamak: campo toroidal"),
                    new("Transmutação — Equação de Dose por Ativação", "D_ativação = C·φ·σ·T_irrad·D_específico", "Ativação de materiais estruturais: vida longa de residuos. Base de cálculo de resíduos nucleares.", "Base de ativação neutrónica e resíduos", "Séc. XX", "Aço inox em reator: Co-60 ativado de Co-59. Residuo de nível intermediário. Descontaminação: 10 t½"),
                    new("Dose de Radiação Ionizante — Grandeza Kerma", "K = Φ·E·(μtr/ρ)", "Φ=fluência de fótons, E=energia do fóton, μtr/ρ=coef. de transferência de energia mássico. Em ar.", "ICRU Report 85", "2011", "Co-60 no ar: μtr/ρ=0,0295 cm²/g. Φ=10⁹ fótons/cm²: K=10⁹×1,25×10⁶×1,6×10⁻¹³×0,0295=7×10⁻³ Gy"),
                    new("Rendimento Quântico de Radiólise", "G-value = espécies por 100 eV depositados", "G(H·)=0,55, G(·OH)=2,7, G(e⁻aq)=2,7 em água. Base de proteção de combustível nuclear.", "Base de radioquímica e química de radiação", "Séc. XX", "Radiólise de água: ·OH danifica DNA a doses clinicas. G(·OH)=2,7×10⁻¹⁶ mol/J. Radioterápica: 2 Gy por fração"),
                    new("Crescimento de Fissão — Equação de In-Core Fuel Performance", "dF/dt ≈ σf·φ·N_U235", "F=burnup acumulado [MWd/tU]. Burnup máximo: 60.000 MWd/tU (UO₂ commercial). Limite de segurança.", "Base de gerência de combustível nuclear", "Séc. XX", "PWR: φ=3×10¹³ n/cm²/s. 18 meses de ciclo: burnup=45.000 MWd/tU. Enriquecimento 4%: suficiente para ciclo 18 meses"),
                    new("Coeficiente de Temperatura Moderador", "α_T = (1/k)·(∂k/∂T)_mod  [pcm/°C]", "Negativo em PWR: aumento de T → redução de k (estabilidade). Base de segurança intrínseca.", "Base de segurança de reatores nucleares", "Séc. XX", "PWR: α_T_mod=−20 pcm/°C. T↑100°C→k↓2000 pcm=−2% Δk. Reação auto-limitante. Intrinsically safe")
                });

            AdicionarPacoteVol12Detalhado(
                "ASTRONOMIA E ASTROFÍSICA DE SISTEMAS PLANETÁRIOS",
                "Sistemas Planetários e Exoplanetas",
                318,
                new List<Vol12FormulaSpec>
                {
                    new("Leis de Kepler — Período Orbital", "T² = (4π²/GM)·a³", "T=período orbital, a=semi-eixo maior, M=massa da estrela. 3ª lei de Kepler (generalizada).", "Kepler; Newton", "1619-1687", "Terra: a=1 UA, M=M⊙: T=1 ano. Marte: a=1,52 UA: T=1,52^{1,5}=1,87 anos. Exoplaneta a=0,05 UA: T=4 dias"),
                    new("Velocidade Orbital Circular", "v = √(GM/r)", "v=velocidade circular, G=constante gravitacional, M=massa central, r=distância. Satélites e planetas.", "Newton", "1687", "LEO (r=6700 km): v=√(6,67e-11×6e24/6,7e6)=7,7 km/s. Geoestacionária r=42300 km: v=3,07 km/s"),
                    new("Equação de Vis-Viva — Energia Orbital", "v² = GM(2/r − 1/a)", "Velocidade em qualquer ponto da órbita elíptica. a=semi-eixo maior. Periélio: v máximo.", "Newton", "1687", "Cometa Halley: a=17,8 UA, M=M⊙. No periélio (r=0,586 UA): v=√(GM(2/0,586−1/17,8)/UA)=54 km/s"),
                    new("Velocidade de Escape", "vesc = √(2GM/R)", "R=raio da superfície. vesc>c: buraco negro (Schwarzschild). Base de atmosferas e lançamentos espaciais.", "Newton", "Séc. XVII", "Terra: vesc=11,2 km/s. Lua: 2,4 km/s. Sol: 617 km/s. Raio de Schwarzschild: R_S=2GM/c²"),
                    new("Equilíbrio de Temperatura de Planeta", "Teq = T★×√(R★/(2a))×(1−A)^{1/4}", "T★=temperatura da estrela, R★=raio, a=distância, A=albedo. Equilíbrio radiativo.", "Base de climatologia planetária e exoplanetas", "Séc. XX", "Terra: T★=5778 K, R★=R⊙, a=1 UA, A=0,30: Teq=255 K. Efeito estufa: T_superfície=288 K. Habitable zone"),
                    new("Massa de Exoplaneta — Velocidade Radial", "m_p sinI = K·M★^{2/3}·(P/2π G)^{1/3}·(1−e²)^{1/2}", "K=amplitude da velocidade radial [m/s]. Massa mínima (sin I desconhecido). Método Doppler.", "Mayor e Queloz", "1995", "51 Peg b: K=56 m/s, P=4,23 dias, M★=M⊙: m_p sinI=0,47 MJ. Júpiter quente. HARPS: K<1 m/s"),
                    new("Trânsito de Exoplaneta — Profundidade", "δ = (Rp/R★)²", "δ=fração de queda de fluxo. Rp=raio do planeta. Duração do trânsito e inclinação: geometria orbital.", "Charbonneau et al.; missão Kepler", "2000", "Terra/Sol: δ=0,0001% (difícil). Júpiter/Sol: δ=1%. Kepler: δ_limiar=20 ppm. TESS: magnitude limite V<12"),
                    new("Habitabilidade — Zona Habitável", "aHz_inner = R★/R⊙·√(L★/L⊙)/√Seff_inner", "S_eff=flux de irradiação normalizado. Vénus: limite interno. Marte: externo. Função de T★.", "Kasting, Whitmire e Reynolds", "1993", "Sol: HZ=0,95–1,67 UA. Estrela M (0,5M⊙): HZ=0,2–0,4 UA. Proxima Cen b: 0,05 UA→dentro da HZ?"),
                    new("Balanço de Carbono Atmosférico — Ciclo de Walker", "dCO₂/dt = F_volcanic − F_silicate_weathering", "Estabilidade de longo prazo: retroalimentação negativa. T↑→intemperismo↑→CO₂↓→resfriamento.", "Walker, Hays e Kasting", "1981", "Ciclo de 100 Myr. Snowball Earth: CO₂ acumula→deglaciação. TRAPPIST-1: ciclo de carbono?"),
                    new("Espessura de Atmosfera — Escala de Altura", "H = kBT/(μg)", "μ=massa molecular média, g=gravidade. P(z)=P₀exp(−z/H). Base de estrutura atmosférica.", "Base de física de atmosferas planetárias", "Séc. XX", "Terra: T=250 K, μ=0,029 kg/mol, g=9,8: H=8,5 km. Marte: H=11 km (g menor, T baixa). Vénus: H=15 km"),
                    new("Velocidade de Escape Atmosférica — Jean's Escape", "ṁ ∝ n(Rexobase)·v̄·e^{−(vesc/vth)²}", "vth=velocidade térmica. H e He escapam; N₂, O₂: retidos. Base de evolução atmosférica.", "Jeans", "1904", "Marte: H₂ escapa (~4 km/s vs vesc=5 km/s). Perda de água primordial. Ganimedes: perde H lentamente"),
                    new("Emissão de Corpo Negro — Lei de Stefan-Boltzmann", "L = 4πR²·σT⁴  [Watts]", "σ=5,67×10⁻⁸ W/m²/K⁴. Total de toda radiação emitida por corpo negro de temperatura T.", "Stefan; Boltzmann", "1879-1884", "Sol: R=7×10⁸ m, T=5778 K: L=3,83×10²⁶ W=1 L⊙. Diretamente observável para estrelas. HR diagram: L vs T"),
                    new("Magnitude Aparente e Absoluta", "m−M = 5log(d/10 pc) = 5log d − 5", "M=magnitude absoluta, m=aparente, d=distância em parsecs. Módulo de distância.", "Pogson", "1856", "Sol: M=4,83, m(a 10pc)=4,83. Estrela a 100 pc: m−M=5. Cefeidas: M por período → d. Régua cósmica"),
                    new("Momento de Inércia Estelar — Estrutura Interna", "I = ∫r² dm = k·MR²", "k=0,4 para esfera uniforme. k<0,4 para estrela concentrada. Rotação diferencial → k medido por sismologia.", "Base de estrutura estelar interna", "Séc. XX", "Sol: k≈0,07 (núcleo denso). Rotação: I·Ω=const → Ω↑↑ quando collapsa. Pulsar: I≈10³⁸ kg·m²"),
                    new("Precessão dos Equinócios — Torque Gravitacional", "ψ̇ = −(3/2)·(GM/r³)·cos ε / Ω  [rad/s]", "ψ̇=taxa de precessão, ε=obliquidade (23,5°), Ω=spin angular. Período de Platão=26.000 anos.", "Newton", "1687", "Terra: ψ̇=50,3''/ano → período=25.772 anos (ciclo de Milankovitch). Polo norte aponta para Vega em ~12.000 anos"),
                    new("Marés — Força de Maré Lunar", "F_maré = 2GMm·r/R³", "M=massa da Lua, m=massa do objeto, r=tamanho do objeto, R=distância. Gradiente de gravidade.", "Newton", "1687", "Amplitude da maré: ~0,5 m em oceano aberto. Praia de Fundy: 16 m (ressonância). Io (Júpiter): F_maré→calor→vulcões"),
                    new("Número de Planetas por Estrela — Equação de Drake (versão planetária)", "f_planetas ≈ 1  (quase toda estrela tem planetas)", "Kepler: 90% das estrelas têm pelo menos 1 planeta. Zona habitável: 20–40% das estrelas-K e M.", "Drake; dados de Kepler/TESS", "1961", "f_terra-análogos≈0,1. 10¹¹ estrelas na Galáxia: ~10¹⁰ planetas tipo-Terra. Probabilidade de vida: desconhecida"),
                    new("Aceleração de Maré — Critério de Roche", "R_Roche = 2,44×R_planeta×(ρ_planeta/ρ_satélite)^{1/3}", "Anéis de Saturno: dentro de R_Roche. Satélites: devem estar além. Limite de instabilidade tidal.", "Roche", "1848", "Saturno: R_Roche=146.000 km. Anéis: 70.000–140.000 km. Lua: 384.000 km >> R_Roche. Tidal disruption events"),
                    new("Efeito Doppler em Astronomia", "Δλ/λ = v_r/c  (não-relativístico)", "v_r=velocidade radial de afastamento. Redshift: Δλ>0. Blueshirt: Δλ<0. Base de espectroscopia estelar.", "Doppler", "1842", "Hα=656,28 nm. Δλ=0,01 nm: v_r=4,6 km/s. Hubble: cz=H₀d. Velocidade radial estelar medida com precisão de 1 m/s"),
                    new("Limite de Eddington", "L_Edd = 4πGMc/κ_es", "κ_es=opacidade por dispersão Thomson. L>L_Edd: pressão de radiação > gravidade → perda de massa.", "Eddington", "1916", "Sol: L_Edd=3,2×10⁴L⊙ >> L_Sol=1L⊙. AGN: L próxima a L_Edd. Estrelas massivas: perdem massa em ventos")
                });
        }
    }
}