using CompendioCalc.Models;

namespace CompendioCalc.Services;

public partial class FormulaService
{
    // ═══════════════════════════════════════════════════════════════
    //  VOLUME 2 — PARTE V: BIOLOGIA QUANTITATIVA
    // ═══════════════════════════════════════════════════════════════

    // ─────────────────────────────────────────────────────
    // 21. EPIDEMIOLOGIA E DINÂMICA DE POPULAÇÕES
    // ─────────────────────────────────────────────────────
    private void AdicionarEpidemiologia()
    {
        _formulas.AddRange([
            // 21.1 Dinâmica de Populações
            new Formula { Id = "ep_lv01", Nome = "Crescimento Exponencial", Categoria = "Epidemiologia", SubCategoria = "Dinâmica de Populações",
                Expressao = "dN/dt = rN → N(t) = N₀ e^{rt}", ExprTexto = "N(t) = N₀ · e^(rt) (crescimento exponencial)", Icone = "🦠",
                Descricao = "Modelo de Malthus: crescimento sem limitação. r>0: crescimento exponencial. r<0: declínio. Tempo de duplicação = ln2/r.",
                Criador = "Thomas Malthus", AnoOrigin = "1798",
                Variaveis = [
                    new() { Simbolo = "N0", Nome = "N₀ (população inicial)", ValorPadrao = 100 },
                    new() { Simbolo = "r", Nome = "r (taxa de crescimento)", ValorPadrao = 0.05 },
                    new() { Simbolo = "t", Nome = "t (tempo)", ValorPadrao = 10 },
                ],
                VariavelResultado = "N(t)",
                Calcular = vars => vars["N0"]*Math.Exp(vars["r"]*vars["t"]) },
            new Formula { Id = "ep_lv02", Nome = "Crescimento Logístico", Categoria = "Epidemiologia", SubCategoria = "Dinâmica de Populações",
                Expressao = "dN/dt = rN(1-N/K)", ExprTexto = "N(t) = K / (1 + ((K−N₀)/N₀)·e^(−rt))", Icone = "🦠",
                Descricao = "Modelo logístico (Verhulst): crescimento limitado pela capacidade de suporte K. Curva sigmoidal. Ponto de inflexão em K/2.",
                Criador = "Pierre-François Verhulst", AnoOrigin = "1838",
                Variaveis = [
                    new() { Simbolo = "N0", Nome = "N₀ (pop. inicial)", ValorPadrao = 10 },
                    new() { Simbolo = "K", Nome = "K (capacidade de suporte)", ValorPadrao = 1000 },
                    new() { Simbolo = "r", Nome = "r (taxa de crescimento)", ValorPadrao = 0.1 },
                    new() { Simbolo = "t", Nome = "t (tempo)", ValorPadrao = 50 },
                ],
                VariavelResultado = "N(t)",
                Calcular = vars => vars["K"]/(1+((vars["K"]-vars["N0"])/vars["N0"])*Math.Exp(-vars["r"]*vars["t"])) },
            new Formula { Id = "ep_lv03", Nome = "Lotka-Volterra (Predador-Presa)", Categoria = "Epidemiologia", SubCategoria = "Dinâmica de Populações",
                Expressao = "dx/dt=αx-βxy; dy/dt=δxy-γy", ExprTexto = "ẋ = αx−βxy (presa); ẏ = δxy−γy (predador)", Icone = "🦠",
                Descricao = "Lotka-Volterra: oscilações predador-presa. α=crescimento presa, β=predação, δ=conversão, γ=mortalidade predador.",
                Criador = "Lotka / Volterra", AnoOrigin = "1925/1926",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "αx", Nome = "αx", ValorPadrao = 10 }, new() { Simbolo = "βxy", Nome = "βxy", ValorPadrao = 5 } ],
                VariavelResultado = "ẋ",
                UnidadeResultado = "",
                Calcular = vars => vars["αx"] - vars["βxy"]
            },
            new Formula { Id = "ep_lv04", Nome = "Competição de Lotka-Volterra", Categoria = "Epidemiologia", SubCategoria = "Dinâmica de Populações",
                Expressao = "dN₁/dt = r₁N₁(1-(N₁+α₁₂N₂)/K₁)", ExprTexto = "dNᵢ/dt = rᵢNᵢ(1−(Nᵢ+αᵢⱼNⱼ)/Kᵢ)", Icone = "🦠",
                Descricao = "Competição interespecífica: duas espécies competindo por recursos. αᵢⱼ=efeito de espécie j sobre i. Coexistência se α₁₂α₂₁<1.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "N", Nome = "N (população)", ValorPadrao = 100, ValorMin = 1 }, new() { Simbolo = "r", Nome = "r (taxa)", ValorPadrao = 0.1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => vars["N"] * vars["r"]
            },
            new Formula { Id = "ep_lv05", Nome = "Equação de Fisher-KPP", Categoria = "Epidemiologia", SubCategoria = "Dinâmica de Populações",
                Expressao = "∂u/∂t = D∂²u/∂x² + ru(1-u)", ExprTexto = "uₜ = D·uₓₓ + ru(1−u) (difusão + logístico)", Icone = "🦠",
                Descricao = "Fisher-KPP: dispersão espacial com crescimento logístico. Ondas viajantes com velocidade c=2√(Dr). Invasões biológicas.",
                Criador = "Ronald Fisher / Kolmogorov", AnoOrigin = "1937",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "D", Nome = "D", ValorPadrao = 5 }, new() { Simbolo = "uₓₓ", Nome = "uₓₓ", ValorPadrao = 3 } ],
                VariavelResultado = "uₜ",
                UnidadeResultado = "",
                Calcular = vars => vars["D"] * vars["uₓₓ"]
            },
            new Formula { Id = "ep_lv06", Nome = "Matriz de Leslie (Pop. Estruturada)", Categoria = "Epidemiologia", SubCategoria = "Dinâmica de Populações",
                Expressao = "nₜ₊₁ = L·nₜ (L: fecundidade e sobrevivência)", ExprTexto = "nₜ₊₁ = L nₜ; taxa de crescimento → autovalor dominante de L", Icone = "🦠",
                Descricao = "Modelo de Leslie: população estruturada por idade. 1ª linha = fecundidades, sub-diagonal = sobrevivências. λ₁ = taxa de crescimento assintótica.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "N", Nome = "N (população)", ValorPadrao = 100, ValorMin = 1 }, new() { Simbolo = "r", Nome = "r (taxa)", ValorPadrao = 0.1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => vars["N"] * vars["r"]
            },
            new Formula { Id = "ep_lv07", Nome = "Mapa Logístico (Caos)", Categoria = "Epidemiologia", SubCategoria = "Dinâmica de Populações",
                Expressao = "xₙ₊₁ = rxₙ(1-xₙ)", ExprTexto = "xₙ₊₁ = r · xₙ · (1−xₙ) com r ∈ [0,4]", Icone = "🦠",
                Descricao = "Mapa logístico discreto: r<3 equilíbrio estável, r≈3.45 bifurcações, r≈3.57 caos. Protótipo de sistemas caóticos.",
                Criador = "Robert May", AnoOrigin = "1976",
                Variaveis = [
                    new() { Simbolo = "xn", Nome = "xₙ (pop. normalizada)", ValorPadrao = 0.5, ValorMin = 0, ValorMax = 1 },
                    new() { Simbolo = "r", Nome = "r (parâmetro)", ValorPadrao = 3.8, ValorMin = 0, ValorMax = 4 },
                ],
                VariavelResultado = "xₙ₊₁",
                Calcular = vars => vars["r"]*vars["xn"]*(1-vars["xn"]) },
            new Formula { Id = "ep_lv08", Nome = "Expoente de Lyapunov", Categoria = "Epidemiologia", SubCategoria = "Dinâmica de Populações",
                Expressao = "λ = lim (1/n) Σ ln|f'(xᵢ)|", ExprTexto = "λ = lim_{n→∞} (1/n) Σᵢ ln|f'(xᵢ)|", Icone = "🦠",
                Descricao = "Expoente de Lyapunov: mede taxa de divergência de trajetórias vizinhas. λ>0 → caos (sensibilidade a condições iniciais).",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "N", Nome = "N (população)", ValorPadrao = 100, ValorMin = 1 }, new() { Simbolo = "r", Nome = "r (taxa)", ValorPadrao = 0.1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => vars["N"] * vars["r"]
            },

            // 21.2 Modelos Epidemiológicos
            new Formula { Id = "ep_sir01", Nome = "Modelo SIR", Categoria = "Epidemiologia", SubCategoria = "Modelos Epidemiológicos",
                Expressao = "dS/dt=-βSI; dI/dt=βSI-γI; dR/dt=γI", ExprTexto = "Ṡ=−βSI; İ=βSI−γI; Ṙ=γI", Icone = "🦠",
                Descricao = "Modelo SIR de Kermack-McKendrick: Suscetível→Infectado→Recuperado. β=taxa de transmissão, γ=taxa de recuperação.",
                Criador = "Kermack / McKendrick", AnoOrigin = "1927",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "βSI", Nome = "βSI", ValorPadrao = 10 }, new() { Simbolo = "γI", Nome = "γI", ValorPadrao = 5 } ],
                VariavelResultado = "İ",
                UnidadeResultado = "",
                Calcular = vars => vars["βSI"] - vars["γI"]
            },
            new Formula { Id = "ep_sir02", Nome = "R₀ (Número Básico de Reprodução)", Categoria = "Epidemiologia", SubCategoria = "Modelos Epidemiológicos",
                Expressao = "R₀ = β/γ", ExprTexto = "R₀ = β/γ (SIR: R₀ = βN/γ)", Icone = "🦠",
                Descricao = "R₀: número médio de infecções secundárias a partir de 1 infectado em população totalmente suscetível. R₀>1: epidemia cresce.",
                Variaveis = [
                    new() { Simbolo = "beta", Nome = "β (taxa de transmissão)", ValorPadrao = 0.3 },
                    new() { Simbolo = "gamma", Nome = "γ (taxa de recuperação)", ValorPadrao = 0.1 },
                ],
                VariavelResultado = "R₀",
                Calcular = vars => vars["beta"]/vars["gamma"] },
            new Formula { Id = "ep_sir03", Nome = "Limiar de Imunidade de Rebanho", Categoria = "Epidemiologia", SubCategoria = "Modelos Epidemiológicos",
                Expressao = "pₕ = 1 - 1/R₀", ExprTexto = "p_c = 1 − 1/R₀ (fração que precisa ser imune)", Icone = "🦠",
                Descricao = "Imunidade de rebanho: proporção mínima de imunes para impedir epidemia. Ex: R₀=3 → 67% precisa ser imune.",
                Variaveis = [ new() { Simbolo = "R0", Nome = "R₀", ValorPadrao = 3, ValorMin = 1 } ],
                VariavelResultado = "p_c (limiar)",
                Calcular = vars => 1 - 1/vars["R0"] },
            new Formula { Id = "ep_sir04", Nome = "Modelo SEIR", Categoria = "Epidemiologia", SubCategoria = "Modelos Epidemiológicos",
                Expressao = "S→E→I→R (E: exposto/latente)", ExprTexto = "Ṡ=−βSI; Ė=βSI−σE; İ=σE−γI; Ṙ=γI", Icone = "🦠",
                Descricao = "SEIR: adiciona compartimento Exposto (período de incubação). σ=1/(período latente). Mais realista para COVID, gripe, etc.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "βSI", Nome = "βSI", ValorPadrao = 10 }, new() { Simbolo = "σE", Nome = "σE", ValorPadrao = 5 } ],
                VariavelResultado = "Ė",
                UnidadeResultado = "",
                Calcular = vars => vars["βSI"] - vars["σE"]
            },
            new Formula { Id = "ep_sir05", Nome = "Modelo SIS (Sem Imunidade)", Categoria = "Epidemiologia", SubCategoria = "Modelos Epidemiológicos",
                Expressao = "dI/dt = βSI - γI (S=N-I)", ExprTexto = "SIS: infectados voltam a ser suscetíveis (sem imunidade duradoura)", Icone = "🦠",
                Descricao = "Modelo SIS: sem imunidade permanente. Equilíbrio endêmico I*=N(1−1/R₀) se R₀>1. Ex: gonorreia, resfriado comum.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "N", Nome = "N (população)", ValorPadrao = 100, ValorMin = 1 }, new() { Simbolo = "r", Nome = "r (taxa)", ValorPadrao = 0.1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => vars["N"] * vars["r"]
            },
            new Formula { Id = "ep_sir06", Nome = "Taxa de Ataque Final (SIR)", Categoria = "Epidemiologia", SubCategoria = "Modelos Epidemiológicos",
                Expressao = "R∞ = 1 + ln(S∞/S₀)/R₀", ExprTexto = "S∞/S₀ = e^{−R₀·(1−S∞/N)} (eq. transcendental)", Icone = "🦠",
                Descricao = "Tamanho final da epidemia: fração total que será infectada. Não é 100% mesmo com R₀ alto (a epidemia se auto-limita).",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "e", Nome = "e", ValorPadrao = 5 } ],
                VariavelResultado = "S₀",
                UnidadeResultado = "",
                Calcular = vars => vars["e"] * vars["e"]
            },
            new Formula { Id = "ep_sir07", Nome = "Rₜ (Número Efetivo de Reprodução)", Categoria = "Epidemiologia", SubCategoria = "Modelos Epidemiológicos",
                Expressao = "Rₜ = R₀ · S(t)/N", ExprTexto = "Rₜ = R₀ · S(t)/N (diminui conforme S diminui)", Icone = "🦠",
                Descricao = "Rₜ: número efetivo de reprodução no tempo t. Leva em conta imunidade adquirida e intervenções. Rₜ<1: epidemia em declínio.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "R₀", Nome = "R₀", ValorPadrao = 5 }, new() { Simbolo = "S", Nome = "S", ValorPadrao = 3 } ],
                VariavelResultado = "Rₜ",
                UnidadeResultado = "",
                Calcular = vars => vars["R₀"] * vars["S"]
            },
            new Formula { Id = "ep_sir08", Nome = "Geração Serial e Tempo de Duplicação", Categoria = "Epidemiologia", SubCategoria = "Modelos Epidemiológicos",
                Expressao = "Td = ln2/r; r ≈ (R₀-1)/Tg", ExprTexto = "Td = ln(2)/r; r ≈ (R₀−1)/T_geração", Icone = "🦠",
                Descricao = "Tempo de duplicação: Td = ln2/r (taxa de crescimento exponencial r). Intervalo serial Tg: tempo médio entre gerações de infecção.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Valor x", ValorPadrao = 10, ValorMin = 0.001 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => Math.Log(vars["x"])
            },
            new Formula { Id = "ep_sir09", Nome = "Modelo em Rede (Network Epidemic)", Categoria = "Epidemiologia", SubCategoria = "Modelos Epidemiológicos",
                Expressao = "R₀ˢ = β⟨k²⟩/(γ⟨k⟩) (rede scale-free)", ExprTexto = "R₀ em rede: depende da distribuição de grau ⟨k²⟩/⟨k⟩", Icone = "🦠",
                Descricao = "Epidemia em redes: R₀ depende da heterogeneidade de contatos. Redes scale-free: limiar pode ser zero (hubs facilitam espalhamento).",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "N", Nome = "N (população)", ValorPadrao = 100, ValorMin = 1 }, new() { Simbolo = "r", Nome = "r (taxa)", ValorPadrao = 0.1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => vars["N"] * vars["r"]
            },
            new Formula { Id = "ep_sir10", Nome = "Matriz de Próxima Geração", Categoria = "Epidemiologia", SubCategoria = "Modelos Epidemiológicos",
                Expressao = "K = FV⁻¹; R₀ = ρ(K) (raio espectral)", ExprTexto = "R₀ = ρ(FV⁻¹) (autovalor dominante da NGM)", Icone = "🦠",
                Descricao = "Método da próxima geração (Diekmann/van den Driessche): R₀ = raio espectral da matriz FV⁻¹. F=novas infecções, V=transições.",
                Criador = "Diekmann / van den Driessche", AnoOrigin = "1990/2002",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "N", Nome = "N (população)", ValorPadrao = 100, ValorMin = 1 }, new() { Simbolo = "r", Nome = "r (taxa)", ValorPadrao = 0.1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => vars["N"] * vars["r"]
            },
        ]);
    }

    // ─────────────────────────────────────────────────────
    // 22. FARMACOCINÉTICA
    // ─────────────────────────────────────────────────────
    private void AdicionarFarmacocinetica()
    {
        _formulas.AddRange([
            // 22.1 Modelos Compartimentais
            new Formula { Id = "fk_01", Nome = "Cinética de 1ª Ordem (Eliminação)", Categoria = "Farmacocinética", SubCategoria = "Modelos Compartimentais",
                Expressao = "C(t) = C₀ e^{-kₑt}", ExprTexto = "C(t) = C₀ · e^(−kₑ·t) (eliminação exponencial)", Icone = "💊",
                Descricao = "Eliminação de 1ª ordem: taxa proporcional à concentração. kₑ=constante de eliminação. Mais comum em farmacocinética.",
                Variaveis = [
                    new() { Simbolo = "C0", Nome = "C₀ (conc. inicial, mg/L)", ValorPadrao = 100 },
                    new() { Simbolo = "ke", Nome = "kₑ (constante elim., 1/h)", ValorPadrao = 0.2 },
                    new() { Simbolo = "t", Nome = "t (tempo, h)", ValorPadrao = 4 },
                ],
                VariavelResultado = "C(t) (mg/L)",
                Calcular = vars => vars["C0"]*Math.Exp(-vars["ke"]*vars["t"]) },
            new Formula { Id = "fk_02", Nome = "Meia-Vida (t₁/₂)", Categoria = "Farmacocinética", SubCategoria = "Modelos Compartimentais",
                Expressao = "t₁/₂ = ln2/kₑ = 0.693/kₑ", ExprTexto = "t½ = ln(2)/kₑ ≈ 0.693/kₑ", Icone = "💊",
                Descricao = "Meia-vida de eliminação: tempo para concentração cair à metade. 5 meias-vidas ≈ 97% eliminado (regime permanente).",
                Variaveis = [ new() { Simbolo = "ke", Nome = "kₑ (1/h)", ValorPadrao = 0.2 } ],
                VariavelResultado = "t₁/₂ (h)",
                Calcular = vars => Math.Log(2)/vars["ke"] },
            new Formula { Id = "fk_03", Nome = "Volume de Distribuição (Vd)", Categoria = "Farmacocinética", SubCategoria = "Modelos Compartimentais",
                Expressao = "Vd = Dose / C₀", ExprTexto = "Vd = Dose / C₀ (volume aparente)", Icone = "💊",
                Descricao = "Vd: volume hipotético para distribuição uniforme da droga. Vd alto → droga se distribui amplamente nos tecidos.",
                Variaveis = [
                    new() { Simbolo = "dose", Nome = "Dose (mg)", ValorPadrao = 500 },
                    new() { Simbolo = "C0", Nome = "C₀ (mg/L)", ValorPadrao = 10 },
                ],
                VariavelResultado = "Vd (L)",
                Calcular = vars => vars["dose"]/vars["C0"] },
            new Formula { Id = "fk_04", Nome = "Clearance (CL)", Categoria = "Farmacocinética", SubCategoria = "Modelos Compartimentais",
                Expressao = "CL = kₑ · Vd = Dose/AUC", ExprTexto = "CL = kₑ · Vd = F·Dose / AUC", Icone = "💊",
                Descricao = "Clearance: volume de sangue completamente depurado por unidade de tempo. CL = CL_renal + CL_hepático + ...",
                Variaveis = [
                    new() { Simbolo = "ke", Nome = "kₑ (1/h)", ValorPadrao = 0.2 },
                    new() { Simbolo = "Vd", Nome = "Vd (L)", ValorPadrao = 50 },
                ],
                VariavelResultado = "CL (L/h)",
                Calcular = vars => vars["ke"]*vars["Vd"] },
            new Formula { Id = "fk_05", Nome = "AUC (Área Sob a Curva)", Categoria = "Farmacocinética", SubCategoria = "Modelos Compartimentais",
                Expressao = "AUC = ∫₀^∞ C(t)dt = C₀/kₑ (IV bolus)", ExprTexto = "AUC₀₋∞ = C₀/kₑ (IV bolus 1 comp.)", Icone = "💊",
                Descricao = "AUC: exposição total ao fármaco. Proporcional à dose absorvida. AUC = Dose·F/CL (F=biodisponibilidade).",
                Variaveis = [
                    new() { Simbolo = "C0", Nome = "C₀ (mg/L)", ValorPadrao = 10 },
                    new() { Simbolo = "ke", Nome = "kₑ (1/h)", ValorPadrao = 0.2 },
                ],
                VariavelResultado = "AUC (mg·h/L)",
                Calcular = vars => vars["C0"]/vars["ke"] },
            new Formula { Id = "fk_06", Nome = "Biodisponibilidade F", Categoria = "Farmacocinética", SubCategoria = "Modelos Compartimentais",
                Expressao = "F = AUC_oral / AUC_IV", ExprTexto = "F = AUC_oral / AUC_IV (0 ≤ F ≤ 1)", Icone = "💊",
                Descricao = "Biodisponibilidade: fração da dose oral que atinge circulação sistêmica. F=1 para IV. Efeito de primeira passagem reduz F.",
                Variaveis = [
                    new() { Simbolo = "AUCoral", Nome = "AUC oral (mg·h/L)", ValorPadrao = 50 },
                    new() { Simbolo = "AUCiv", Nome = "AUC IV (mg·h/L)", ValorPadrao = 80 },
                ],
                VariavelResultado = "F (biodisponibilidade)",
                Calcular = vars => vars["AUCoral"]/vars["AUCiv"] },
            new Formula { Id = "fk_07", Nome = "Estado Estacionário (Css) em Dose Repetida", Categoria = "Farmacocinética", SubCategoria = "Modelos Compartimentais",
                Expressao = "Css_avg = F·Dose/(CL·τ)", ExprTexto = "Css_avg = F·D / (CL·τ) (τ = intervalo posológico)", Icone = "💊",
                Descricao = "Concentração média no estado estacionário: atingido em ~5 meias-vidas. Css ∝ dose/intervalo.",
                Variaveis = [
                    new() { Simbolo = "F", Nome = "F (biodisponibilidade)", ValorPadrao = 0.8, ValorMin = 0, ValorMax = 1 },
                    new() { Simbolo = "D", Nome = "Dose (mg)", ValorPadrao = 500 },
                    new() { Simbolo = "CL", Nome = "CL (L/h)", ValorPadrao = 10 },
                    new() { Simbolo = "tau", Nome = "τ (intervalo, h)", ValorPadrao = 8 },
                ],
                VariavelResultado = "Css_avg (mg/L)",
                Calcular = vars => vars["F"]*vars["D"]/(vars["CL"]*vars["tau"]) },
            new Formula { Id = "fk_08", Nome = "Dose de Carga", Categoria = "Farmacocinética", SubCategoria = "Modelos Compartimentais",
                Expressao = "DL = Css_desejada · Vd / F", ExprTexto = "D_carga = Css · Vd / F", Icone = "💊",
                Descricao = "Dose de carga: atinge Css imediatamente sem esperar 5 meias-vidas. Seguida por doses de manutenção.",
                Variaveis = [
                    new() { Simbolo = "Css", Nome = "Css desejada (mg/L)", ValorPadrao = 10 },
                    new() { Simbolo = "Vd", Nome = "Vd (L)", ValorPadrao = 50 },
                    new() { Simbolo = "F", Nome = "F (biodisponibilidade)", ValorPadrao = 1, ValorMin = 0, ValorMax = 1 },
                ],
                VariavelResultado = "Dose de carga (mg)",
                Calcular = vars => vars["Css"]*vars["Vd"]/vars["F"] },
            new Formula { Id = "fk_09", Nome = "Cinética de Michaelis-Menten (Saturação)", Categoria = "Farmacocinética", SubCategoria = "Modelos Compartimentais",
                Expressao = "dC/dt = -Vmax·C/(Km+C)", ExprTexto = "−dC/dt = Vmax·C / (Km + C)", Icone = "💊",
                Descricao = "Cinética de saturação (0ᵃ ordem em altas conc.): taxa máxima Vmax quando C>>Km. Ex: etanol, fenitoína.",
                Variaveis = [
                    new() { Simbolo = "Vmax", Nome = "Vmax (mg/L/h)", ValorPadrao = 20 },
                    new() { Simbolo = "C", Nome = "C (mg/L)", ValorPadrao = 10 },
                    new() { Simbolo = "Km", Nome = "Km (mg/L)", ValorPadrao = 5 },
                ],
                VariavelResultado = "Taxa de eliminação (mg/L/h)",
                Calcular = vars => vars["Vmax"]*vars["C"]/(vars["Km"]+vars["C"]) },

            // 22.2 Farmacodinâmica
            new Formula { Id = "fk_fd01", Nome = "Modelo Emax (Farmacodinâmica)", Categoria = "Farmacocinética", SubCategoria = "Farmacodinâmica",
                Expressao = "E = Emax · C^n / (EC₅₀^n + C^n)", ExprTexto = "E = Emax · Cⁿ / (EC₅₀ⁿ + Cⁿ) (Hill)", Icone = "💊",
                Descricao = "Modelo Emax sigmoidal (Hill): relaciona concentração com efeito. EC₅₀=conc. para 50% efeito máximo. n=coeficiente Hill.",
                Variaveis = [
                    new() { Simbolo = "Emax", Nome = "Emax (efeito máximo)", ValorPadrao = 100 },
                    new() { Simbolo = "C", Nome = "C (concentração)", ValorPadrao = 5 },
                    new() { Simbolo = "EC50", Nome = "EC₅₀", ValorPadrao = 10 },
                    new() { Simbolo = "n", Nome = "n (Hill coefficient)", ValorPadrao = 1, ValorMin = 0.1 },
                ],
                VariavelResultado = "E (efeito)",
                Calcular = vars => vars["Emax"]*Math.Pow(vars["C"],vars["n"])/(Math.Pow(vars["EC50"],vars["n"])+Math.Pow(vars["C"],vars["n"])) },
            new Formula { Id = "fk_fd02", Nome = "Índice Terapêutico (TI)", Categoria = "Farmacocinética", SubCategoria = "Farmacodinâmica",
                Expressao = "TI = TD₅₀/ED₅₀", ExprTexto = "TI = TD₅₀ / ED₅₀ (margem de segurança)", Icone = "💊",
                Descricao = "Índice terapêutico: razão entre dose tóxica e dose efetiva em 50% da população. TI alto → fármaco mais seguro.",
                Variaveis = [
                    new() { Simbolo = "TD50", Nome = "TD₅₀ (dose tóxica)", ValorPadrao = 500 },
                    new() { Simbolo = "ED50", Nome = "ED₅₀ (dose efetiva)", ValorPadrao = 50 },
                ],
                VariavelResultado = "TI",
                Calcular = vars => vars["TD50"]/vars["ED50"] },
            new Formula { Id = "fk_fd03", Nome = "PK/PD Link Model", Categoria = "Farmacocinética", SubCategoria = "Farmacodinâmica",
                Expressao = "E(t) = Emax·C_e(t)/(EC₅₀+C_e(t))", ExprTexto = "Efeito ligado à concentração no local de efeito (Ce)", Icone = "💊",
                Descricao = "Modelo PK/PD: liga farmacocinética (concentração) à farmacodinâmica (efeito). Compartimento de efeito com lag temporal ke0.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "fk_fd04", Nome = "Fator de Acumulação", Categoria = "Farmacocinética", SubCategoria = "Farmacodinâmica",
                Expressao = "R = 1/(1-e^{-kₑτ})", ExprTexto = "R = 1/(1 − e^(−kₑ·τ)) ≈ 1.44·t½/τ se τ<t½", Icone = "💊",
                Descricao = "Fator de acumulação: quão mais a Css é comparada à 1ª dose. R↑ quando intervalo posológico τ é curto relativo a t½.",
                Variaveis = [
                    new() { Simbolo = "ke", Nome = "kₑ (1/h)", ValorPadrao = 0.1 },
                    new() { Simbolo = "tau", Nome = "τ (intervalo, h)", ValorPadrao = 8 },
                ],
                VariavelResultado = "R (fator de acumulação)",
                Calcular = vars => 1.0/(1-Math.Exp(-vars["ke"]*vars["tau"])) },
            new Formula { Id = "fk_fd05", Nome = "Janela Terapêutica", Categoria = "Farmacocinética", SubCategoria = "Farmacodinâmica",
                Expressao = "MEC < C(t) < MTC", ExprTexto = "MEC < C(t) < MTC (concentração entre mínima eficaz e máxima tolerada)", Icone = "💊",
                Descricao = "Janela terapêutica: faixa de concentração entre MEC (mínima eficaz) e MTC (máxima tolerada). Objetivo do regime posológico.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
        ]);
    }

    // ─────────────────────────────────────────────────────
    // 23. NEUROCIÊNCIA COMPUTACIONAL
    // ─────────────────────────────────────────────────────
    private void AdicionarNeurocienciaComputacional()
    {
        _formulas.AddRange([
            // 23.1 Modelagem Neural
            new Formula { Id = "nc_hh01", Nome = "Modelo de Hodgkin-Huxley", Categoria = "Neurociência Computacional", SubCategoria = "Modelagem Neural",
                Expressao = "C dV/dt = -gNa m³h(V-ENa) - gK n⁴(V-EK) - gL(V-EL) + I", ExprTexto = "C·dV/dt = −gNa·m³h(V−ENa) − gK·n⁴(V−EK) − gL(V−EL) + I_ext", Icone = "⚡",
                Descricao = "Modelo HH: descreve potencial de ação via condutâncias iônicas dependentes de voltagem. 4 EDOs acopladas (V, m, h, n).",
                Criador = "Hodgkin / Huxley", AnoOrigin = "1952",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "nc_hh02", Nome = "Equação de Nernst", Categoria = "Neurociência Computacional", SubCategoria = "Modelagem Neural",
                Expressao = "Eᵢₒₙ = (RT/zF) ln([ion]_out/[ion]_in)", ExprTexto = "E = (RT/zF) ln([ext]/[int]) ≈ 58/z mV (a 37°C) log₁₀", Icone = "⚡",
                Descricao = "Potencial de equilíbrio de Nernst: voltagem onde fluxo difusivo = fluxo elétrico para um íon. ENa ≈ +60mV, EK ≈ -80mV.",
                Criador = "Walther Nernst", AnoOrigin = "1889",
                Variaveis = [
                    new() { Simbolo = "z", Nome = "z (valência do íon)", ValorPadrao = 1 },
                    new() { Simbolo = "Co", Nome = "[íon]_externo (mM)", ValorPadrao = 145 },
                    new() { Simbolo = "Ci", Nome = "[íon]_interno (mM)", ValorPadrao = 12 },
                    new() { Simbolo = "T", Nome = "T (Kelvin)", ValorPadrao = 310 },
                ],
                VariavelResultado = "Eᵢₒₙ (mV)",
                Calcular = vars => (8.314*vars["T"]/(vars["z"]*96485))*Math.Log(vars["Co"]/vars["Ci"])*1000 },
            new Formula { Id = "nc_hh03", Nome = "Equação de Goldman-Hodgkin-Katz", Categoria = "Neurociência Computacional", SubCategoria = "Modelagem Neural",
                Expressao = "Vm = (RT/F) ln((PK[K]o+PNa[Na]o+PCl[Cl]i)/(PK[K]i+PNa[Na]i+PCl[Cl]o))", ExprTexto = "Vm = (RT/F) ln(Σ Pₖ[cat]_o + P_Cl[Cl]_i) / (similar int)", Icone = "⚡",
                Descricao = "Equação GHK: potencial de repouso considerando múltiplos íons e suas permeabilidades. Generaliza Nernst para membranas reais.",
                Criador = "Goldman / Hodgkin / Katz", AnoOrigin = "1943/1949",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Valor x", ValorPadrao = 10, ValorMin = 0.001 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => Math.Log(vars["x"])
            },
            new Formula { Id = "nc_hh04", Nome = "Gating Variable m(V)", Categoria = "Neurociência Computacional", SubCategoria = "Modelagem Neural",
                Expressao = "dm/dt = αₘ(V)(1-m) - βₘ(V)m", ExprTexto = "dm/dt = αₘ(1−m) − βₘ m; m∞ = αₘ/(αₘ+βₘ)", Icone = "⚡",
                Descricao = "Variável de gating m: probabilidade de ativação do canal Na⁺. α,β = taxas dependentes de voltagem. τₘ = 1/(α+β).",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "nc_hh05", Nome = "Corrente Sináptica (AMPA/NMDA)", Categoria = "Neurociência Computacional", SubCategoria = "Modelagem Neural",
                Expressao = "I_syn = g_syn · s(t) · (V - E_syn)", ExprTexto = "I_syn = ḡ_syn · s(t) · (V − E_rev)", Icone = "⚡",
                Descricao = "Corrente sináptica: condutância dependente do tempo s(t) × driving force (V−Erev). AMPA: rápida excitatória. NMDA: lenta, Mg²⁺ block.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "nc_hh06", Nome = "Equação do Cabo (Cable Equation)", Categoria = "Neurociência Computacional", SubCategoria = "Modelagem Neural",
                Expressao = "λ²∂²V/∂x² = τ∂V/∂t + V", ExprTexto = "λ² Vₓₓ = τ Vₜ + V (propagação passiva em dendrito)", Icone = "⚡",
                Descricao = "Equação do cabo: propagação passiva de voltagem em estruturas cilíndricas (dendritos, axônio). λ=constante de espaço, τ=constante de tempo.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "nc_hh07", Nome = "Velocidade de Condução do Potencial de Ação", Categoria = "Neurociência Computacional", SubCategoria = "Modelagem Neural",
                Expressao = "v ∝ √d (não-mielinizado); v ∝ d (mielinizado)", ExprTexto = "v ~ √d (unmyelinated); v ~ d (myelinated, saltatory)", Icone = "⚡",
                Descricao = "Velocidade do PA: cresce com diâmetro do axônio. Mielina: condução saltatória entre nodos de Ranvier → muito mais rápida.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Valor x", ValorPadrao = 4, ValorMin = 0 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => Math.Sqrt(vars["x"])
            },

            // 23.2 Modelos Simplificados
            new Formula { Id = "nc_if01", Nome = "Integrate-and-Fire (LIF)", Categoria = "Neurociência Computacional", SubCategoria = "Modelos Simplificados",
                Expressao = "τ dV/dt = -(V-Vrest) + R·I; se V≥Vth: spike, V→Vreset", ExprTexto = "τ·dV/dt = −(V−V_rest) + RI; V≥V_th → fire & reset", Icone = "⚡",
                Descricao = "LIF (Leaky Integrate-and-Fire): modelo neuronal simplificado. Integra corrente até limiar, depois dispara e reseta. Computacionalmente eficiente.",
                Criador = "Louis Lapicque", AnoOrigin = "1907",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "nc_if02", Nome = "Izhikevich (Modelo de 2 Variáveis)", Categoria = "Neurociência Computacional", SubCategoria = "Modelos Simplificados",
                Expressao = "dv/dt = 0.04v² + 5v + 140 - u + I; du/dt = a(bv-u)", ExprTexto = "v̇ = 0.04v² + 5v + 140 − u + I; u̇ = a(bv−u)", Icone = "⚡",
                Descricao = "Modelo de Izhikevich: 2 EDOs que reproduzem 20+ padrões de disparo neural (regular, bursting, chattering, etc.). Parâmetros a,b,c,d.",
                Criador = "Eugene Izhikevich", AnoOrigin = "2003",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "nc_if03", Nome = "Taxa de Disparo (f-I Curve)", Categoria = "Neurociência Computacional", SubCategoria = "Modelos Simplificados",
                Expressao = "f = 1/(τ ln(RI-VR)/(RI-Vth)) (LIF)", ExprTexto = "f(I) para LIF: cresce monotonicamente acima de I_rheobase", Icone = "⚡",
                Descricao = "Curva f-I: relação entre corrente injetada e taxa de disparo. Tipo I: contínua (frequência→0). Tipo II: descontínua (frequência mínima >0).",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "nc_if04", Nome = "Modelo de FitzHugh-Nagumo", Categoria = "Neurociência Computacional", SubCategoria = "Modelos Simplificados",
                Expressao = "dv/dt = v - v³/3 - w + I; dw/dt = ε(v + a - bw)", ExprTexto = "v̇ = v − v³/3 − w + I; ẇ = ε(v+a−bw)", Icone = "⚡",
                Descricao = "FitzHugh-Nagumo: modelo bidimensional de potencial de ação. Redução do HH. v=excitação, w=recuperação. Análise de plano de fase.",
                Criador = "FitzHugh / Nagumo", AnoOrigin = "1961/1962",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },

            // 23.3 Redes Neurais Biológicas
            new Formula { Id = "nc_nn01", Nome = "Aprendizado Hebbiano", Categoria = "Neurociência Computacional", SubCategoria = "Redes Neurais Biológicas",
                Expressao = "Δwᵢⱼ = η · xᵢ · xⱼ ('fire together → wire together')", ExprTexto = "Δwᵢⱼ = η · pre_i · post_j (correlação)", Icone = "⚡",
                Descricao = "Regra de Hebb: se neurônios pré e pós-sinápticos disparam juntos, conexão se fortalece. Base da plasticidade sináptica.",
                Criador = "Donald Hebb", AnoOrigin = "1949",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "η", Nome = "η", ValorPadrao = 2 }, new() { Simbolo = "pre_i", Nome = "pre_i", ValorPadrao = 3 }, new() { Simbolo = "post_j", Nome = "post_j", ValorPadrao = 4 } ],
                VariavelResultado = "Δwᵢⱼ",
                UnidadeResultado = "",
                Calcular = vars => vars["η"] * vars["pre_i"] * vars["post_j"]
            },
            new Formula { Id = "nc_nn02", Nome = "STDP (Plasticidade Dependente de Timing)", Categoria = "Neurociência Computacional", SubCategoria = "Redes Neurais Biológicas",
                Expressao = "Δw = A₊e^{-Δt/τ₊} se pre→post; A₋e^{Δt/τ₋} se post→pre", ExprTexto = "STDP: LTP se pré antes de pós; LTD se pós antes de pré", Icone = "⚡",
                Descricao = "STDP: janela temporal de ~±20ms. Pré antes de pós → LTP (potenciação). Pós antes de pré → LTD (depressão). Causalidade temporal.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "nc_nn03", Nome = "Equação de Wilson-Cowan", Categoria = "Neurociência Computacional", SubCategoria = "Redes Neurais Biológicas",
                Expressao = "τE dE/dt = -E + S(aEE·E - aEI·I + PE)", ExprTexto = "τ_E Ė = −E + σ(wEE·E − wEI·I + P_ext)", Icone = "⚡",
                Descricao = "Wilson-Cowan: modelo de campo médio para populações excitatórias (E) e inibitórias (I). S = função sigmoidal. Oscilações, bistabilidade.",
                Criador = "Wilson / Cowan", AnoOrigin = "1972",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "nc_nn04", Nome = "Rede de Hopfield", Categoria = "Neurociência Computacional", SubCategoria = "Redes Neurais Biológicas",
                Expressao = "wᵢⱼ = (1/N) Σₚ ξᵢᵖ ξⱼᵖ (memórias ξ)", ExprTexto = "Hopfield: w = (1/N) Σₚξᵖξᵖᵀ (mem. associativa)", Icone = "⚡",
                Descricao = "Rede de Hopfield: memória associativa com dinâmica de minimização de energia. Capacidade ≈ 0.14N padrões em N neurônios.",
                Criador = "John Hopfield", AnoOrigin = "1982",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "nc_nn05", Nome = "Teoria da Informação Neural", Categoria = "Neurociência Computacional", SubCategoria = "Redes Neurais Biológicas",
                Expressao = "I(S;R) = H(R) - H(R|S)", ExprTexto = "Info mútua I = H(resposta) − H(ruído) bits", Icone = "⚡",
                Descricao = "Informação mútua: bits sobre o estímulo S que a resposta R carrega. H(R)=entropia da resposta. Limita eficiência da codificação neural.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "nc_nn06", Nome = "Teoria do Coding Eficiente", Categoria = "Neurociência Computacional", SubCategoria = "Redes Neurais Biológicas",
                Expressao = "Maximizar I(S;R) dado constraints neurais", ExprTexto = "Efficient coding: max I(estímulo; resposta) com restrições", Icone = "⚡",
                Descricao = "Hipótese do coding eficiente (Barlow): neurônios sensoriais evoluíram para maximizar informação transmitida. Explica campos receptivos.",
                Criador = "Horace Barlow", AnoOrigin = "1961",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "nc_nn07", Nome = "Codificação por Taxa vs Temporal", Categoria = "Neurociência Computacional", SubCategoria = "Redes Neurais Biológicas",
                Expressao = "Rate: r(t) = nspikes/Δt; Temporal: timing preciso dos spikes", ExprTexto = "Rate code: freq. de disparos; Temporal: fase/timing", Icone = "⚡",
                Descricao = "Rate coding: informação na frequência média de disparos. Temporal coding: informação no timing preciso dos spikes. Debate central em neurociência.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
        ]);
    }
}
