using System.Collections.Generic;

namespace CompendioCalc.Services
{
    public partial class FormulaService
    {
        private void AdicionarFormulasVol12_Literal_Parte5()
        {
            AdicionarPacoteVol12Detalhado(
                "MODELAGEM CLIMÁTICA E CIÊNCIAS DA ATMOSFERA",
                "Dinâmica Climática e Atmosférica",
                338,
                new List<Vol12FormulaSpec>
                {
                    new("Equilíbrio Radiativo Simples", "ΔT_eq = ΔF / λ", "λ=parâmetro de feedback climático (W/m²/K). ΔF=forçamento radiativo. Sensibilidade climática S=1/λ.", "Manabe e Wetherald", "1967", "ΔF_2×CO₂=3,7 W/m². S=3°C/3,7W/m²=0,81°C/(W/m²). IPCC AR6: S=2,5–4°C. Incerteza em feedback de nuvem"),
                    new("Forçamento Radiativo de CO₂", "ΔF = 5,35·ln(C/C₀)  [W/m²]", "C=concentração atual, C₀=referência (280 ppm pré-industrial). Logarítmico: saturação de bandas.", "Myhre et al.", "1998", "C=420 ppm: ΔF=5,35×ln(420/280)=5,35×0,405=2,17 W/m². C=560 ppm: ΔF=5,35×ln2=3,7 W/m². Dobramento"),
                    new("Equação de Clapeyron-Clausius — Vapor Saturado", "dPs/dT = L·Ps/(RwT²)", "Ps=pressão de vapor saturado, L=calor latente de vaporização, Rw=const. do vapor. Regra de Clausius.", "Clausius; Clapeyron", "1834-1850", "Rw=461 J/kg/K, L=2,5×10⁶ J/kg: dPs/dT=Ps×13,3/T². T=280 K: dPs/dT=0,071 kPa/K. +7%/°C de vapor"),
                    new("Equação de Richardson — Turbulência Atmosférica", "Ri = (g/T)·(∂T/∂z + Γd)/(∂u/∂z)²", "Ri<0,25: turbulência possível. Ri>1: turbulência suprimida. Γd=9,8 K/km (gradiente adiabático seco).", "Richardson", "1922", "Inversão de temperatura: Ri>>1. Camada limite convectiva: Ri<0. TKE (turbulent kinetic energy) budget"),
                    new("Circulação Hadley — Células de Convecção", "ω = −(gw·q/cp)·(∂ln T/∂p)^{−1}  (simplificado)", "ω=velocidade vertical em pressão, q=calor latente. ITCZ: ascensão. Subtropicais: subsidência.", "Hadley", "1735", "ITCZ migra sazonalmente. El Niño: ITCZ desloca. Energia: 300 W/m² transportada. GCMs modelam circulação"),
                    new("Oscilação El Niño-Southern Oscillation (ENSO)", "SOI = (Δp_Tahiti − Δp_Darwin)/DP", "SOI<−7: El Niño. SOI>+7: La Niña. Período: 3–7 anos. Teleconexões globais.", "Walker", "1924", "El Niño 1997–98: SOI=−30. Consequências: seca no NE Brasil, chuvas no Sul. PDO: modulação decadal"),
                    new("Modelo de Coluna — Temperatura de Emissão Efetiva", "Te = T_surface × (1−τ_effective)^{1/4}  (approx)", "τ=profundidade óptica do GHG. Mais GHG: Te↑ (topo emissivo mais quente). Simplificado.", "Base de meteorologia e mudança climática", "Séc. XX", "CO₂ 280→420 ppm: τ↑ → Te em altitude mais alta → T_sup↑ para re-equilibrar. Mecanismo do efeito estufa"),
                    new("Saldo de Radiação na TOA", "N = FSW(1−α) − FLW  [W/m²]", "FSW=radiação solar incidente, α=albedo, FLW=radiação de onda longa emitida. N>0: aquecimento do planeta.", "Trenberth e Fasullo", "2012", "FSW=341 W/m², α=0,30, FLW=238 W/m²: N=341×0,7−238=0,9 W/m². Desequilíbrio atual: +0,9 W/m²"),
                    new("Temperatura de Neve Estacionária", "Δα·ΔF_SW = λ·ΔT  (feedback ice-albedo)", "Ice-albedo feedback: ΔT positivo → gelo derrete → α↓ → mais absorção → ΔT maior. Feedback positivo.", "Budyko; Sellers", "1969", "α_gelo=0,6, α_oceano=0,07. Derretimento do Ártico: ΔF=+0,3 W/m² → amplificação ártica 2–3× global"),
                    new("Concentração de CO₂ — Ciclo Sazonal", "C(t) = C_mean + a·sin(2πt+φ)", "Amplitude sazonal: ~10 ppm no NH (fotossíntese verão). Tendência de aumento: 2 ppm/ano.", "Keeling", "1958", "1958: 315 ppm. 2024: 424 ppm. Sazonal: max em maio (NH inverno), min em setembro. Keeling Curve"),
                    new("Tempo de Residência de CO₂ na Atmosfera", "τ_CO₂ ≈ 5 × τ_simples  (absorção multietapa)", "τ simples=4 anos. Partição em oceano+bio: equilibration time=1000 anos para 20%. Inércia climática.", "Joos et al.", "2013", "50% do CO₂ emitido absorvido em 30 anos. 20% permanece por 1000+ anos. Impossibilidade de cooling imediato"),
                    new("Modelo de Circulação Geral — Balanço de Vapor", "∂q/∂t = −∇·(vq) − E + P", "q=razão de mistura de vapor, E=evaporação, P=precipitação. Transporte horizontal crítico.", "Manabe e Wetherald", "1967", "GCMs com ~50 km de resolução: 10⁸ equações diferenciais. Ciclo hidrológico: P global=2,7 mm/dia. CMIP6"),
                    new("Ciclone Tropical — Vento Máximo", "Vmax = √(Ck/Cd·(SST−Tout)·k*−k)", "Ck/Cd=eficiência aerodinâmica, SST=temperatura da superfície do mar, k=entalpia do ar.", "Emanuel", "1986", "SST=30°C: Vmax potencial=75 m/s (145 kt). SST↑2°C: Vmax↑5 m/s. Intensificação rápida: SST>28,5°C"),
                    new("Temperatura Global Média — Anomalia", "ΔT = T_atual − T_referência (1850–1900)", "IPCC AR6: ΔT=1,1°C (2011–2020 vs 1850–1900). Meta Paris: <1,5°C ou <2°C.", "IPCC AR6 WGI", "2021", "2024: ~1,3°C acima do pré-industrial. Último ano a <1,5°C: possivelmente 2030–2035. NDCs insuficientes"),
                    new("Temperatura de Permafrost", "T_permafrost(z) = T_mean + A_surface × e^{−z/d} × cos(2πt/P − z/d)", "d=profundidade de amortecimento, A=amplitude superficial, P=período (1 ano). Degradação por ΔT.", "Base de criologia e permafrost", "Séc. XX", "Sibéria: T_permafrost(z→∞)=−5°C. d=3,5 m (anual). Aquecimento: ativo layer↑ → CH₄ liberado. Feedback"),
                    new("Índice de Severidade de Seca — PDSI", "PDSI = f(P, PET, storage)  (Palmer)", "Índice adimensional. PDSI<−2: seca moderada. PDSI<−4: seca extrema. Memória de meses.", "Palmer", "1965", "Texas 2011: PDSI=−6 (seca excepcional). Nordeste Brasil La Niña: PDSI=−3. SPI: alternativa padronizada"),
                    new("Albedo Planetário — Contribuições", "α = α_superfície × T_atmosfera + α_nuvens", "Albedo médio terrestre=0,30. Nuvens: contribuem ~0,18. Superfícies: oceano=0,07, deserto=0,35.", "Base de balanço radiativo da Terra", "Séc. XX", "α_Terra=0,30 (CERES). α_Vénus=0,77 (nuvens densas). α_Lua=0,12 (sem atmosfera). Feedback de nuvem: ±0,5°C"),
                    new("Precipitação — Índice de Extremo Climático", "R99p: precipitação total nos dias muito chuvosos (>99° percentil)", "Índices de ETCCDI. R99p aumentou 6% por °C de aquecimento (Clausius-Clapeyron).", "Alexander et al.; ETCCDI", "2006", "Brasil SE: R99p=12% da precipitação anual. São Paulo 2024: eventos extremos de chuva mais frequentes"),
                    new("Calor Oceânico — OHC", "ΔOHC = ρ·cp·∫ΔT·dV", "ρ=1025 kg/m³, cp=4000 J/kg/K. 90% do calor do sistema climático vai para o oceano.", "Levitus et al.", "2012", "2023: recorde de OHC. 0–2000 m: ΔT=0,1°C equivale a 5×10²³ J. Expansão térmica: +1 mm SLR por 10²² J")
                });

            AdicionarPacoteVol12Detalhado(
                "CIÊNCIAS DA COMPUTAÇÃO APLICADAS — ALGORITMOS E OTIMIZAÇÃO",
                "Algoritmos e Otimização",
                357,
                new List<Vol12FormulaSpec>
                {
                    new("Algoritmo de Dijkstra — Complexidade", "T = O((V+E)log V)  com heap binário", "V=vértices, E=arestas. Fibonacci heap: O(E+V log V). Caminhos mínimos em grafos com pesos positivos.", "Dijkstra", "1959", "GPS: Dijkstra em grafo de rodovias. A*: admissível se h(v)≤d(v,t). Bidirectional: 2× mais rápido"),
                    new("Algoritmo de Floyd-Warshall", "D[i][j] = min(D[i][j], D[i][k]+D[k][j])  para todo k", "Todos os pares de caminhos mínimos. O(V³). Detecta ciclos negativos: D[i][i]<0.", "Floyd; Warshall", "1962", "Roteamento OSPF: Floyd-Warshall. V=100 roteadores: 10⁶ ops. D de Johnson: O(VE+V²log V) para esparsas"),
                    new("Programação Dinâmica — Mochila 0/1", "OPT(i,W) = max(OPT(i−1,W), vi+OPT(i−1,W−wi))", "O(nW) tempo e espaço. Pseudo-polinomial: W pode ser grande. FPTAS: aproximação em O(n³/ε).", "Bellman; Dantzig", "1954-1957", "n=100 itens, W=1000: tabela 100×1000=10⁵ células. Corte de estoque, alocação de recursos"),
                    new("Algoritmo de Kruskal — Árvore Geradora Mínima", "Sort arestas; add se não forma ciclo (Union-Find)", "T = O(E log E). Union-Find com rank e path compression: O(E·α(V)) ≈ O(E).", "Kruskal", "1956", "Rede elétrica: MST minimiza cabo total. Prim: O((V+E)log V). Borůvka: paralelo. Rede de telecomunicações"),
                    new("Algoritmo de Ford-Fulkerson — Fluxo Máximo", "max_flow = min_cut  (max-flow min-cut theorem)", "Augmenting paths. Edmonds-Karp (BFS): O(VE²). Dinic: O(V²E). Preflow-Push: O(V²√E).", "Ford e Fulkerson", "1956", "Redes de transporte: fluxo máximo = capacidade de corte mínima. Matching bipartite: fluxo em rede"),
                    new("Algoritmo A* — Heurística Admissível", "f(n) = g(n) + h(n);  h(n)≤d(n,goal)", "g=custo acumulado, h=heurística admissível. Ótimo se h admissível e consistente.", "Hart, Nilsson e Raphael", "1968", "Robô: h=distância Euclidiana. Mapas com obstáculos: JPS (Jump Point Search). PathFinding.js"),
                    new("Transformada de Haar — Compressão Wavelet", "H₁=[1,1]/√2; H₂=[1,−1]/√2", "Wavelet de Haar: mais simples. DWT 2D: JPEG2000. Sparse representation: compressão sem percepção visual.", "Haar", "1910", "Imagem 1024×1024: 10⁶ pixels. DWT 4 níveis: 97% dos coeficientes→zero. Compressão sem perda percebida"),
                    new("Algoritmo de Karatsuba — Multiplicação Rápida", "ab = (a₁b₁)×10^n + ((a₁+a₀)(b₁+b₀)−a₁b₁−a₀b₀)×10^{n/2} + a₀b₀", "T = O(n^{log₂3}) ≈ O(n^{1,585})  vs O(n²) clássico. Divide-and-conquer.", "Karatsuba e Ofman", "1962", "n=10⁶ dígitos: Karatsuba 10⁹ vs clássico 10¹². GMP: big integers. FFT multiplication: O(n log n log log n)"),
                    new("Heapsort — Complexidade", "T = O(n log n)  pior caso, in-place", "Constrói max-heap em O(n). Extrai máximo n vezes em O(log n) cada. Constante menor que mergesort.", "Williams; Floyd", "1964", "Mergesort: O(n log n) estável. Quicksort: O(n log n) médio, O(n²) pior. Introsort (std::sort C++): híbrido"),
                    new("Algoritmo de Boyer-Moore-Horspool — Busca de Padrão", "Shift = max(good_suffix, bad_character)", "Shift por tabela pré-computada. Melhor caso: O(n/m). Pior: O(nm). Melhor que KMP na prática.", "Boyer e Moore; Horspool", "1977-1980", "grep: Boyer-Moore. DNA search: Aho-Corasick para múltiplos padrões. n=10⁹ chars, m=50: ~0,1 seg"),
                    new("Backtracking — N-Rainhas", "Recursão com pruning: se conflito→backtrack", "Pior caso: O(n!). Com pruning: muito mais rápido. Constraint propagation (arc-consistency) melhora.", "Base de algoritmos de busca e backtracking", "Séc. XX", "N=8: 92 soluções. N=15: 2 million nós visitados com backtracking puro. MRV heuristic: first-fail"),
                    new("Algoritmo de Prim — Complexidade com Heap", "T = O((V+E) log V)", "Para grafos densos: matriz de adjacência → O(V²). Fibonacci heap: O(E+V log V).", "Prim; Jarník", "1930-1957", "Rede de sensor sem fio: MST minimiza energia total. Aplicação em clustering: minimum spanning tree"),
                    new("Cálculo de Inversão de Matriz — Gauss-Jordan", "T = O(n³)  eliminação gaussiana", "Número de condicionamento κ=σmax/σmin: amplifica erros numéricos. LU decomposition preferível.", "Base de álgebra linear computacional", "Séc. XX", "Gauss-Jordan: numericamente instável para κ grande. Partial pivoting: estabiliza. LAPACK: DGESV"),
                    new("Algoritmo de PageRank", "PRi = (1−d)/N + d × Σ_{j→i} PRj/Lj", "d=0,85 (damping factor), N=total páginas, Lj=links de saída de j. Convergência: 50–100 iterações.", "Brin e Page", "1998", "Google 1998: ~10⁶ páginas. 2024: ~10¹² páginas. HITS alternativo. Personalized PageRank: recomendações"),
                    new("Complexidade da Transformada de Fourier — Cooley-Tukey", "T_FFT = O(N log N)  vs  O(N²) da DFT", "Divide N=2×(N/2). Recursão: T(N)=2T(N/2)+O(N). Base de álgebra computacional.", "Cooley e Tukey; Gauss", "1805-1965", "N=10⁶: FFT=2×10⁷ vs DFT=10¹². Convolução em O(N log N). Multiplicação de polinômios. NumPy FFT"),
                    new("Codificação de Huffman — Ótima", "L_Huffman ≤ H(X)+1  [bits/símbolo]", "Huffman: código prefixo-livre ótimo. Convergente a H quando codificando blocos.", "Huffman; Shannon", "1948-1952", "Texto inglês: H≈4,5 bits/char. Huffman: L=4,7 bits/char. Deflate (ZIP): LZ77 + Huffman. Entropy coding"),
                    new("Programação Linear — Dualidade", "max cᵀx s.a. Ax≤b, x≥0  ↔  min bᵀy s.a. Aᵀy≥c, y≥0", "Valor ótimo primal = dual (strong duality). Preço-sombra: interpretação econômica de y*.", "Dantzig; von Neumann", "1947", "Mistura ótima de rações: max lucro s.a. nutrientes. Dual: preços de equilíbrio. Simplex: V pivôs~O(m)"),
                    new("Algoritmo de Bellman-Ford — Pesos Negativos", "d[v] = min(d[v], d[u]+w(u,v))  V−1 iterações", "T=O(VE). Detecta ciclos negativos em iteração V. Mais lento que Dijkstra mas mais geral.", "Bellman; Ford", "1956-1958", "Arbitragem cambial: ciclo negativo = lucro. OSPF com pesos negativos impossível; use EIGRP. Potencial de Johnson"),
                    new("Algoritmo de Simulated Annealing", "P(aceitar piora) = e^{−ΔE/T}  com T→0 lentamente", "T=temperatura que decresce. Escapa de ótimos locais. Convergência: T→0 suficientemente devagar.", "Kirkpatrick, Gelatt e Vecchi", "1983", "TSP de 100 cidades: SA chega a <2% do ótimo. T₀=1000, resfriamento=0,99. VLSI placement, design de circuito")
                });

            AdicionarPacoteVol12Detalhado(
                "MATEMÁTICA FINANCEIRA E ATUARIAL",
                "Finanças e Atuária",
                376,
                new List<Vol12FormulaSpec>
                {
                    new("Valor Futuro com Juros Compostos", "FV = PV × (1+i)^n", "PV=valor presente, i=taxa por período, n=número de períodos. Base de toda matemática financeira.", "Fibonacci; Simon Stevin", "1202-1585", "R$1000 a 1% ao mês por 24 meses: FV=1000×(1,01)^{24}=R$1269,73. Poder dos juros compostos: duplicação"),
                    new("Valor Presente Líquido", "VPL = −C₀ + Σ FCt/(1+i)^t", "C₀=investimento inicial, FC=fluxo de caixa. VPL>0: projeto cria valor. TIR: i que zera VPL.", "Base de finanças corporativas", "Séc. XX", "Planta industrial: C₀=R$1M, FC=R$300k/ano, i=12%: VPL=−1000+300/0,12=+R$500k. Aprovado!"),
                    new("Taxa Interna de Retorno", "TIR: Σ FCt/(1+TIR)^t = C₀", "Comparar TIR com custo de capital (WACC). TIR>WACC: criar valor. Múltiplas TIRs: fluxo não-convencional.", "Base de análise de projetos (Fisher)", "1930", "VPL=0 quando TIR=15%. WACC=10%: projeto aceitável. Projetos mutuamente exclusivos: usar VPL, não TIR"),
                    new("Anuidade Perpétua", "PV = PMT/i", "PMT=pagamento periódico constante, i=taxa de juros. Limite de anuidade com n→∞.", "Base de matemática financeira clássica", "Séc. XIX", "Bônus perpétuo (Consol britânico): PMT=£5, i=5%: PV=£100. Dividendo de ação: PV=D₁/(r−g) Gordon"),
                    new("Modelo de Gordon — Precificação de Ações", "P₀ = D₁/(r−g)", "D₁=dividendo próximo, r=taxa de retorno exigida, g=taxa de crescimento perpétuo de dividendos.", "Gordon e Shapiro", "1956", "D₁=R$3, r=15%, g=5%: P₀=3/(0,15−0,05)=R$30. r<g: não aplicável (bolha). DDM: dividend discount model"),
                    new("Fórmula de Black-Scholes", "C = S·N(d₁) − K·e^{-rT}·N(d₂)", "d₁=[ln(S/K)+(r+σ²/2)T]/(σ√T). d₂=d₁−σ√T. N=CDF normal. Opção de compra europeia.", "Black e Scholes; Merton", "1973", "S=R$100, K=R$105, r=5%, σ=20%, T=0,5: d₁=0,14, C≈R$6,80. IV=σ implícita. Put-call parity: P=C−S+Ke^{-rT}"),
                    new("Greeks da Opção — Delta", "Δ = ∂C/∂S = N(d₁)", "Sensibilidade do prêmio ao preço do subjacente. Delta hedge: portfólio neutro ao preço.", "Base de teoria de derivativos (Hull)", "2022", "Opção ATM: Δ≈0,5. Deep ITM: Δ→1. Deep OTM: Δ→0. Delta-hedge: vender Δ ações por opção comprada"),
                    new("Greeks da Opção — Vega", "ν = ∂C/∂σ = S·√T·N'(d₁)", "Sensibilidade ao σ (volatilidade implícita). Maior para opções ATM e prazos longos.", "Base de gestão de risco de opções", "Séc. XX", "Opção com Δ=0,5, T=0,5: ν=S×0,5×0,4=0,2S por unit de σ. VIX: impliedσ de S&P500. Vega riskneutral"),
                    new("Prêmio de Seguro — Princípio da Esperança", "P_puro = E[X] = Σ xᵢ·pᵢ", "P_puro=prêmio puro. P_comercial=P_puro×(1+carregamento). Princípio de equidade atuarial.", "Base de ciências atuariais", "Séc. XX", "Seguro de vida: X=R$500k com p=0,002: P_puro=R$1000. Carregamento 30%: P_comercial=R$1300"),
                    new("Tábua de Mortalidade — Probabilidade de Morte", "qx = dx/lx", "lx=sobreviventes à idade x, dx=mortes em [x,x+1). Base de seguros de vida e previdência.", "Graunt; Halley", "1662-1693", "l₀=100000, l₃₀=97500, l₃₁=97350: q₃₀=150/97500=0,00154. Expectativa de vida: e₀=Σlx/l₀=76 anos"),
                    new("Valor Presente Atuarial — Anuidade de Vida", "äx = Σ vᵏ·kpx  onde v=1/(1+i)", "kpx=probabilidade de sobreviver k anos. äx: custo de pagar R$1/ano enquanto viver.", "Base de matemática atuarial", "Séc. XX", "i=5%, äx(60)=12 (tábua BR-EMS). Previdência: benefício R$3000/mês: PV=3000×12×12=R$432k"),
                    new("Capital de Risco — Ruína Atuarial", "P(ruína) = (1−θ)×e^{-θu/μ}  (Cramér-Lundberg)", "θ=loading factor, u=capital inicial, μ=sinistro médio. Base de solvência de seguradoras.", "Cramér; Lundberg", "1903-1930", "θ=0,3, u=100k, μ=10k: P(ruína)=0,7×e^{-0,3×10}=0,7×0,05=3,5%. Solvência II: capital de risco mínimo"),
                    new("Modelo de Cox — Precificação de Bonds", "P = e^{-∫rdt}·E[face_value]", "r=taxa de juros estocástica (CIR, Vasicek). Curva de juros: P(t,T) para todos T.", "Cox, Ingersoll, Ross", "1985", "Vasicek: dr=κ(θ−r)dt+σdW. Bond pricing: P(t,T)=A(t,T)e^{-B(t,T)r}. Calibração por yield curve"),
                    new("Duration Modificada — Risco de Taxa", "D_mod = D_Macaulay/(1+y)", "ΔP/P ≈ −D_mod·Δy. Duration=sensibilidade de preço ao yield. Convexidade: 2ª ordem.", "Macaulay; Hicks", "1938-1939", "Bond 10 anos, coupon 5%, y=6%: D_Mac=8,1, D_mod=7,6. Δy=+1%: ΔP/P≈−7,6%. Hedging de risco de taxa"),
                    new("Índice de Sharpe", "SR = (R_p − Rf) / σ_p", "R_p=retorno do portfólio, Rf=taxa livre de risco, σ_p=desvio padrão de retorno. SR>1: bom.", "Sharpe", "1966", "Fundo de ações: R_p=15%, Rf=10%, σ=20%: SR=0,25. SR=1: excelente. Sortino: usa downside deviation"),
                    new("Modelo de Merton — Risco de Crédito", "Valor da empresa: V = E+D; Default: V<D em T", "E=opção de compra (equity), D=valor de face da dívida. Prob default: N(−d₂) do BS.", "Merton", "1974", "V=R$100M, D=R$70M, σ=30%, T=5a: PD=N(−d₂)=N(−1,2)=12%. Spread de crédito: r_D−r_f=PD×LGD/1−PD"),
                    new("HJM — Heath-Jarrow-Morton Framework", "df(t,T) = μ(t,T)dt + σ(t,T)dW", "f(t,T)=taxa forward no tempo t para maturidade T. HJM arbitra-free: μ=σ(T)∫σ(s)ds.", "Heath, Jarrow e Morton", "1992", "HJM: modelo geral de curva de juros. LMM (LIBOR Market Model): caso especial. Precifica swaptions"),
                    new("CAPM — Linha de Mercado de Títulos", "E[Ri] = Rf + βi(E[Rm]−Rf)", "βi=Cov(Ri,Rm)/Var(Rm). E[Rm]−Rf=prêmio de risco de mercado. Alfa: retorno acima de CAPM.", "Sharpe; Lintner; Mossin", "1964-1966", "Ação com β=1,5, Rf=10%, E[Rm]=15%: E[Ri]=10+1,5×5=17,5%. Alpha positivo: acima da SML"),
                    new("Índice de Gini", "G = 1 − 2∫₀¹ L(F)dF  (área acima da Lorenz)", "L(F)=curva de Lorenz. G=0: igualdade perfeita. G=1: desigualdade máxima. Base de economia do bem-estar.", "Gini", "1912", "Brasil: G=0,49 (alta desigualdade). Nórdicos: G=0,25. China: G=0,38 (crescendo). Palma ratio: top10/bot40"),
                    new("Valor em Risco Condicional — CVaR", "CVaR_α = E[X|X>VaR_α]", "CVaR=Expected Shortfall: média das perdas acima do VaR. Coerente (superaditividade).", "Rockafellar e Uryasev", "2000", "VaR(99%)=R$1M. Perdas acima de R$1M (1% dos dias): média=R$2M=CVaR. Basileia III: adota CVaR"),
                    new("Modelo de Crédito — PD, LGD, EAD", "EL = PD × LGD × EAD", "EL=perda esperada. Capital econômico: UL=√Var(perdas)−EL. IRB (Basileia): PD estimada internamente.", "Basileia II; base de gestão de risco de crédito", "2004", "PD=2%, LGD=45%, EAD=R$1M: EL=R$9000. UL depende da correlação de ativos. Rating interno: PD por grade")
                });
        }
    }
}