using CompendioCalc.Models;

namespace CompendioCalc.Services;

public partial class FormulaService
{
    // ═════════════════════════════════════════════════════════════
    //  VOLUME 2 — PARTE II: FÍSICA AVANÇADA
    // ═════════════════════════════════════════════════════════════

    // ─────────────────────────────────────────────────────
    // 7. MECÂNICA ANALÍTICA
    // ─────────────────────────────────────────────────────
    private void AdicionarMecanicaAnalitica()
    {
        _formulas.AddRange([
            // 7.1 Mecânica Lagrangiana
            new Formula { Id = "ma_l01", Nome = "Lagrangiano L = T - V", Categoria = "Mecânica Analítica", SubCategoria = "Lagrangiana",
                Expressao = "L(q, q̇, t) = T - V", ExprTexto = "L(q, q̇, t) = T − V", Icone = "ℒ",
                Descricao = "Lagrangiano: diferença entre energia cinética e potencial. Base da formulação lagrangiana da mecânica.",
                Criador = "Joseph-Louis Lagrange", AnoOrigin = "1788",
                Variaveis = [ new() { Simbolo = "T", Nome = "Energia Cinética T", ValorPadrao = 50 }, new() { Simbolo = "V", Nome = "Energia Potencial V", ValorPadrao = 20 } ],
                VariavelResultado = "L", Calcular = vars => vars["T"] - vars["V"] },
            new Formula { Id = "ma_l02", Nome = "Equações de Euler-Lagrange (Mecânica)", Categoria = "Mecânica Analítica", SubCategoria = "Lagrangiana",
                Expressao = "d/dt(∂L/∂q̇ᵢ) - ∂L/∂qᵢ = 0", ExprTexto = "d/dt(∂L/∂q̇ᵢ) − ∂L/∂qᵢ = 0", Icone = "ℒ",
                Descricao = "Equações de movimento de Lagrange para cada coordenada generalizada qᵢ. Equivalentes às leis de Newton.",
                Criador = "Euler / Lagrange", AnoOrigin = "1755",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "ma_l03", Nome = "Momento Generalizado pᵢ", Categoria = "Mecânica Analítica", SubCategoria = "Lagrangiana",
                Expressao = "pᵢ = ∂L/∂q̇ᵢ", ExprTexto = "pᵢ = ∂L/∂q̇ᵢ (momento conjugado)", Icone = "ℒ",
                Descricao = "Momento conjugado a qᵢ: derivada parcial do Lagrangiano em relação à velocidade generalizada. Para partícula livre: p=mv.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "ma_l04", Nome = "Coordenada Cíclica", Categoria = "Mecânica Analítica", SubCategoria = "Lagrangiana",
                Expressao = "∂L/∂qᵢ=0 ⟹ pᵢ=const", ExprTexto = "∂L/∂qᵢ = 0 ⟹ pᵢ conservado", Icone = "ℒ",
                Descricao = "Se L não depende explicitamente de qᵢ (coordenada cíclica/ignorável), o momento conjugado pᵢ é constante de movimento.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "ma_l05", Nome = "Lagrangiano para N partículas", Categoria = "Mecânica Analítica", SubCategoria = "Lagrangiana",
                Expressao = "L = Σ ½mᵢ|q̇ᵢ|² - V(q₁,...,qₙ)", ExprTexto = "L = Σᵢ ½mᵢ|q̇ᵢ|² − V(q₁,...,qₙ)", Icone = "ℒ",
                Descricao = "Lagrangiano de sistema de N partículas: soma das energias cinéticas menos potencial total.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "ma_l06", Nome = "Pêndulo Simples (Lagrangiano)", Categoria = "Mecânica Analítica", SubCategoria = "Lagrangiana",
                Expressao = "L = ½ml²θ̇² + mgl cosθ", ExprTexto = "L = ½ml²θ̇² + mgl cos θ", Icone = "ℒ",
                Descricao = "Lagrangiano do pêndulo simples em coord. generalizadas. EL dá: mlθ̈ = -mg sinθ.",
                Variaveis = [
                    new() { Simbolo = "m", Nome = "Massa m (kg)", ValorPadrao = 1, ValorMin = 0.01 },
                    new() { Simbolo = "l", Nome = "Comprimento l (m)", ValorPadrao = 1, ValorMin = 0.01 },
                    new() { Simbolo = "g", Nome = "Gravidade g (m/s²)", ValorPadrao = 9.81 },
                ],
                VariavelResultado = "ω (freq. oscilação peq.) = √(g/l)",
                Calcular = vars => Math.Sqrt(vars["g"] / vars["l"]) },
            new Formula { Id = "ma_l07", Nome = "Função de Energia de Jacobi h", Categoria = "Mecânica Analítica", SubCategoria = "Lagrangiana",
                Expressao = "h = Σ q̇ᵢ(∂L/∂q̇ᵢ) - L", ExprTexto = "h = Σᵢ q̇ᵢ pᵢ − L", Icone = "ℒ",
                Descricao = "Função energia de Jacobi. Se L não depende explicitamente de t, h é conservada. Para sistemas naturais h=T+V=E.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "ma_l08", Nome = "Forças Generalizadas", Categoria = "Mecânica Analítica", SubCategoria = "Lagrangiana",
                Expressao = "Qᵢ = Σⱼ Fⱼ · ∂rⱼ/∂qᵢ", ExprTexto = "Qᵢ = Σⱼ Fⱼ · ∂rⱼ/∂qᵢ (força generalizada)", Icone = "ℒ",
                Descricao = "Projeção das forças no espaço de coordenadas generalizadas. Com forças não-conservativas: d/dt(∂L/∂q̇ᵢ)-∂L/∂qᵢ=Qᵢ.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "ma_l09", Nome = "Multiplicadores de Lagrange (Vínculos)", Categoria = "Mecânica Analítica", SubCategoria = "Lagrangiana",
                Expressao = "d/dt(∂L/∂q̇ᵢ)-∂L/∂qᵢ = Σⱼ λⱼ∂fⱼ/∂qᵢ", ExprTexto = "EL com vínculos: d/dt(∂L/∂q̇ᵢ)−∂L/∂qᵢ = Σⱼλⱼ(∂fⱼ/∂qᵢ)", Icone = "ℒ",
                Descricao = "Equações de Lagrange com multiplicadores para vínculos holônomos fⱼ(q,t)=0. λⱼ representam forças de vínculo.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "ma_l10", Nome = "Princípio de d'Alembert", Categoria = "Mecânica Analítica", SubCategoria = "Lagrangiana",
                Expressao = "Σᵢ(Fᵢ - mᵢaᵢ)·δrᵢ = 0", ExprTexto = "Σᵢ (Fᵢ − mᵢ r̈ᵢ) · δrᵢ = 0", Icone = "ℒ",
                Descricao = "Forças aplicadas menos forças de inércia são virtuais: trabalho virtual nulo para deslocamentos compatíveis com vínculos. Base das equações de Lagrange.",
                Criador = "Jean le Rond d'Alembert", AnoOrigin = "1743",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },

            // 7.2 Mecânica Hamiltoniana
            new Formula { Id = "ma_h01", Nome = "Hamiltoniano H = Σpᵢq̇ᵢ - L", Categoria = "Mecânica Analítica", SubCategoria = "Hamiltoniana",
                Expressao = "H(q,p,t) = Σ pᵢq̇ᵢ - L", ExprTexto = "H(q,p,t) = Σᵢ pᵢq̇ᵢ − L (transformada de Legendre)", Icone = "ℒ",
                Descricao = "Hamiltoniano: energia do sistema em termos de coordenadas e momentos. Para sistemas conservativos H=T+V=E.",
                Criador = "William Rowan Hamilton", AnoOrigin = "1835",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "ma_h02", Nome = "Equações de Hamilton", Categoria = "Mecânica Analítica", SubCategoria = "Hamiltoniana",
                Expressao = "q̇ᵢ=∂H/∂pᵢ; ṗᵢ=-∂H/∂qᵢ", ExprTexto = "q̇ᵢ = ∂H/∂pᵢ ; ṗᵢ = −∂H/∂qᵢ", Icone = "ℒ",
                Descricao = "Equações canônicas de Hamilton: 2n equações de 1ª ordem equivalentes às n equações de Lagrange de 2ª ordem.",
                Criador = "Hamilton", AnoOrigin = "1835",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "ma_h03", Nome = "Colchete de Poisson", Categoria = "Mecânica Analítica", SubCategoria = "Hamiltoniana",
                Expressao = "{f,g} = Σ(∂f/∂qᵢ·∂g/∂pᵢ - ∂f/∂pᵢ·∂g/∂qᵢ)", ExprTexto = "{f,g} = Σᵢ (∂f/∂qᵢ ∂g/∂pᵢ − ∂f/∂pᵢ ∂g/∂qᵢ)", Icone = "ℒ",
                Descricao = "Operação fundamental na mecânica hamiltoniana. Se {f,H}=0 e ∂f/∂t=0, então f é constante de movimento. Análogo clássico do comutador quântico.",
                Criador = "Poisson", AnoOrigin = "1809",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "ma_h04", Nome = "Evolução Temporal df/dt", Categoria = "Mecânica Analítica", SubCategoria = "Hamiltoniana",
                Expressao = "df/dt = ∂f/∂t + {f,H}", ExprTexto = "df/dt = ∂f/∂t + {f, H}", Icone = "ℒ",
                Descricao = "Evolução temporal de qualquer observável f no espaço de fase via colchete de Poisson com H.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "ma_h05", Nome = "Relações Canônicas", Categoria = "Mecânica Analítica", SubCategoria = "Hamiltoniana",
                Expressao = "{qᵢ,pⱼ}=δᵢⱼ; {qᵢ,qⱼ}=0; {pᵢ,pⱼ}=0", ExprTexto = "{qᵢ,pⱼ}=δᵢⱼ; {qᵢ,qⱼ}=0; {pᵢ,pⱼ}=0", Icone = "ℒ",
                Descricao = "Relações fundamentais de Poisson entre coordenadas e momentos canônicos. Análogos clássicos de [q̂,p̂]=iℏ.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "ma_h06", Nome = "Transformação Canônica", Categoria = "Mecânica Analítica", SubCategoria = "Hamiltoniana",
                Expressao = "(q,p)→(Q,P): preserva {Qᵢ,Pⱼ}=δᵢⱼ", ExprTexto = "Trans. canônica: (q,p) → (Q,P) preservando colchetes de Poisson", Icone = "ℒ",
                Descricao = "Mudança de variáveis no espaço de fase que preserva a forma das equações de Hamilton. Preserva colchetes de Poisson.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "ma_h07", Nome = "Equação de Hamilton-Jacobi", Categoria = "Mecânica Analítica", SubCategoria = "Hamiltoniana",
                Expressao = "H(q, ∂S/∂q, t) + ∂S/∂t = 0", ExprTexto = "H(q, ∂S/∂q, t) + ∂S/∂t = 0", Icone = "ℒ",
                Descricao = "Equação de Hamilton-Jacobi: EDP para a função geradora S da transformação canônica que trivializa o sistema. Conexão com óptica e mecânica quântica.",
                Criador = "Hamilton / Jacobi", AnoOrigin = "~1837",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "ma_h08", Nome = "Teorema de Liouville (Fase)", Categoria = "Mecânica Analítica", SubCategoria = "Hamiltoniana",
                Expressao = "dρ/dt = 0 (fase preserva volume)", ExprTexto = "Volume no espaço de fase é conservado", Icone = "ℒ",
                Descricao = "O fluxo hamiltoniano preserva volume no espaço de fase. ρ(q,p,t) satisfaz ∂ρ/∂t + {ρ,H} = 0.",
                Criador = "Joseph Liouville", AnoOrigin = "1838",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "ma_h09", Nome = "Variáveis de Ação-Ângulo", Categoria = "Mecânica Analítica", SubCategoria = "Hamiltoniana",
                Expressao = "J = (1/2π)∮p dq; θ̇ = ∂H/∂J = ω", ExprTexto = "J = (1/2π) ∮ p dq; θ̇ = ω = ∂H/∂J", Icone = "ℒ",
                Descricao = "Para sistemas integráveis, variáveis ação J (constantes) e ângulo θ (evolução linear) simplificam o movimento. Quantização semiclássica: J=nℏ.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },

            // 7.3 Princípio de Menor Ação
            new Formula { Id = "ma_s01", Nome = "Princípio de Hamilton", Categoria = "Mecânica Analítica", SubCategoria = "Ação",
                Expressao = "δS = δ∫L dt = 0", ExprTexto = "δS = δ ∫ₜ₁ᵗ² L(q,q̇,t) dt = 0", Icone = "ℒ",
                Descricao = "O caminho real no espaço de configuração é aquele que extremiza a ação S. Princípio variacional fundamental.",
                Criador = "Hamilton", AnoOrigin = "1834",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "a", Nome = "Limite inferior", ValorPadrao = 0 }, new() { Simbolo = "b", Nome = "Limite superior", ValorPadrao = 1 }, new() { Simbolo = "n", Nome = "Subdivisões", ValorPadrao = 100, ValorMin = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => (vars["b"] - vars["a"]) / vars["n"]
            },
            new Formula { Id = "ma_s02", Nome = "Princípio de Maupertuis", Categoria = "Mecânica Analítica", SubCategoria = "Ação",
                Expressao = "δW = δ∫p·dq = 0 (E fixo)", ExprTexto = "δ ∫ p · dq = 0 a energia fixa", Icone = "ℒ",
                Descricao = "Versão geométrica: a ação abreviada W=∫p·dq é extremizada ao longo da trajetória real com energia fixa.",
                Criador = "Pierre-Louis Moreau de Maupertuis", AnoOrigin = "1744",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "a", Nome = "Limite inferior", ValorPadrao = 0 }, new() { Simbolo = "b", Nome = "Limite superior", ValorPadrao = 1 }, new() { Simbolo = "n", Nome = "Subdivisões", ValorPadrao = 100, ValorMin = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => (vars["b"] - vars["a"]) / vars["n"]
            },
            new Formula { Id = "ma_s03", Nome = "Teorema de Noether", Categoria = "Mecânica Analítica", SubCategoria = "Ação",
                Expressao = "Simetria contínua ↔ quantidade conservada", ExprTexto = "Simetria contínua da ação ↔ lei de conservação", Icone = "ℒ",
                Descricao = "Simetria temporal→energia, translação→momento linear, rotação→momento angular. Um dos teoremas mais profundos da física.",
                Criador = "Emmy Noether", AnoOrigin = "1918",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "ma_s04", Nome = "Espaço de Fase", Categoria = "Mecânica Analítica", SubCategoria = "Ação",
                Expressao = "Γ = {(q₁,...,qₙ,p₁,...,pₙ)}", ExprTexto = "Γ = {(q₁,...,qₙ,p₁,...,pₙ)} ∈ ℝ²ⁿ", Icone = "ℒ",
                Descricao = "Espaço de fase: 2n-dimensional, cada ponto representa completamente o estado do sistema. Geometria simplética natural.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "ma_s05", Nome = "Forma Simplética ω", Categoria = "Mecânica Analítica", SubCategoria = "Ação",
                Expressao = "ω = Σ dpᵢ∧dqᵢ", ExprTexto = "ω = Σᵢ dpᵢ ∧ dqᵢ", Icone = "ℒ",
                Descricao = "2-forma simplética canônica no espaço de fase. Preservada por transformações canônicas e fluxo hamiltoniano.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "ma_s06", Nome = "Teorema KAM", Categoria = "Mecânica Analítica", SubCategoria = "Ação",
                Expressao = "Toros invariantes persistem para perturbações pequenas", ExprTexto = "Perturbação pequena: maioria dos toros invariantes sobrevive", Icone = "ℒ",
                Descricao = "Kolmogorov-Arnold-Moser: em sistemas quase-integráveis, a maioria dos toros invariantes persiste sob perturbação pequena. Fronteira entre ordem e caos.",
                Criador = "Kolmogorov / Arnold / Moser", AnoOrigin = "1954-1962",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
        ]);
    }

    // ─────────────────────────────────────────────────────
    // 8. MECÂNICA ESTATÍSTICA
    // ─────────────────────────────────────────────────────
    private void AdicionarMecanicaEstatistica()
    {
        _formulas.AddRange([
            // 8.1 Termodinâmica Estatística
            new Formula { Id = "me_01", Nome = "Entropia de Boltzmann S=kB ln Ω", Categoria = "Mecânica Estatística", SubCategoria = "Fundamentos",
                Expressao = "S = kB ln Ω", ExprTexto = "S = kB ln Ω", Icone = "Z",
                Descricao = "Entropia: proporcional ao logaritmo do número de microestados Ω. Liga termodinâmica à contagem de estados microscópicos.",
                Criador = "Ludwig Boltzmann", AnoOrigin = "1877",
                Variaveis = [
                    new() { Simbolo = "omega", Nome = "Ω (microestados)", ValorPadrao = 100, ValorMin = 1 },
                    new() { Simbolo = "kB", Nome = "kB (Boltzmann)", ValorPadrao = 1.380649e-23 },
                ],
                VariavelResultado = "S (J/K)",
                Calcular = vars => vars["kB"] * Math.Log(vars["omega"]) },
            new Formula { Id = "me_02", Nome = "Entropia de Gibbs S = -kB Σ pᵢ ln pᵢ", Categoria = "Mecânica Estatística", SubCategoria = "Fundamentos",
                Expressao = "S = -kB Σ pᵢ ln pᵢ", ExprTexto = "S = −kB Σᵢ pᵢ ln pᵢ", Icone = "Z",
                Descricao = "Generalização da entropia de Boltzmann para distribuições arbitrárias. Para probabilidades iguais pᵢ=1/Ω, reduz-se a S=kB ln Ω.",
                Criador = "J. Willard Gibbs", AnoOrigin = "1902",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Valor x", ValorPadrao = 10, ValorMin = 0.001 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => Math.Log(vars["x"])
            },
            new Formula { Id = "me_03", Nome = "Distribuição de Boltzmann", Categoria = "Mecânica Estatística", SubCategoria = "Fundamentos",
                Expressao = "pᵢ = e^(-Eᵢ/kBT) / Z", ExprTexto = "pᵢ = e^(−Eᵢ/kBT) / Z", Icone = "Z",
                Descricao = "Probabilidade de ocupação do estado i com energia Eᵢ a temperatura T. Estados de menor energia são mais prováveis.",
                Criador = "Ludwig Boltzmann",
                Variaveis = [
                    new() { Simbolo = "Ei", Nome = "Eᵢ (energia do estado, J)", ValorPadrao = 1e-21 },
                    new() { Simbolo = "kB", Nome = "kB (Boltzmann)", ValorPadrao = 1.380649e-23 },
                    new() { Simbolo = "T", Nome = "Temperatura T (K)", ValorPadrao = 300, ValorMin = 0.01 },
                    new() { Simbolo = "Z", Nome = "Z (função de partição)", ValorPadrao = 10 },
                ],
                VariavelResultado = "pᵢ",
                Calcular = vars => Math.Exp(-vars["Ei"]/(vars["kB"]*vars["T"])) / vars["Z"] },
            new Formula { Id = "me_04", Nome = "Função de Partição Canônica Z", Categoria = "Mecânica Estatística", SubCategoria = "Fundamentos",
                Expressao = "Z = Σᵢ e^(-Eᵢ/kBT)", ExprTexto = "Z = Σᵢ e^(−Eᵢ/kBT)", Icone = "Z",
                Descricao = "Função de partição canônica: normalização da distribuição de Boltzmann. Todas as quantidades termodinâmicas derivam de Z.",
                Criador = "Boltzmann / Gibbs",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Expoente x", ValorPadrao = 1 }, new() { Simbolo = "A", Nome = "Amplitude A", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => vars["A"] * Math.Exp(vars["x"])
            },
            new Formula { Id = "me_05", Nome = "Energia Livre de Helmholtz F", Categoria = "Mecânica Estatística", SubCategoria = "Fundamentos",
                Expressao = "F = -kBT ln Z", ExprTexto = "F = −kBT ln Z", Icone = "Z",
                Descricao = "Energia livre de Helmholtz: potencial termodinâmico fundamental a T,V constantes. F=U-TS. Conexão direta com Z.",
                Variaveis = [
                    new() { Simbolo = "kB", Nome = "kB", ValorPadrao = 1.380649e-23 },
                    new() { Simbolo = "T", Nome = "T (K)", ValorPadrao = 300, ValorMin = 0.01 },
                    new() { Simbolo = "Z", Nome = "Z (f. partição)", ValorPadrao = 100, ValorMin = 0.001 },
                ],
                VariavelResultado = "F (J)",
                Calcular = vars => -vars["kB"] * vars["T"] * Math.Log(vars["Z"]) },
            new Formula { Id = "me_06", Nome = "⟨E⟩ = -∂lnZ/∂β", Categoria = "Mecânica Estatística", SubCategoria = "Fundamentos",
                Expressao = "⟨E⟩ = -∂ln Z/∂β  (β=1/kBT)", ExprTexto = "⟨E⟩ = −∂(ln Z)/∂β, onde β = 1/(kBT)", Icone = "Z",
                Descricao = "Energia média do sistema como derivada logarítmica da função de partição em relação ao inverso da temperatura.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Valor x", ValorPadrao = 10, ValorMin = 0.001 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => Math.Log(vars["x"])
            },
            new Formula { Id = "me_07", Nome = "Flutuação de Energia ΔE²", Categoria = "Mecânica Estatística", SubCategoria = "Fundamentos",
                Expressao = "⟨ΔE²⟩ = kBT²Cᵥ", ExprTexto = "⟨(E−⟨E⟩)²⟩ = kBT² Cᵥ", Icone = "Z",
                Descricao = "Flutuações de energia são proporcionais à capacidade calorífica. Para sistemas grandes, ΔE/⟨E⟩ ~ 1/√N → 0.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },

            // 8.2 Ensembles e Distribuições Quânticas
            new Formula { Id = "me_08", Nome = "Ensemble Microcanônico", Categoria = "Mecânica Estatística", SubCategoria = "Ensembles",
                Expressao = "pᵢ = 1/Ω (equipartição)", ExprTexto = "pᵢ = 1/Ω para E−δ ≤ Eᵢ ≤ E+δ", Icone = "Z",
                Descricao = "Ensemble microcanônico: sistema isolado. Todos os microestados com energia fixa E são equiprováveis.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "1", Nome = "1", ValorPadrao = 10 }, new() { Simbolo = "Ω", Nome = "Ω", ValorPadrao = 2, ValorMin = 0.001 } ],
                VariavelResultado = "pᵢ",
                UnidadeResultado = "",
                Calcular = vars => vars["1"] / vars["Ω"]
            },
            new Formula { Id = "me_09", Nome = "Ensemble Gran-Canônico", Categoria = "Mecânica Estatística", SubCategoria = "Ensembles",
                Expressao = "𝒵 = Σ_N e^(βμN) · Z_N", ExprTexto = "𝒵 = Σ_N e^(βμN) · Z_N (gran-canônica)", Icone = "Z",
                Descricao = "Função de partição gran-canônica: sistema troca energia E e partículas N com reservatório a T e potencial químico μ.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Expoente x", ValorPadrao = 1 }, new() { Simbolo = "A", Nome = "Amplitude A", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => vars["A"] * Math.Exp(vars["x"])
            },
            new Formula { Id = "me_10", Nome = "Potencial Gran-Canônico Ω_G", Categoria = "Mecânica Estatística", SubCategoria = "Ensembles",
                Expressao = "Ω_G = -kBT ln 𝒵 = F - μN", ExprTexto = "Ω_G = −kBT ln 𝒵 = F − μN", Icone = "Z",
                Descricao = "Potencial termodinâmico do ensemble gran-canônico. Ω_G = -PV para fluido simples.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "F", Nome = "F", ValorPadrao = 10 }, new() { Simbolo = "μN", Nome = "μN", ValorPadrao = 5 } ],
                VariavelResultado = "𝒵",
                UnidadeResultado = "",
                Calcular = vars => vars["F"] - vars["μN"]
            },
            new Formula { Id = "me_11", Nome = "Distribuição de Fermi-Dirac", Categoria = "Mecânica Estatística", SubCategoria = "Ensembles",
                Expressao = "⟨n⟩ = 1/(e^((ε-μ)/kBT) + 1)", ExprTexto = "⟨n⟩ = 1 / (e^((ε−μ)/kBT) + 1)", Icone = "Z",
                Descricao = "Distribuição de férmions (elétrons, prótons, etc.): ⟨n⟩∈[0,1] pelo princípio de exclusão de Pauli. A T=0: degrau em ε=μ.",
                Criador = "Enrico Fermi / Paul Dirac", AnoOrigin = "1926",
                Variaveis = [
                    new() { Simbolo = "eps", Nome = "ε (energia)", ValorPadrao = 0.1 },
                    new() { Simbolo = "mu", Nome = "μ (potencial químico)", ValorPadrao = 0.05 },
                    new() { Simbolo = "kBT", Nome = "kBT", ValorPadrao = 0.026 },
                ],
                VariavelResultado = "⟨n⟩",
                Calcular = vars => 1.0 / (Math.Exp((vars["eps"]-vars["mu"])/vars["kBT"]) + 1) },
            new Formula { Id = "me_12", Nome = "Distribuição de Bose-Einstein", Categoria = "Mecânica Estatística", SubCategoria = "Ensembles",
                Expressao = "⟨n⟩ = 1/(e^((ε-μ)/kBT) - 1)", ExprTexto = "⟨n⟩ = 1 / (e^((ε−μ)/kBT) − 1)", Icone = "Z",
                Descricao = "Distribuição de bósons (fótons, fônons, etc.): sem limite de ocupação. Para fótons: μ=0.",
                Criador = "S.N. Bose / Albert Einstein", AnoOrigin = "1924",
                Variaveis = [
                    new() { Simbolo = "eps", Nome = "ε (energia)", ValorPadrao = 0.1 },
                    new() { Simbolo = "mu", Nome = "μ", ValorPadrao = 0 },
                    new() { Simbolo = "kBT", Nome = "kBT", ValorPadrao = 0.026 },
                ],
                VariavelResultado = "⟨n⟩",
                Calcular = vars => { double x = (vars["eps"]-vars["mu"])/vars["kBT"]; return x>0? 1.0/(Math.Exp(x)-1) : double.NaN; } },
            new Formula { Id = "me_13", Nome = "Lei de Planck (Corpo Negro)", Categoria = "Mecânica Estatística", SubCategoria = "Ensembles",
                Expressao = "u(ν) = (8πhν³/c³)·1/(e^(hν/kBT)-1)", ExprTexto = "u(ν) = (8πhν³/c³) / (e^(hν/kBT) − 1)", Icone = "Z",
                Descricao = "Densidade espectral de energia do corpo negro. Origem da mecânica quântica: Planck introduziu quantização E=hν para derivá-la.",
                Criador = "Max Planck", AnoOrigin = "1900",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Expoente x", ValorPadrao = 1 }, new() { Simbolo = "A", Nome = "Amplitude A", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => vars["A"] * Math.Exp(vars["x"])
            },
            new Formula { Id = "me_14", Nome = "Lei de Stefan-Boltzmann", Categoria = "Mecânica Estatística", SubCategoria = "Ensembles",
                Expressao = "P = σT⁴ (σ=5.67×10⁻⁸ W/m²K⁴)", ExprTexto = "P = σT⁴", Icone = "Z",
                Descricao = "Potência total irradiada por corpo negro é proporcional a T⁴. Integração da lei de Planck sobre todas as frequências.",
                Criador = "Stefan / Boltzmann", AnoOrigin = "1879/1884",
                Variaveis = [
                    new() { Simbolo = "T", Nome = "T (K)", ValorPadrao = 5778, ValorMin = 0.01 },
                    new() { Simbolo = "sigma", Nome = "σ (W/m²K⁴)", ValorPadrao = 5.670374419e-8 },
                ],
                VariavelResultado = "P (W/m²)",
                Calcular = vars => vars["sigma"] * Math.Pow(vars["T"], 4) },
            new Formula { Id = "me_15", Nome = "Equipartição de Energia", Categoria = "Mecânica Estatística", SubCategoria = "Ensembles",
                Expressao = "⟨½kx²⟩ = ½kBT por grau de liberdade", ExprTexto = "⟨E_quadrático⟩ = ½kBT por grau de liberdade", Icone = "Z",
                Descricao = "Cada grau de liberdade quadrático (cinético ou potencial) contribui ½kBT à energia média. Válido no regime clássico.",
                Criador = "Maxwell / Boltzmann",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },

            // 8.3 Modelos e Transições de Fase
            new Formula { Id = "me_16", Nome = "Modelo de Ising (1D)", Categoria = "Mecânica Estatística", SubCategoria = "Modelos",
                Expressao = "H = -J Σ sᵢsᵢ₊₁ - h Σ sᵢ", ExprTexto = "H = −J Σ sᵢsᵢ₊₁ − h Σ sᵢ (sᵢ = ±1)", Icone = "Z",
                Descricao = "Modelo de Ising: spins ±1 em rede com interação entre vizinhos (J) e campo externo (h). Sem transição de fase em 1D (Ising, 1925).",
                Criador = "Ernst Ising / Wilhelm Lenz", AnoOrigin = "1925",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "me_17", Nome = "Magnetização Média (Ising)", Categoria = "Mecânica Estatística", SubCategoria = "Modelos",
                Expressao = "⟨m⟩ = -(1/N)∂F/∂h", ExprTexto = "⟨m⟩ = −(1/N) ∂F/∂h", Icone = "Z",
                Descricao = "Magnetização por spin como derivada da energia livre em relação ao campo magnético.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "me_18", Nome = "Temperatura Crítica (Ising 2D)", Categoria = "Mecânica Estatística", SubCategoria = "Modelos",
                Expressao = "sinh(2J/kBTc) = 1 → Tc = 2J/(kB·ln(1+√2))", ExprTexto = "kBTc = 2J / ln(1+√2) ≈ 2.269J/kB", Icone = "Z",
                Descricao = "Solução exata de Onsager para o modelo de Ising 2D: transição de fase a Tc. Magnetização espontânea abaixo de Tc.",
                Criador = "Lars Onsager", AnoOrigin = "1944",
                Variaveis = [ new() { Simbolo = "J", Nome = "J (interação)", ValorPadrao = 1 } ],
                VariavelResultado = "kBTc / J",
                Calcular = vars => 2 * vars["J"] / Math.Log(1 + Math.Sqrt(2)) },
            new Formula { Id = "me_19", Nome = "Expoentes Críticos", Categoria = "Mecânica Estatística", SubCategoria = "Modelos",
                Expressao = "m~(Tc-T)^β; Cv~|T-Tc|^(-α); χ~|T-Tc|^(-γ)", ExprTexto = "m ∝ (Tc−T)^β; Cv ∝ |T−Tc|^(−α); χ ∝ |T−Tc|^(−γ)", Icone = "Z",
                Descricao = "Comportamento próximo ao ponto crítico segue leis de potência universais. Expoentes dependem apenas da dimensão e simetria (universalidade).",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "me_20", Nome = "Teoria de Campo Médio (Landau)", Categoria = "Mecânica Estatística", SubCategoria = "Modelos",
                Expressao = "F = F₀ + a(T-Tc)m² + bm⁴ + ...", ExprTexto = "F = F₀ + a(T−Tc)m² + bm⁴ + ... (expansão de Landau)", Icone = "Z",
                Descricao = "Expansão de Landau da energia livre em termos do parâmetro de ordem m. Campo médio: β=1/2, γ=1, α=0. Exato em d altas.",
                Criador = "Lev Landau", AnoOrigin = "1937",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "F₀", Nome = "F₀", ValorPadrao = 10 }, new() { Simbolo = "a", Nome = "a", ValorPadrao = 5 } ],
                VariavelResultado = "F",
                UnidadeResultado = "",
                Calcular = vars => vars["F₀"] + vars["a"]
            },
        ]);
    }

    // ─────────────────────────────────────────────────────
    // 9. TEORIA QUÂNTICA DE CAMPOS
    // ─────────────────────────────────────────────────────
    private void AdicionarTeoriaQuanticaCampos()
    {
        _formulas.AddRange([
            // 9.1 Fundamentos QFT
            new Formula { Id = "qft_01", Nome = "Ação de Klein-Gordon", Categoria = "Teoria Quântica de Campos", SubCategoria = "Fundamentos",
                Expressao = "S = ∫(½∂μφ∂ᵘφ - ½m²φ²) d⁴x", ExprTexto = "S = ∫ (½∂μφ ∂ᵘφ − ½m²φ²) d⁴x", Icone = "ψ",
                Descricao = "Ação para campo escalar real livre. A equação de Euler-Lagrange dá a equação de Klein-Gordon: (□+m²)φ=0.",
                Criador = "Klein / Gordon", AnoOrigin = "1926",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "a", Nome = "Limite inferior", ValorPadrao = 0 }, new() { Simbolo = "b", Nome = "Limite superior", ValorPadrao = 1 }, new() { Simbolo = "n", Nome = "Subdivisões", ValorPadrao = 100, ValorMin = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => (vars["b"] - vars["a"]) / vars["n"]
            },
            new Formula { Id = "qft_02", Nome = "Equação de Klein-Gordon", Categoria = "Teoria Quântica de Campos", SubCategoria = "Fundamentos",
                Expressao = "(∂²/∂t² - ∇² + m²)φ = 0", ExprTexto = "(□ + m²)φ = 0; □ = ∂²/∂t² − ∇²", Icone = "ψ",
                Descricao = "Equação relativística para campo escalar. Versão covariante da eq. de Schrödinger para spin 0. Admite soluções com energia negativa.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "qft_03", Nome = "Equação de Dirac", Categoria = "Teoria Quântica de Campos", SubCategoria = "Fundamentos",
                Expressao = "(iγᵘ∂μ - m)ψ = 0", ExprTexto = "(iγᵘ∂μ − m)ψ = 0", Icone = "ψ",
                Descricao = "Equação de Dirac: equação relativística de 1ª ordem para férmions (spin 1/2). Previu a existência do pósitron.",
                Criador = "Paul Dirac", AnoOrigin = "1928",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "qft_04", Nome = "Lagrangiana de Dirac", Categoria = "Teoria Quântica de Campos", SubCategoria = "Fundamentos",
                Expressao = "ℒ = ψ̄(iγᵘ∂μ - m)ψ", ExprTexto = "ℒ = ψ̄(iγᵘ∂μ − m)ψ", Icone = "ψ",
                Descricao = "Lagrangiana do campo de Dirac livre. ψ̄ = ψ†γ⁰. Invariante sob transformações de Lorentz.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "qft_05", Nome = "Propagador de Feynman (Escalar)", Categoria = "Teoria Quântica de Campos", SubCategoria = "Fundamentos",
                Expressao = "ΔF(p) = i/(p²-m²+iε)", ExprTexto = "ΔF(p) = i / (p² − m² + iε)", Icone = "ψ",
                Descricao = "Propagador escalar no espaço de momentos: amplitude de propagação de partícula virtual. Polo em p²=m² (partícula real).",
                Criador = "Richard Feynman", AnoOrigin = "1949",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "qft_06", Nome = "Quantização de Campo Escalar", Categoria = "Teoria Quântica de Campos", SubCategoria = "Fundamentos",
                Expressao = "φ(x) = ∫(aₖe^(-ikx) + a†ₖe^(ikx)) d³k", ExprTexto = "φ(x) = ∫ [aₖ e^(−ikx) + a†ₖ e^(ikx)] d³k/(2π)³√(2ωₖ)", Icone = "ψ",
                Descricao = "Quantização canônica: campo expandido em modos, com operadores de criação a†ₖ e aniquilação aₖ. [aₖ,a†ₖ']=δ³(k-k').",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Valor x", ValorPadrao = 4, ValorMin = 0 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => Math.Sqrt(vars["x"])
            },
            new Formula { Id = "qft_07", Nome = "Relação de Anticomutação (Férmions)", Categoria = "Teoria Quântica de Campos", SubCategoria = "Fundamentos",
                Expressao = "{ψ̂(x), ψ̂†(y)} = δ³(x-y)", ExprTexto = "{ψ̂ₐ(x), ψ̂†ᵦ(y)} = δₐᵦ δ³(x−y)", Icone = "ψ",
                Descricao = "Campos fermiônicos satisfazem relações de anticomutação (estatística de Fermi-Dirac). Garante princípio de Pauli.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "qft_08", Nome = "Regras de Feynman (Diagramas)", Categoria = "Teoria Quântica de Campos", SubCategoria = "Fundamentos",
                Expressao = "M = Σ diagramas (vértice × propagadores × momentos)", ExprTexto = "iM = Σ (diagramas de Feynman)", Icone = "ψ",
                Descricao = "Amplitude de espalhamento: soma sobre diagramas de Feynman. Cada diagrama = produto de propagadores e constantes de acoplamento.",
                Criador = "Richard Feynman", AnoOrigin = "1948",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "qft_09", Nome = "Seção de Choque σ", Categoria = "Teoria Quântica de Campos", SubCategoria = "Fundamentos",
                Expressao = "dσ = |M|² × cinemática × espaço de fase", ExprTexto = "dσ ∝ |M|² × dΠ (espaço de fase)", Icone = "ψ",
                Descricao = "Seção de choque: probabilidade de interação. Proporcional ao módulo quadrado da amplitude de espalhamento M.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "qft_10", Nome = "Renormalização: Equação do Grupo de Renorm.", Categoria = "Teoria Quântica de Campos", SubCategoria = "Fundamentos",
                Expressao = "μ dg/dμ = β(g)", ExprTexto = "μ dg/dμ = β(g) (função beta)", Icone = "ψ",
                Descricao = "Equação do grupo de renormalização: como constantes de acoplamento 'correm' com a escala de energia μ. β<0 → liberdade assintótica.",
                Criador = "K. Wilson / Callan-Symanzik", AnoOrigin = "~1970",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },

            // 9.2 QED
            new Formula { Id = "qft_qed01", Nome = "Lagrangiana QED", Categoria = "Teoria Quântica de Campos", SubCategoria = "QED",
                Expressao = "ℒ = ψ̄(iγᵘDμ-m)ψ - ¼FμνFᵘᵛ", ExprTexto = "ℒ_QED = ψ̄(iγᵘDμ−m)ψ − ¼FμνFᵘᵛ", Icone = "ψ",
                Descricao = "Lagrangiana da Eletrodinâmica Quântica. Dμ=∂μ+ieAμ (derivada covariante). Descreve elétrons, pósitrons e fótons.",
                Criador = "Tomonaga / Schwinger / Feynman", AnoOrigin = "1947-1949",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "qft_qed02", Nome = "Tensor Eletromagnético Fμν", Categoria = "Teoria Quântica de Campos", SubCategoria = "QED",
                Expressao = "Fμν = ∂μAν - ∂νAμ", ExprTexto = "Fμν = ∂μAν − ∂νAμ", Icone = "ψ",
                Descricao = "Tensor de força eletromagnético. Contém campos E e B: F⁰ⁱ=Eⁱ/c, Fⁱʲ=-εⁱʲᵏBᵏ.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "qft_qed03", Nome = "Propagador do Fóton", Categoria = "Teoria Quântica de Campos", SubCategoria = "QED",
                Expressao = "Dμν(q) = -igμν/(q²+iε)", ExprTexto = "Dμν(q) = −igμν / (q² + iε) (gauge de Feynman)", Icone = "ψ",
                Descricao = "Propagador do fóton no gauge de Feynman. Fóton é bóson de gauge sem massa da interação eletromagnética.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "qft_qed04", Nome = "Secção de Choque de Compton", Categoria = "Teoria Quântica de Campos", SubCategoria = "QED",
                Expressao = "dσ/dΩ ∝ (α²/2m²)(ω'/ω)² ...", ExprTexto = "Fórmula de Klein-Nishina para espalhamento Compton", Icone = "ψ",
                Descricao = "Klein-Nishina: seção de choque do espalhamento Compton (fóton-elétron). Resultado fundamental da QED.",
                Criador = "Klein / Nishina", AnoOrigin = "1929",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "qft_qed05", Nome = "Momento Magnético Anômalo", Categoria = "Teoria Quântica de Campos", SubCategoria = "QED",
                Expressao = "g-2 = α/π + ... ≈ 0.00231...", ExprTexto = "aₑ = (g−2)/2 = α/(2π) + O(α²) ≈ 0.00116", Icone = "ψ",
                Descricao = "Correção quântica ao momento magnético do elétron. Schwinger calculou α/(2π). Acordo teoria-experimento: 12 casas decimais!",
                Criador = "Julian Schwinger", AnoOrigin = "1948",
                Variaveis = [ new() { Simbolo = "alpha", Nome = "α (constante estrut. fina)", ValorPadrao = 0.0072973525693 } ],
                VariavelResultado = "aₑ ≈ α/(2π)",
                Calcular = vars => vars["alpha"] / (2 * Math.PI) },
            new Formula { Id = "qft_qed06", Nome = "Constante de Estrutura Fina α", Categoria = "Teoria Quântica de Campos", SubCategoria = "QED",
                Expressao = "α = e²/(4πε₀ℏc) ≈ 1/137", ExprTexto = "α = e²/(4πε₀ℏc) ≈ 1/137.036", Icone = "ψ",
                Descricao = "Constante adimensional que mede força do acoplamento eletromagnético. α≈1/137: número 'mágico' da física.",
                Criador = "Arnold Sommerfeld", AnoOrigin = "1916",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "e", Nome = "e", ValorPadrao = 5 } ],
                VariavelResultado = "α",
                UnidadeResultado = "",
                Calcular = vars => vars["e"] * vars["e"]
            },
            new Formula { Id = "qft_qed07", Nome = "Invariância de Gauge U(1)", Categoria = "Teoria Quântica de Campos", SubCategoria = "QED",
                Expressao = "ψ→e^(iα(x))ψ; Aμ→Aμ-∂μα/e", ExprTexto = "ψ → e^(iα(x))ψ; Aμ → Aμ − (1/e)∂μα", Icone = "ψ",
                Descricao = "QED: teoria de gauge com grupo U(1). Exigir invariância local sob mudança de fase de ψ requer introduzir campo de gauge Aμ (fóton).",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Expoente x", ValorPadrao = 1 }, new() { Simbolo = "A", Nome = "Amplitude A", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => vars["A"] * Math.Exp(vars["x"])
            },

            // 9.3 QCD
            new Formula { Id = "qft_qcd01", Nome = "Lagrangiana QCD", Categoria = "Teoria Quântica de Campos", SubCategoria = "QCD",
                Expressao = "ℒ = Σ_f ψ̄_f(iγᵘDμ-m_f)ψ_f - ¼G^a_μνG^aμν", ExprTexto = "ℒ_QCD = Σ_f ψ̄_f(iD̸−m_f)ψ_f − ¼G^a_μν G^{aμν}", Icone = "ψ",
                Descricao = "Lagrangiana da Cromodinâmica Quântica. Quarks (ψ_f, 6 sabores) interagem via campo de gauge gluônico (G^a_μν). Grupo SU(3) de cor.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "qft_qcd02", Nome = "Tensor Gluônico", Categoria = "Teoria Quântica de Campos", SubCategoria = "QCD",
                Expressao = "G^a_μν = ∂μA^a_ν - ∂νA^a_μ + gf^abc A^b_μ A^c_ν", ExprTexto = "G^a_μν = ∂μA^a_ν − ∂νA^a_μ + g f^{abc} A^b_μ A^c_ν", Icone = "ψ",
                Descricao = "Tensor de campo gluônico: inclui termo não-linear (auto-interação dos glúons). SU(3) é não-abeliano → glúons interagem entre si.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "qft_qcd03", Nome = "Liberdade Assintótica", Categoria = "Teoria Quântica de Campos", SubCategoria = "QCD",
                Expressao = "β₀ = (11Nc-2Nf)/3 > 0 → g(μ)→0 p/ μ→∞", ExprTexto = "β(g) = −β₀g³/(16π²) + ...; β₀ > 0 → g→0 em alta energia", Icone = "ψ",
                Descricao = "QCD é assintoticamente livre: acoplamento forte diminui em altas energias (distâncias curtas). Prêmio Nobel 2004.",
                Criador = "Gross / Wilczek / Politzer", AnoOrigin = "1973",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "qft_qcd04", Nome = "Confinamento de Quarks", Categoria = "Teoria Quântica de Campos", SubCategoria = "QCD",
                Expressao = "V(r) ∝ σ·r (potencial linear em distâncias grandes)", ExprTexto = "V(r) ∝ σ·r para r grande → confinamento", Icone = "ψ",
                Descricao = "Quarks não existem isolados: potencial entre quarks cresce linearmente com distância. Criar par quark-antiquark é energeticamente favorável.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "qft_qcd05", Nome = "Modelo Padrão: Grupo de Gauge", Categoria = "Teoria Quântica de Campos", SubCategoria = "QCD",
                Expressao = "SU(3)_C × SU(2)_L × U(1)_Y", ExprTexto = "SU(3)_C × SU(2)_L × U(1)_Y", Icone = "ψ",
                Descricao = "Grupo de gauge do Modelo Padrão: SU(3) (cor/QCD), SU(2)×U(1) (eletrofraca, quebrada pelo Higgs para U(1)_EM). 12+3+1=16 bósons de gauge.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "qft_qcd06", Nome = "Mecanismo de Higgs", Categoria = "Teoria Quântica de Campos", SubCategoria = "QCD",
                Expressao = "V(φ) = μ²|φ|² + λ|φ|⁴ (μ²<0)", ExprTexto = "V(φ) = μ²|φ|² + λ|φ|⁴ com μ² < 0 ('chapéu mexicano')", Icone = "ψ",
                Descricao = "Quebra espontânea de simetria: potencial com mínimo não trivial v=√(-μ²/λ). Gera massa para W±, Z⁰ e férmions.",
                Criador = "Higgs / Brout-Englert", AnoOrigin = "1964",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "qft_qcd07", Nome = "Massa de Higgs mH", Categoria = "Teoria Quântica de Campos", SubCategoria = "QCD",
                Expressao = "mH = √(2λ)·v ≈ 125 GeV/c²", ExprTexto = "mH = √(2λ) · v ≈ 125.1 GeV/c²", Icone = "ψ",
                Descricao = "Massa do bóson de Higgs: mH ≈ 125.1 GeV. Descoberto experimentalmente no LHC (ATLAS e CMS) em 2012.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Valor x", ValorPadrao = 4, ValorMin = 0 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => Math.Sqrt(vars["x"])
            },
        ]);
    }

    // ─────────────────────────────────────────────────────
    // 10. RELATIVIDADE GERAL
    // ─────────────────────────────────────────────────────
    private void AdicionarRelatividadeGeral()
    {
        _formulas.AddRange([
            // 10.1 Fundamentos da Relatividade Especial
            new Formula { Id = "rg_01", Nome = "Intervalo Espaço-Temporal", Categoria = "Relatividade Geral", SubCategoria = "Relatividade Especial",
                Expressao = "ds² = -c²dt² + dx² + dy² + dz²", ExprTexto = "ds² = −c²dt² + dx² + dy² + dz² (Minkowski)", Icone = "G",
                Descricao = "Métrica de Minkowski: espaço-tempo plano da relatividade especial. ds²<0 (tempo), ds²>0 (espaço), ds²=0 (luz).",
                Criador = "Hermann Minkowski", AnoOrigin = "1908",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "rg_02", Nome = "Transformação de Lorentz", Categoria = "Relatividade Geral", SubCategoria = "Relatividade Especial",
                Expressao = "t'=γ(t-vx/c²); x'=γ(x-vt); γ=1/√(1-v²/c²)", ExprTexto = "t' = γ(t − vx/c²); x' = γ(x − vt); γ = 1/√(1−v²/c²)", Icone = "G",
                Descricao = "Transformação entre referenciais inerciais. Reduz-se a Galileu para v≪c.",
                Criador = "Hendrik Lorentz / Albert Einstein", AnoOrigin = "1904/1905",
                Variaveis = [
                    new() { Simbolo = "v", Nome = "v (velocidade relativa, m/s)", ValorPadrao = 0.5 * 3e8 },
                    new() { Simbolo = "c", Nome = "c (velocidade da luz)", ValorPadrao = 2.998e8 },
                ],
                VariavelResultado = "γ (fator de Lorentz)",
                Calcular = vars => 1.0 / Math.Sqrt(1 - Math.Pow(vars["v"]/vars["c"], 2)) },
            new Formula { Id = "rg_03", Nome = "E = mc²", Categoria = "Relatividade Geral", SubCategoria = "Relatividade Especial",
                Expressao = "E₀ = mc² (energia em repouso)", ExprTexto = "E₀ = mc²", Icone = "G",
                Descricao = "Equivalência massa-energia: massa em repouso m equivale a energia E₀=mc². A equação mais famosa da física.",
                Criador = "Albert Einstein", AnoOrigin = "1905",
                Variaveis = [
                    new() { Simbolo = "m", Nome = "m (kg)", ValorPadrao = 1 },
                    new() { Simbolo = "c", Nome = "c (m/s)", ValorPadrao = 2.998e8 },
                ],
                VariavelResultado = "E₀ (J)",
                Calcular = vars => vars["m"] * vars["c"] * vars["c"] },
            new Formula { Id = "rg_04", Nome = "Relação Energia-Momento", Categoria = "Relatividade Geral", SubCategoria = "Relatividade Especial",
                Expressao = "E² = (pc)² + (mc²)²", ExprTexto = "E² = (pc)² + (mc²)²", Icone = "G",
                Descricao = "Relação relativística entre energia total E, momento p e massa m. Para fótons (m=0): E=pc. Para repouso (p=0): E=mc².",
                Criador = "Einstein", AnoOrigin = "1905",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "rg_05", Nome = "Quadrivetor Energia-Momento", Categoria = "Relatividade Geral", SubCategoria = "Relatividade Especial",
                Expressao = "pᵘ = (E/c, p)", ExprTexto = "pᵘ = (E/c, p⃗); pμpᵘ = −m²c²", Icone = "G",
                Descricao = "Quadrivetor energia-momento unifica energia e momento numa entidade covariante de Lorentz.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },

            // 10.2 Geometria e Equações de Einstein
            new Formula { Id = "rg_06", Nome = "Métrica de Espaço-Tempo Geral", Categoria = "Relatividade Geral", SubCategoria = "Geometria",
                Expressao = "ds² = gμν dxᵘ dxᵛ", ExprTexto = "ds² = gμν dxᵘ dxᵛ", Icone = "G",
                Descricao = "Métrica geral do espaço-tempo: tensor métrico gμν(x) determina intervalos e a geometria. Em coord. cartesianas de Minkowski: gμν=ημν.",
                Criador = "Einstein", AnoOrigin = "1915",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "rg_07", Nome = "Equações de Campo de Einstein", Categoria = "Relatividade Geral", SubCategoria = "Geometria",
                Expressao = "Rμν - ½gμνR + Λgμν = (8πG/c⁴)Tμν", ExprTexto = "Rμν − ½gμν R + Λgμν = (8πG/c⁴) Tμν", Icone = "G",
                Descricao = "Equações de Einstein: a curvatura do espaço-tempo (lado esquerdo) é determinada pela distribuição de matéria-energia (Tμν). Λ: constante cosmológica.",
                Criador = "Albert Einstein", AnoOrigin = "1915",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "rg_08", Nome = "Tensor Energia-Momento Tμν", Categoria = "Relatividade Geral", SubCategoria = "Geometria",
                Expressao = "Tμν: fonte de gravitação (energia, momento, pressão)", ExprTexto = "Tμν = (ρ+p/c²)uμuν + p gμν (fluido perfeito)", Icone = "G",
                Descricao = "Tensor energia-momento: descreve distribuição de energia, momento linear, tensão e pressão. Para fluido perfeito: ρ (densidade), p (pressão).",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "rg_09", Nome = "Equação Geodésica", Categoria = "Relatividade Geral", SubCategoria = "Geometria",
                Expressao = "d²xᵘ/dτ² + Γᵘαβ (dxᵅ/dτ)(dxᵝ/dτ) = 0", ExprTexto = "d²xᵘ/dτ² + Γᵘ_αβ (dxᵅ/dτ)(dxᵝ/dτ) = 0", Icone = "G",
                Descricao = "Partículas livres seguem geodésicas do espaço-tempo curvo. Gravidade não é uma força, mas curvatura do espaço-tempo.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "rg_10", Nome = "Princípio de Equivalência", Categoria = "Relatividade Geral", SubCategoria = "Geometria",
                Expressao = "Massa inercial = massa gravitacional", ExprTexto = "mᵢₙₑᵣ = mᵍᵣₐᵥ (localmente, gravidade ≡ aceleração)", Icone = "G",
                Descricao = "Localmente, um campo gravitacional é indistinguível de aceleração. Motivação fundamental de Einstein para a RG.",
                Criador = "Einstein", AnoOrigin = "1907",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "rg_11", Nome = "Identidade de Bianchi", Categoria = "Relatividade Geral", SubCategoria = "Geometria",
                Expressao = "∇ᵘGμν = 0 (Gμν = Rμν - ½gμνR)", ExprTexto = "∇ᵘGμν = 0 (conservação automática)", Icone = "G",
                Descricao = "Identidade de Bianchi contraída: a divergência do tensor de Einstein é zero. Garante conservação de energia-momento ∇ᵘTμν=0.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },

            // 10.3 Soluções Clássicas e Cosmologia
            new Formula { Id = "rg_12", Nome = "Métrica de Schwarzschild", Categoria = "Relatividade Geral", SubCategoria = "Soluções",
                Expressao = "ds²=-(1-rₛ/r)c²dt²+(1-rₛ/r)⁻¹dr²+r²dΩ²", ExprTexto = "ds² = −(1−rₛ/r)c²dt² + (1−rₛ/r)⁻¹dr² + r²dΩ²", Icone = "G",
                Descricao = "Solução esfericamente simétrica no vácuo: descreve espaço-tempo fora de massa esférica. rₛ = raio de Schwarzschild.",
                Criador = "Karl Schwarzschild", AnoOrigin = "1916",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "rg_13", Nome = "Raio de Schwarzschild", Categoria = "Relatividade Geral", SubCategoria = "Soluções",
                Expressao = "rₛ = 2GM/c²", ExprTexto = "rₛ = 2GM/c²", Icone = "G",
                Descricao = "Raio de Schwarzschild: raio do horizonte de eventos de um buraco negro de Schwarzschild. Para M_sol: rₛ≈3 km.",
                Criador = "Karl Schwarzschild", AnoOrigin = "1916",
                Variaveis = [
                    new() { Simbolo = "M", Nome = "M (massa, kg)", ValorPadrao = 1.989e30 },
                    new() { Simbolo = "G", Nome = "G (const. gravitacional)", ValorPadrao = 6.674e-11 },
                    new() { Simbolo = "c", Nome = "c (m/s)", ValorPadrao = 2.998e8 },
                ],
                VariavelResultado = "rₛ (m)",
                Calcular = vars => 2 * vars["G"] * vars["M"] / (vars["c"] * vars["c"]) },
            new Formula { Id = "rg_14", Nome = "Desvio Gravitacional da Luz", Categoria = "Relatividade Geral", SubCategoria = "Soluções",
                Expressao = "δφ = 4GM/(c²b)", ExprTexto = "δφ = 4GM/(c²b) (desvio angular)", Icone = "G",
                Descricao = "Desvio da trajetória da luz pelo campo gravitacional. Para o Sol: δφ≈1.75''. Confirmado por Eddington em 1919.",
                Criador = "Einstein", AnoOrigin = "1916",
                Variaveis = [
                    new() { Simbolo = "M", Nome = "M (massa, kg)", ValorPadrao = 1.989e30 },
                    new() { Simbolo = "b", Nome = "b (parâmetro de impacto, m)", ValorPadrao = 6.96e8 },
                    new() { Simbolo = "G", Nome = "G", ValorPadrao = 6.674e-11 },
                    new() { Simbolo = "c", Nome = "c (m/s)", ValorPadrao = 2.998e8 },
                ],
                VariavelResultado = "δφ (rad)",
                Calcular = vars => 4*vars["G"]*vars["M"]/(vars["c"]*vars["c"]*vars["b"]) },
            new Formula { Id = "rg_15", Nome = "Dilatação Gravitacional do Tempo", Categoria = "Relatividade Geral", SubCategoria = "Soluções",
                Expressao = "dτ = dt√(1 - rₛ/r)", ExprTexto = "dτ = dt √(1 − rₛ/r)", Icone = "G",
                Descricao = "Relógios mais próximos de massa gravitacional marcam tempo mais lentamente. Medido com relógios atômicos em aviões e satélites GPS.",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Valor x", ValorPadrao = 4, ValorMin = 0 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => Math.Sqrt(vars["x"])
            },
            new Formula { Id = "rg_16", Nome = "Redshift Gravitacional", Categoria = "Relatividade Geral", SubCategoria = "Soluções",
                Expressao = "1+z = √(1-rₛ/r_emissor)/√(1-rₛ/r_observador)", ExprTexto = "1+z = √(1−rₛ/rₑ) / √(1−rₛ/rₒ)", Icone = "G",
                Descricao = "Luz que sai de campo gravitacional perde energia: comprimento de onda aumenta (redshift). Verificado pelo efeito Pound-Rebka.",
                Criador = "Einstein", AnoOrigin = "1907",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Valor x", ValorPadrao = 4, ValorMin = 0 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = vars => Math.Sqrt(vars["x"])
            },
            new Formula { Id = "rg_17", Nome = "Métrica FLRW (Cosmologia)", Categoria = "Relatividade Geral", SubCategoria = "Soluções",
                Expressao = "ds²=-c²dt²+a(t)²[dr²/(1-kr²)+r²dΩ²]", ExprTexto = "ds² = −c²dt² + a(t)² [dr²/(1−kr²) + r²dΩ²]", Icone = "G",
                Descricao = "Métrica de Friedmann-Lemaître-Robertson-Walker: descreve universo homogêneo e isotrópico em expansão. a(t)=fator de escala, k=curvatura.",
                Criador = "Friedmann / Lemaître / Robertson / Walker", AnoOrigin = "1920s",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "rg_18", Nome = "Equação de Friedmann", Categoria = "Relatividade Geral", SubCategoria = "Soluções",
                Expressao = "(ȧ/a)² = 8πGρ/3 - kc²/a² + Λ/3", ExprTexto = "H² = (ȧ/a)² = 8πGρ/3 − kc²/a² + Λ/3", Icone = "G",
                Descricao = "Equação de Friedmann: governa expansão do universo. H=ȧ/a é a constante de Hubble. ρ inclui matéria, radiação e energia escura.",
                Criador = "Alexander Friedmann", AnoOrigin = "1922",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
            new Formula { Id = "rg_19", Nome = "Lei de Hubble-Lemaître", Categoria = "Relatividade Geral", SubCategoria = "Soluções",
                Expressao = "v = H₀d", ExprTexto = "v = H₀ · d (velocidade de recessão)", Icone = "G",
                Descricao = "Galáxias se afastam com velocidade proporcional à distância. H₀≈70 km/s/Mpc. Evidência da expansão do universo.",
                Criador = "Hubble / Lemaître", AnoOrigin = "1929",
                Variaveis = [
                    new() { Simbolo = "H0", Nome = "H₀ (km/s/Mpc)", ValorPadrao = 70 },
                    new() { Simbolo = "d", Nome = "Distância d (Mpc)", ValorPadrao = 10 },
                ],
                VariavelResultado = "v (km/s)",
                Calcular = vars => vars["H0"] * vars["d"] },
            new Formula { Id = "rg_20", Nome = "Radiação de Hawking", Categoria = "Relatividade Geral", SubCategoria = "Soluções",
                Expressao = "T_BH = ℏc³/(8πGMkB)", ExprTexto = "T_BH = ℏc³ / (8πGMkB)", Icone = "G",
                Descricao = "Buracos negros emitem radiação térmica com temperatura T proporcional à gravidade superficial. BN têm entropia e 'evaporam' lentamente.",
                Criador = "Stephen Hawking", AnoOrigin = "1974",
                ExemploPratico = "Utilize os valores padrão para calcular o resultado.",
                Variaveis = [ new() { Simbolo = "x", Nome = "Parâmetro x", ValorPadrao = 1 }, new() { Simbolo = "y", Nome = "Parâmetro y", ValorPadrao = 1 } ],
                VariavelResultado = "Resultado",
                UnidadeResultado = "",
                Calcular = _ => double.NaN
            },
        ]);
    }
}
